---
# FIXME command works in interactive shell only and /quit is always executed first
- name: Weechat command (execute manually)
  debug:
    msg: "weechat --no-connect --no-scripts --run-command '/{{ weechat_cmd | join('; /') }}'"

- name: Weechat configuration
  vars:
    keys: "{{ item.key | split('.') }}"
    file: "{{ [0] | map('extract', keys) | first }}"
    section: "{{ [1] | map('extract', keys) | first }}"
    option: "{{ range(2, keys | length) | map('extract', keys) | join('.') }}"
  ini_file:
    dest: "{{ ansible_env.HOME }}/.weechat/{{ file }}.conf"
    section: "{{ section }}"
    option: "{{ option }}"
    value: "{{ item.value }}"
    backup: yes
  with_dict: "{{ weechat_conf }}"
