---
dependencies:

  - role: dotfiles
    paths:
      - name: xresources
        prefix: .
        pattern: "*.j2" # "Xresources"
        template: yes
      - name: xresources/files/Xresources.d
        dest: .Xresources.d

galaxy_info:
  galaxy_tags: system
