---
# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

# disableStartupPopups: true

# git:
#   autoForwardBranches: none

gui:
  border: single # hidden
  # screenMode: half
  showRandomTip: true

# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#custom-command-for-copying-to-and-pasting-from-clipboard
os:
  editPreset: helix
  # copyToClipboardCmd: >
  #   if [[ "$TERM" =~ ^(screen|tmux) ]]; then
  #     printf "\033Ptmux;\033\033]52;c;$(printf {{text}} | base64 -w 0)\a\033\\" > /dev/tty
  #   else
  #     printf "\033]52;c;$(printf {{text}} | base64 -w 0)\a" > /dev/tty
  #   fi

# If true, display a confirmation when subprocess terminates. This allows you
# to view the output of the subprocess before returning to Lazygit.
promptToReturnFromSubprocess: true

# Background refreshes
refresher:
  # File/submodule refresh interval in seconds.
  # Auto-refresh can be disabled via option 'git.autoRefresh'.
  refreshInterval: 10

  # Re-fetch interval in seconds.
  # Auto-fetch can be disabled via option 'git.autoFetch'.
  fetchInterval: 60

# Periodic update checks
update:
  method: never
