---
enabled: "{{ .features.vscodium }}"
packages:
  vscodium:
    # enabled: "{{ .features.vscodium }}"
    nameOverwrite:
      arch: vscodium-bin
      fedora: com.vscodium.codium
      windows: VSCodium.VSCodium
    type: '{{ eq .osIDLike "darwin" | ternary "cask" (eq .osIDLike "fedora" | ternary "flatpak" nil) }}'
  # vscodium@insiders:
  #   type: cask
