---
enabled: "{{ .features.vscodium }}"
packages:
  vscodium:
    # enabled: "{{ .features.vscodium }}"
    type: '{{ eq .osIDLike "arch" | ternary "aur" (eq .osIDLike "darwin" | ternary "cask" nil) }}'
    nameOverwrite:
      arch: vscodium-bin
      fedora: com.vscodium.codium
      windows: VSCodium.VSCodium
  # vscodium@insiders:
  #   type: cask
