---
# - name: "Find"
#   find:
#     paths: "{{ dot_root }}{{ '/' + item.value.src if item.value.src | default(false) else '/' + dot_roles_dir + '/' + item.key + '/' + dot_files_dir if dot_files_dir and dot_roles_dir else item.key }}"
#     patterns: "*"
#     use_regex: false
#     # file_type: file/directory
#     hidden: true

# http://docs.ansible.com/ansible/playbooks_loops.html#id24
# - name: "Construct {{ dot_files_dir | default('directory') }} dict"
#   vars:
#     _dot_root: "{{ dot_root if dot_files_dir != 'templates' else dot_local_dir }}"
#   set_fact:
#     dot_item: "{{ item }}"
#     # dot_files_target: >
#     #   {{{
#     #     item.key: {
#     #       'src': _dot_root + ('/' + item.value.src if item.value.src | default(false) else '/' + dot_roles_dir + '/' + item.key + '/' + dot_files_dir if dot_files_dir and dot_roles_dir else item.key),
#     #       'dest': dot_home + ('/' + item.value.dest if item.value.dest | default(false) else ''),
#     #       'pattern': item.value.pattern | default(dot_find_pattern),
#     #       'prefix': item.value.prefix | default('')
#     #     }
#     #   }}}
#   # with_dict: "{{ dot_files }}"

# # shell: "find {{ item.value.src + '/' + item.value.pattern }} {{ dot_find_options }}"
# # with_lines: "{{ dot_find }}"

# - name: "Find {{ item.key }} files"
#   find:
#     # contains:
#     file_type: file
#     hidden: yes
#     path: "{{ item.value.src }}"
#     pattern: "{{ item.value.pattern }}"
#   register: dot_found_files
#   with_dict: "{{ dot_files_target }}"

# - name: "Find {{ item.key }} directories"
#   find:
#     file_type: directory
#     path: "{{ item.value.src }}"
#     pattern: "{{ item.value.pattern }}"
#     recurse: no
#   register: dot_found_dirs
#   with_dict: "{{ dot_files_target }}"

# # - name: "Register sources"
# #   set_fact:
# #     # dot_target: "{{ item }}"
# #     dot_source:
# #       files: "{{ dot_found_files.files + dot_found_dirs.files }}"
# #       matched: "{{ dot_found_files.matched + dot_found_dirs.matched }}"
# #       examined: "{{ dot_found_files.examined + dot_found_dirs.examined }}"
# #       msg: "{{ dot_found_files.msg + dot_found_dirs.msg }}"
#   # with_together?

# # - name: Check source path
# #   assert:
# #     that:
# #       - "source != inventory_dir"

# - name: Ensure destination directory exists
#   file:
#     path: "{{ item.value.dest }}"
#     state: directory
#     follow: true
#   with_dict: "{{ dot_files_target }}"


# # - name: "Construct {{ dot_files_dir | default('directory') }} dict"
# #   set_fact:
# #     dot_target_map: >
# #       {{ dot_target_map | combine({
# #         dot_dict_key: {
# #           item.key: {
# #             '_src': dot_root + ('/' + item.value.src if item.value.src | default(false) else '/' + dot_roles_dir + '/' + item.key + '/' + dot_files_dir if dot_files_dir and dot_roles_dir else item.key),
# #             '_dest': dot_home + ('/' + item.value.dest if item.value.dest | default(false) else ''),
# #             'prefix': item.value.prefix | default(''),
# #             'pattern': item.value.pattern | default(dot_find_pattern)
# #           }
# #         }
# #       }, recursive=true) }}
# #   with_dict: "{{ dot_files }}"
