---
- name: "Initialize facts"
  set_fact:
    # Parsed dict
    dot_files_paths: {}
    # Final list
    dot_targets: []
    # Role directory (ansible role_* variables return 'target')
    # dot_role_dir: "{{ item.key }}"

- name: "Gather {{ dot_files_dir }} paths"
  set_fact:
    dot_files_paths: >
      {{ dot_files_paths | combine({
        item.key: {
          'src': (dot_root if dot_files_dir != 'templates' else dot_local_dir) + (
            '/' + item.value.src
              if item.value.src | default(false) else
            '/' + dot_roles_dir + '/' + item.key + '/' + dot_files_dir
              if dot_files_dir and dot_roles_dir else
            item.key),
          'dest': dot_home + (
            '/' + item.value.dest
              if item.value.dest | default(false) else
            ''),
          'pattern': item.value.pattern | default(dot_find_pattern),
          'prefix': item.value.prefix | default(''),
          'regex_replace': '' if dot_files_dir != 'templates' else '.j2',
        }
      }, recursive=true) }}
  with_dict: "{{ dot_files }}"

- name: "Find {{ dot_files_dir }}"
  find:
    path: "{{ dot_files_paths[item[0]].src }}"
    pattern: "{{ dot_files_paths[item[0]].pattern }}"
    file_type: "{{ item[1] }}"
    hidden: yes
    recurse: no
  with_nested:
    - "{{ dot_files_paths }}"
    - "{{ dot_files_type }}"
  register: dot_find

- name: "Check {{ dot_files_dir }} destination"
  stat:
    path: "{{ dot_files_paths[item[0].item[0]].dest + '/' + dot_files_paths[item[0].item[0]].prefix + item[1].path | basename | regex_replace(dot_files_paths[item[0].item[0]].regex_replace, '') }}"
  with_subelements:
    - "{{ dot_find.results }}"
    - files
  register: dot_stats
  no_log: "{{ dot_no_log }}"

# Final target list
- name: "Gather {{ dot_files_dir }} stats"
  set_fact:
    dot_targets: >
      {{ dot_targets + [
        {
          'src': item.item.1.path,
          'dest': dot_files_paths[item.item.0.item.0].dest + '/' + dot_files_paths[item.item.0.item.0].prefix + item.item.1.path | basename | regex_replace(dot_files_paths[item.item.0.item.0].regex_replace, ''),
          'exists': item.stat.exists,
          'link': item.stat.lnk_source | default(false),
          'type': item.item.0.item.1,
          'role_name': item.item.0.item.0,
          'role_directory': dot_files_dir,
        }
      ] }}
  with_items: "{{ dot_stats.results }}"
  no_log: "{{ dot_no_log }}"

# - debug: var=dot_targets
