---
npm_user: "{{ user_name }}"
npm_email: "{{ email }}"

npm_install: yes
npm_global: yes
npm_state: present

npm_prefix: "{{ ansible_env.HOME }}/.node_modules" # /bin?

# Node modules
npm_packages: []

# System packages
node_packages: []
