---
- name: Update Homebrew
  homebrew: update_homebrew=yes
  when: update_packages

- name: Update Homebrew packages
  homebrew: upgrade_all=yes
  when: upgrade_packages

- name: Install Homebrew packages
  homebrew: name={{ item }} state=latest
  with_items: "{{ homebrew_packages }}"

# TODO: casks
