---
functions/extract.nu:
  type: file
  url: https://raw.githubusercontent.com/nushell/nu_scripts/refs/heads/main/modules/data_extraction/ultimate_extractor.nu
  refreshPeriod: 168h

# ~/nu_scripts/themes/nu-themes
themes/tokyo-storm.nu:
  type: file
  url: https://raw.githubusercontent.com/nushell/nu_scripts/refs/heads/main/themes/nu-themes/tokyo-storm.nu
  refreshPeriod: 168h
