#!/bin/sh
#
# Install native apps
# Usage: `brew bundle Caskfile`
# https://github.com/mathiasbynens/dotfiles/blob/master/Caskfile

# Homebrew Cask
install caskroom/cask/brew-cask
tap caskroom/versions

###############################################################################
# Browsers                                                                    #
###############################################################################

cask install google-chrome
#cask install google-chrome-canary
cask install firefox
#cask install firefox-aurora
cask install opera
#cask install opera-developer
#cask install opera-next
cask install torbrowser

###############################################################################
# Editors                                                                     #
###############################################################################

#cask install atom
cask install sublime-text3
cask install phpstorm
cask install mou

###############################################################################
# Development                                                                 #
###############################################################################

#cask install tower
#cask install sourcetree
#cask install gitx-l

cask install vagrant
#cask install vagrant-manager
cask install virtualbox
#cask install vmware-fusion

#cask install filezilla
cask install transmit

cask install sequel-pro
cask install robomongo

cask install kaleidoscope
cask install reggy

###############################################################################
# Utilities                                                                   #
###############################################################################

cask install alfred
#cask install atext
cask install bartender
cask install caffeine
cask install flux
cask install imagealpha
cask install imageoptim
#cask install miro-video-converter
cask install onyx
cask install the-unarchiver
cask install vlc

# Only to remap Caps Lock
cask install karabiner
cask install seil

###############################################################################
# Programs                                                                    #
###############################################################################

cask install cakebrew
cask install dropbox
cask install evernote
#cask install lastpass-universal
cask install little-snitch
cask install skype
cask install transmission

###############################################################################
# Quicklook plugins                                                           #
###############################################################################

cask install qlcolorcode
cask install qlstephen
cask install qlmarkdown
cask install qlprettypatch
cask install quicklook-json
cask install quicklook-csv
cask install betterzipql
cask install webp-quicklook

###############################################################################
# Fonts                                                                       #
###############################################################################

#tap caskroom/fonts
#cask install font-inconsolata

###############################################################################
# Others                                                                      #
###############################################################################

# Link apps to Alfred
cask alfred link

# Cleanup
cask cleanup
