---

# - include: "{{ lib }}/{{ action|default('sym') }}links.yml"

# - name: Symlink Hamerspoon configuration
#   file:
#     src: "{{ dot_root }}/{{ item.key }}"
#     dest: "{{ dot_home }}/{{ item.value }}"
#     state: link
#   with_dict:
#     hammerspoon: .hammerspoon
