---
extraPackages:
  ripgrep:
    nameOverwrite:
      windows: BurntSushi.ripgrep.MSVC
    # type: mise
  ripgrep-all:
    enabled: '{{ eq .osIDLike "arch" "darwin" }}'
    # nameOverwrite:
    #   darwin: rga
    type: '{{ eq .osIDLike "windows" | ternary "scoop" nil }}'
