---
extraPackages:
  ripgrep:
    nameOverwrite:
      windows: burntsushi.ripgrep.msvc
  ripgrep-all:
    condition: eq .osIDLike "arch" "darwin"
    # nameOverwrite:
    #   darwin: rga
    type: eq .osIDLike "windows" | ternary "scoop" nil
