---
extraPackages:
  ripgrep:
    enabled: '{{ (get .features "ripgrep") }}'
    nameOverwrite:
      windows: BurntSushi.ripgrep.MSVC
    # type: mise
  ripgrep-all:
    enabled: '{{ and (get .features "ripgrep") (eq .osIDLike "arch" "darwin") }}'
    # nameOverwrite:
    #   darwin: rga
    type: '{{ eq .osIDLike "windows" | ternary "scoop" nil }}'
