---
packages:
  yq:
    nameOverwrite:
      alpine: yq-go # "extra/yq" installs "kislyuk/yq" instead of "mikefarah/yq"
      pacman: go-yq
      windows: MikeFarah.yq
    # or (and (eq .osID "debian") (le (int .osVersion) 11))
    #   (and (eq .osID "ubuntu") (le (float64 .osVersion) 22.04))
    #   | ternary "mise" (eq .osIDLike "fedora" | ternary "brew" nil)
    type: '{{ eq .osIDLike "debian" "fedora" | ternary "brew" nil }}'
