---
bash_urls:
  spark:
    url: "https://raw.githubusercontent.com/holman/spark/master/spark"
    dest: bin
  git_prompt:
    url: "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh"
