#!/bin/bash
#
# Set of printing functions

print () {

	# Don't print if mute is set
	[ -n "$mute" ] && return

	local icon_color=$1 icon=$2 label=$3 message=$4
	local text_color=$white column="%-42s"

	# Change style if label only
	[ "$message" = "" ] && text_color=""

	# \r\033[2K
	printf "   ${icon_color}$icon  ${column}  $message\n" "${text_color}$label${reset}"
}

user () {
	print $yellow ? "$1" "$2"
}

info () {
	print $white → "$1" "$2"
}

success () {
	print $green ✓ "$1" "$2"
}

fail () {
	print $red × "$1" "$2"
}

die () {
	print $red × "$1" "$2"
	exit
}

skipped () {
	success "Skipped"
}
