---
extraPackages:
  tmux:
  nowplaying-cli:
    enabled: '{{ and (get .features "tmux") (eq .osID "darwin") }}'
  pam-reattach:
    enabled: '{{ and (get .features "tmux") (eq .osID "darwin") }}'
  playerctl:
    enabled: '{{ and (get .features "tmux") (eq .os "linux") }}'
  reattach-to-user-namespace:
    enabled: '{{ and (get .features "tmux") (eq .osID "darwin") }}'
