#!/bin/bash
#
# Setup some defaults

Utils=$DOTFILES/script/utils
source $Utils/print.sh

UNAME=$( uname )

# exec $DOTFILES/init/st3install

case $UNAME in

	Darwin) # Mac OS X

		# TERMINAL

		# Custom version of the Solarized Dark theme
		TERM_PROFILE='LEI'
		CURRENT_PROFILE="$(defaults read com.apple.terminal 'Default Window Settings')"


		if [ "${CURRENT_PROFILE}" != "${TERM_PROFILE}" ]
		then
			if . $Utils/ask "Terminal ? (current: $CURRENT_PROFILE)" Y true
			then
				open "$DOTFILES/init/$TERM_PROFILE.terminal"
				sleep 1 # Wait a bit to make sure the theme is loaded
				defaults write com.apple.terminal 'Default Window Settings' -string "${TERM_PROFILE}"
				defaults write com.apple.terminal 'Startup Window Settings' -string "${TERM_PROFILE}"

				success "Default now set to $TERM_PROFILE.terminal" "Window settings"
			fi
		else
			info "Already set to $TERM_PROFILE.terminal" "Window settings" true
		fi

		# SUBLIME TEXT

		if . $Utils/ask "Sublime Text ?" Y true
		then

			st_prefix=~/Library/Application\ Support/Sublime\ Text
			st_suffix=/Packages/User/Preferences.sublime-settings

			for f in "$st_prefix"*"$st_suffix"
			do
				rm -r "$f" # -f ?
				ln -s "$DOTFILES/init/Preferences.sublime-settings" "$f"
				st_version=${f#$st_prefix}
				success "Symlinked Preferences.sublime-settings" "Sublime Text ${st_version:1:1}"
			done
		fi

		# SYSTEM

		if . $Utils/ask "Set OS defaults ?" N true
		then
			. $Utils/ask "SSD ?" N true && SSD=true
			source $DOTFILES/setup/.osx
		fi

		;;

	Linux) # Linux

		;;

esac

info "Require a logout/restart to take effect"
