#!/usr/bin/env bash

# bootstrap.sh

# set -o xtrace
set -o nounset
set -o errexit
set -o pipefail

# Extend matching operators
shopt -s extglob
# Loop on dotfiles
shopt -s dotglob
# Do not loop on empty directory
shopt -s nullglob
# Recursive globbing
shopt -s globstar

# .dotrc
declare -A CONFIG
# Register loaded files
declare -A IMPORTED

main() {
	unset -f main

	# Paths
	cd $(dirname "${BASH_SOURCE[0]}")/..
	DOT_ROOT=$(pwd -P)
	DOT_TARGET=$HOME
	DOT_FILES="$DOT_ROOT/files"
	DOT_BOOTSTRAP="$DOT_ROOT/bootstrap"
	DOT_RC="$DOT_ROOT/.dotrc"

	# Bootstrap configuration
	UNAME=$(uname -s) # Darwin|Linux
	TIMESTAMPS=false
	DRY_RUN=${DRY_RUN-false}
	DEBUG=${DEBUG-false}
	# MIN_DEPTH=1
	# MAX_DEPTH=1

	# Load library
	import "lib/log"
	import "lib/file"

	# Parse settings
	read_conf "$DOT_RC"
	log_debug "Debug mode enabled" "$UNAME"
	# log_info "Configuration loaded" "${CONFIG[@]}"

	# Templates
	for template in $DOT_FILES/**/template.*; do
		process_template_file "$template"
	done

	# Symlinks

	# [submodule "files/.vim/bundle/pathogen"]
	# url = https://github.com/tpope/vim-pathogen.git
	# [submodule "files/.vim/bundle/sensible"]
	# url = https://github.com/tpope/vim-sensible.git
	# [submodule "files/.vim/bundle/fugitive"]
	# url = https://github.com/tpope/vim-fugitive.git
	# [submodule "files/.vim/bundle/syntastic"]
	# url = https://github.com/scrooloose/syntastic
	# [submodule "files/.vim/bundle/base16"]
	# url = https://github.com/chriskempson/base16-vim.git
	# [submodule "files/.vim/bundle/nerdtree"]
	# url = https://github.com/scrooloose/nerdtree.git
	# [submodule "files/.vim/bundle/gitgutter"]
	# url = https://github.com/airblade/vim-gitgutter.git
	# [submodule "files/.vim/bundle/command-t"]
	# url = https://github.com/wincent/command-t.git
	# [submodule "files/.vim/bundle/ctrlp"]
	# url = https://github.com/ctrlpvim/ctrlp.vim.git
	# [submodule "files/.vim/bundle/airline"]
	# url = https://github.com/bling/vim-airline.git
#tpope/vim-vinegar
	log "STATUS" "$?"
}

import() {
	local path="$1"
	local name="${path##*/}"
	local ext="sh"

	[[ ${IMPORTED[$name]-} = true ]] && return 0
	source "$DOT_BOOTSTRAP/$path.$ext"
	IMPORTED[$name]=true

	return $?
}

[[ "$0" == "$BASH_SOURCE" ]] && main "$@"
