---
dependencies:

  - role: package
    packages: "{{ irc_packages }}"

  - role: dotfiles
    paths:
      - name: irc
        dest: irc
        pattern: "*.j2"
        template: yes
      - name: irc/files/bin
        dest: irc/bin
