---
- name: "Ensure packages are {{ packages_state }}"
  package:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default(packages_state) }}"
    install_options: "{{ item.install_options | default(omit) }}"
  with_items: "{{ packages }}"
  become: "{{ 'yes' if ansible_os_family != 'Darwin' else 'no' }}"
  when: packages_install

# - name: "Check packages state : {{ packages_state }}"
#   homebrew:
#     name: "{{ item.name | default(item) }}"
#     state: "{{ item.state | default(packages_state) }}"
#     install_options: "{{ item.install_options | default(false) }}"
#   with_items: "{{ packages }}"
#   when: "packages_install and ansible_distribution == 'Darwin'"
