---
- name: "Check {{ packages | length }} packages state : {{ packages_state }}"
  package:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default(packages_state) }}"
    # Homebrew module options
    # role_brew_install_options
    install_options: "{{
      item.install_options | join(',') if ansible_os_family == 'Darwin' and
      item.install_options is defined and
      item.install_options | length > 0 else omit
    }}"
  with_items: "{{ packages }}"
  become: "{{ 'yes' if ansible_os_family != 'Darwin' else 'no' }}"
  when: packages_install
