---
- name: "{{ packages | length }} packages : {{ packages_state }}"
  package:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default(packages_state) }}"
    # Homebrew module options
    # role_brew_install_options
    install_options: "{{
      item.install_options | join(',') if ansible_os_family == 'Darwin' and
      item.install_options is defined and
      item.install_options | length > 0 else omit
    }}"
    # https://github.com/transcode-open/apt-cyg
    # https://github.com/naokirin/ansible-apt-cyg-module
    use: "{{ 'auto' if os != 'Windows' else 'apt_cyg' }}"
  with_items: "{{ packages }}"
  # ansible_os_family
  become: "{{ 'yes' if os in ['Archlinux', 'Debian'] else 'no' }}"
  when: packages_install
