#!/bin/bash
#
# Bootstrap dotfiles
# Mainly inspired from mathiasbynens/dotfiles

# Set working directory
cd "$(dirname "$0")"

DOTFILES_DIR=$(pwd)
TARGET_DIR=$HOME
indent_level=1
indent_size=3

export DOTFILES=$DOTFILES_DIR
export lib=$DOTFILES_DIR/lib
source $lib/print # Get colors asap

# Get command
args=("$@")

set -e


do_setup () {
	# TODO Configuration file
	# if [ -e "$DOTFILES_DIR/config" ]
	# then
	# 	source $DOTFILES_DIR/config
	# else
	# 	echo "$cfg file needed. See config.sample for directions and copy it to config."
	# 	exit 1
	# fi

	echo 'bootfiles dotstrap'

	#git pull origin master

	# Import functions
	source $lib/ask
	source $lib/dir
	source $lib/link
	source $lib/git
	source $lib/brew
}

do_gitconfig () {
	# Create git/.gitconfig if needed
	local gitconfig_file="git/gitconfig."
	if check_file "$gitconfig_file" Y; then
		if ask "Configure git credentials ?" Y; then
			gitconfig
		else
			skipped
		fi
	else
		warn "Git configuration already file exists" "$gitconfg_file"
	fi
}

do_link () {
	# Ignore lists
	local global_ignore=(".DS_Store" ".gitignore" "README.md" ".git" "gitconfig.sample")
	local vim_ignore=(${global_ignore[@]} "vimrc." "gvimrc.")

	if ask "Create symbolic links ?" Y true; then
		[ "$debug" = true ] && \
			info "Symbolic dry run" "Changes are not applied while debugging" true
		echo ''
		dir "" link_dotfile ${global_ignore[@]} || skipped
		dir "bin" link_file || skipped
		dir ".vim" link_file ${vim_ignore[@]} || skipped
		echo ''
		success "Stuff linked."
	else
		skipped "symlinks"
	fi
}

do_defaults () {
	if ask "Set defaults ?" Y true; then
		local defaults=$DOTFILES_DIR/lib/defaults
		source_file $defaults || \
			warn "Configuration didn't fully complete" "lib/defaults"
		# success "Defaults loaded" "lib/defaults"
		indent_level=1
		success "OS configuration done."
	else
		skipped "defaults"
	fi
}

copy () {
	local src=$1
	echo $src
	if [ -f "$src" -o -d "$src" ] && \
		. $lib/copy $src $TARGET_DIR/$src; then
		success "$src" "Copied to ~/$src"
	else
		fail "$src failed to be copied"
	fi
}

remove () {
	local src=$1
	echo $src
	# 2> /dev/null
	if [ -f "$src" -o -d "$src" -o -L "$src" ] && \
		rm -r $TARGET_DIR/$src; then
		success "Removed" "$src"
	else
		fail "$src can't be removed"
	fi
}

# Print command line usage
echo_usage () {
	$lib/usage
	exit 0
}

check_file () {
	local file=$1

	if [ -f $file ]; then
		return 1
	else
		return 0
	fi
}

source_file () {
	local file=$1

	if [ -f $file ] && source "$file"; then
		#success "Operation successfull !"
		return 1
	else
		#fail "Command failed !"
		return 0
	fi
}

sandbox () {
	TARGET_DIR=$TARGET_DIR/sandbox
	info "$TARGET_DIR" "Using sandbox folder"

	if [ ! -d $TARGET_DIR ]; then
		mkdir $TARGET_DIR
	fi
}

uninstall () {
	# Does not undo bundles & defaults

	# Remove bin/* and */*.symlink
	# ask "Remove symbolic links ?" Y && \
	# 	info "Unlinking bin files" "..." && \
	# 	dir "/bin" "" unlink && \
	# 	info "Unlinking dotfiles" "..." && \
	# 	dir "/" "*.symlink" unsymlink && \
	# 	success 'Symlinks unchained.' || \
	# 	skip

	# Remove .vim
	# TODO Symlink
	# ask "Remove .vim directory ?" Y && \
	# 	remove ".vim" || \
	# 	skip

	echo ''
	echo 'Bootstrap uninstalled things.'
}

install () {
	echo ''

	# Git
	#####

	do_gitconfig

	echo ''
	indent_level=1

	# Symbolic links
	################

	do_link

	echo ''
	indent_level=1

	# Set OS defaults
	#################

	do_defaults
}

# Parse arguments and unset recognized ones
parse_flags () {
	local args=("$@")

	for (( i = ${#args[@]} - 1; i >= 0; i-- )); do
		case ${args[i]} in
			-d|--default)
				force_default=true
				unset args[i] ;;
			-f|--force)
				force=true
				unset args[i] ;;
			-m|--mute)
				mute=true
				unset args[i] ;;
			-s|--sandbox)
				sandbox
				unset args[i] ;;
			-t|--test)
				debug=true
				unset args[i] ;;
			-h|--help)
				echo_usage
				unset args[i] ;;
			-*) echo "Unrecognized option: ${args[i]}"
				echo_usage
				unset args[i] ;;
		esac
	done

	# Print echo_usage if > 1 argument left
	[ ${#args[@]} -gt 1 ] && echo_usage

	echo ${args[@]}
}

# Execute command
bootstrap () {
	cmd=$(parse_flags $@)

	case $cmd in
		'')          install ;;
		'install')   install ;;
		'uninstall') uninstall ;;
		'bundle')    source $DOTFILES/lib/setup ;;
		'defaults')  source $DOTFILES/lib/defaults ;;
		*)           echo_usage ;;
	esac
}

do_setup
bootstrap ${args[@]}

echo ''
indent_level=0

success "Things were bootstrapped !" " "

# source ~/.bash_profile || \
# 	fail "~/.bash_profile"
