#!/bin/bash
#
# Setup some defaults
# Steps specific to init folder & depending on OS type

# Import prompt functions
lib=$DOTFILES/lib
source $lib/print
source $lib/ask

UNAME=$( uname )

info "'dot defaults' is an alias to this step" " " true

if [ -n "$indent_level" ]; then
	original_level=$indent_level
else
	indent_level=2
fi

case $UNAME in

	Darwin)

		# TERMINAL

		# Search for the terminal configuration
		TERM_FILE=`find $DOTFILES -name *.terminal`
		base_name=$(basename $TERM_FILE)
		TERM_PROFILE=${base_name%%.*}
		# Custom version of the Solarized Dark theme
		[ -n "$TERM_PROFILE" ] || TERM_PROFILE='LEI'

		CURRENT_PROFILE="$(defaults read com.apple.terminal 'Default Window Settings')"


		if [ "${CURRENT_PROFILE}" != "${TERM_PROFILE}" ]; then
			if ask "Change Terminal profile ? Currently $CURRENT_PROFILE)" Y; then
				((indent_level++))
				open "$TERM_FILE"
				sleep 1 # Wait a bit to make sure the theme is loaded
				defaults write com.apple.terminal 'Default Window Settings' -string "${TERM_PROFILE}"
				defaults write com.apple.terminal 'Startup Window Settings' -string "${TERM_PROFILE}"

				success "Terminal window" "Profile now uses $TERM_PROFILE.terminal"
			fi
		else
			success "Terminal window" "Current profile already uses $TERM_PROFILE.terminal" true
			((indent_level++))
		fi

		((indent_level--))

		# SYSTEM

		if ask "Set OS defaults ?" N; then

			((indent_level++))

			if [ "$(whoami)" != "root" ]; then
				warn "Administrator access is required" " " && sudo -v
			fi

			ask "SSD specific commands ?" N && SSD=true
			info "Executing init/.osx" "..." true
			if source $DOTFILES/init/.osx; then
				info "Some changes may require a logout/restart to take effect" " " true

				# Kill affected applications

				if ask "Kill affected applications (except Terminal) ?" N; then
					for app in "Activity Monitor" "Address Book" "Calendar" "Contacts" "cfprefsd" \
						"Dock" "Finder" "Mail" "Messages" "Safari" "SizeUp" "SystemUIServer" \
						"Transmission" "Twitter" "iCal"; do # "Terminal"
						killall "${app}" > /dev/null 2>&1
					done
				fi
			else
				fail "$DOTFILES/init/.osx"
				step_failed=true
			fi
		else
			((indent_level++))
		fi

		((indent_level--))

		# SUBLIME TEXT

		if ask "Link Sublime Text preferences ?" Y; then

			st_prefix=~/Library/Application\ Support/Sublime\ Text
			st_suffix=/Packages/User/Preferences.sublime-settings

			for f in "$st_prefix"*"$st_suffix"; do

				rm "$f" # -f ?
				ln -s "$DOTFILES/init/Preferences.sublime-settings" "$f"

				st_success=true
				st_version=${f#$st_prefix}
				success "Sublime Text ${st_version:1:1}" "Symlinked Preferences.sublime-settings"
			done

			if [ ! -n "$st_success" ]; then
				fail "No application found" "$st_prefix*$st_suffix"
				step_failed=true
			fi
		fi

		;;

	*)

		echo "No configuration for $UNAME"

		;;

esac

echo ''
indent_level=$original_level

[ "$step_failed" = true ] && return 0
