[local]
localhost

[work]
; localhost

[local:vars]
ansible_connection = local

[remote]
; raspberry ansible_host=192.168.1.20 ansible_user=LEI
; vagrant ansible_host=192.168.20.20 ansible_user=vagrant ansible_port=2222

[all:vars]
dot_repo = git://github.com/LEI/dotfiles.git
; dot_repo_dir = .dotfiles
; dot_repo_version = master

email = guillaume.frichet@gmail.com
full_name = Guillaume Frichet
user_name = LEI

timezone = Europe/Paris

[work:vars]
email = guillaume.frichet@f.fr
user_name = Guillaume
