---
- name: Setup local host
  hosts: local
  gather_facts: yes

  pre_tasks:
    - name: Update dotfiles repository
      tags: ['repo']
      git:
        repo: "{{ dot_repo }}"
        dest: "{{ dot_root }}"
        version: "{{ dot_version | default('HEAD') }}"
        # Discard any modified files in the working repository
        force: no
        # Retrieve new revisions from the origin repository
        update: no
      # ignore_errors: yes

  tasks:
    - name: "Group hosts by OS distribution"
      group_by: key=os_{{ ansible_distribution|lower }}
      tags: [always]

- include: "playbooks/debian.yml"
  when: ansible_distribution == 'Debian'

- include: "playbooks/macosx.yml"
  when: ansible_distribution == 'MacOSX'

- include: "playbooks/common.yml"
