---
- hosts: all
  tasks:
    - name: "Group hosts by OS distribution"
      group_by: key=os_{{ ansible_distribution|lower }}
      tags: ['always']

- name: "Debian"
  hosts: os_debian
  tags: ['deb']
  roles:
    - {role: apt-get}
    - {role: apt, tags: ['apt','pkg'], packages: "{{ apt_packages }}"}
    - {role: debops.nodejs, tags: ['npm', 'node']}

- name: "MacOSX"
  hosts: os_macosx
  tags: ['osx']
  roles:
    - {role: homebrew}
    - {role: brew, tags: ['brew','pkg'], packages: "{{ brew_packages }}"}
    - {role: cask, tags: ['brew','cask'], packages: "{{ brew_casks }}"}
    - {role: brew, tags: ['npm', 'node'], packages: ['node']}
    - {role: hammerspoon, tags: ['ws','hs']}
    # - {role: osx, tags:['defaults']}

- name: "setup : Development environment"
  hosts: local
  # # FIXME: disable duplicates roles (apt-get, homebrew)
  # vars:
  #   packages_update: no
  #   packages_upgrade: no
  # pre_tasks:
  #   - name: Update repository
  #     git:
  #       repo: git://github.com/LEI/dotfiles.git
  #       dest: "{{ dot_root }}"
  #       version: ansible
  #       update: no
  #     ignore_errors: yes
  tags: ['common', 'home']
  roles:
    - {role: git, tags: ['git']}
    - {role: npm, tags: ['node','npm']}
    - {role: tmux, tags: ['tmux']}
    - {role: vim, tags: ['vim']}
    - {role: bash, tags: ['bash']}
    - {role: bin, tags: ['bin']}
    # - {role: files, tags: ['cfg']}

