---
- name: Group by distribution
  hosts: local
  tasks:
    - name: "os : {{ ansible_distribution }}"
      group_by: key=os_{{ ansible_distribution|lower }}
      tags:
        - always

- name: Debian packages
  hosts: os_debian
  tags: ['deb']
  roles:
    - {role: apt, tags: ['apt','pkg'], packages: "{{ apt_packages }}"}

- name: MacOSX packages
  hosts: os_macosx
  tags: ['osx']
  roles:
    - {role: brew, tags: ['brew','pkg'], packages: "{{ brew_packages }}"}
    # - {role: cask, tags: ['brew','cask'], packages: "{{ cask_apps }}"}
    - {role: hammerspoon, tags: ['ws','hs']}
    # - {role: osx, tags:['defaults']}

- name: Setup local environment
  hosts: local
  # FIXME: disable duplicates roles (apt-get, homebrew)
  vars:
    packages_update: no
    packages_upgrad: no
  # pre_tasks:
  #   - name: Update repository
  #     git:
  #       repo: git://github.com/LEI/dotfiles.git
  #       dest: "{{ dot_root }}"
  #       version: ansible
  #       update: no
  #     ignore_errors: yes
  tags: ['common', 'home']
  roles:
    - {role: git, tags: ['git']}
    - {role: npm, tags: ['node','npm']}
    - {role: tmux, tags: ['tmux']}
    - {role: vim, tags: ['vim']}
    - {role: bash, tags: ['bash']}
    - {role: bin, tags: ['bin']}
    # - {role: files, tags: ['cfg']}

