---
- name: Setup hosts
  hosts: all
  gather_facts: yes

  # pre_tasks:
  #   - name: Ensure git is installed
  #     package:
  #       name: "{{ 'git-core' if ansible_distribution == 'Debian' else 'git' }}"
  #     become: "{{ 'yes' if ansible_distribution in ['Archlinux', 'Debian'] else 'no' }}"
  #   - name: Clone dotfiles repository
  #     tags: ['repo']
  #     git:
  #       repo: "{{ dot_repo }}"
  #       dest: "{{ dot_root }}"
  #       version: "{{ dot_repo_version | default(omit) }}"
  #       # Discard any modified files in the working repository
  #       force: no
  #       # Retrieve new revisions from the origin repository
  #       update: yes
  #       # key_file:
  #     # ignore_errors: yes
  #     when:  dot_repo is defined

  tasks:

    - name: "Group hosts by OS"
      # MacOSX -> os_macosx
      # CYGWIN_NT-6.1 -> os_cygwin
      group_by: key=os_{{ ansible_distribution | lower | regex_replace('^([a-zA-Z]+)[\s|-|_](.*)$', '\\1') }}
      tags: [always]

    - name: Group names
      debug:
        msg:
          groups: "{{ group_names | to_nice_json }}"
          os: "{{ os }}"
      when: log_enable is defined and log_enable

    - name: "OS {{ ansible_os_family }}" # ansible_model
      vars:
        dist: "{{ ansible_distribution }} {{ ansible_distribution_release | default(ansible_distribution_version) }}"
      debug: # inventory_hostname
        var: dist # os, os_relase

    # - name: "Include OS vars"
    #   include_vars: "{{ item }}"
    #   with_first_found:
    #     - "vars/{{ ansible_distribution | lower }}.yml"
    #     - "vars/{{ ansible_os_family | lower }}.yml"
    #     - "vars/os_defaults.yml"

- include: "playbooks/os_archlinux.yml" # Archlinux
- include: "playbooks/os_centos.yml" # RedHat
- include: "playbooks/os_cygwin.yml" # Windows
- include: "playbooks/os_debian.yml" # Debian
- include: "playbooks/os_macosx.yml" # MacOSX

- include: "playbooks/all.yml"

- include: "playbooks/local.yml"

- include: "playbooks/remote.yml"
  # when: "'remote' in group_names"
