---
- name: Setup hosts
  hosts: all
  gather_facts: yes

  # pre_tasks:

  #   - name: Update dotfiles repository
  #     tags: ['repo']
  #     git:
  #       repo: "{{ dot_repo }}"
  #       dest: "{{ dot_root }}"
  #       version: "{{ dot_repo_version | default(omit) }}"
  #       # Discard any modified files in the working repository
  #       force: no
  #       # Retrieve new revisions from the origin repository
  #       update: yes
  #       # key_file:
  #     # ignore_errors: yes
  #     when:  dot_repo is defined

  tasks:

    - name: "Distribution {{ ansible_os_family }}" # ansible_model
      vars:
        os: "{{ ansible_distribution }} {{ ansible_distribution_release | default(ansible_distribution_version) }}"
      debug: # inventory_hostname
        var: os
      tags: [distro]

    - name: "Group hosts by OS distribution"
      group_by: key=os_{{ ansible_distribution | lower }}
      tags: [always]

    - name: Group names
      debug:
        msg: "{{ group_names | to_nice_json }}"
      when: log_enable is defined and log_enable

    # - name: "Include OS vars"
    #   include_vars: "{{ item }}"
    #   with_first_found:
    #     - "vars/{{ ansible_distribution | lower }}.yml"
    #     - "vars/{{ ansible_os_family | lower }}.yml"
    #     - "vars/os_defaults.yml"

- include: "playbooks/os_archlinux.yml"
  # when: ansible_distribution == 'Archlinux'

- include: "playbooks/os_debian.yml"
  # when: ansible_distribution == 'Debian'

- include: "playbooks/os_macosx.yml"
  # when: ansible_distribution == 'MacOSX'

- include: "playbooks/all.yml"

- include: "playbooks/local.yml"

- include: "playbooks/remote.yml"
  # when: "'remote' in group_names"
