#!/bin/bash
#
# Setup some defaults

# Import prompt functions
lib=$DOTFILES/lib
source $lib/print
source $lib/ask
source $lib/brew

UNAME=$( uname )

info "'dot setup' is an alias to execute Brew and Cask files" " " true

if [ -n "$indent_level" ]; then
	original_level=$indent_level
else
	indent_level=2
fi

case $UNAME in

	Darwin)

		# HOMEBREW

		if install_homebrew; then

			# BREW LIBS

			# Install dependencies
			if ask "Bundle brew ?" Y; then
				((indent_level++))
				if ! brew_bundle "Brew"; then
					setp_failed=true
				fi
			else
				skipped "Brew"
				((indent_level++))
			fi

			((indent_level--))

			# CASK APPS

			# Install programs
			if ask "Bundle cask ?" Y; then
				((indent_level++))
				if ! brew_bundle "Cask"; then
					setp_failed=true
				fi
			else
				skipped "Cask"
				((indent_level++))
			fi

			((indent_level--))

		else
			skipped "Homebrew"
		fi

		;;

	Linux)

		# apt-get stuff ?
		# https://github.com/Homebrew/linuxbrew ?

		;;

esac

echo ''
indent_level=$original_level

[ "$setp_failed" = true ] && return 0
