#!/bin/bash
#
# Setup some defaults

# Import prompt functions
lib=$DOTFILES_DIR/lib
source $lib/print
source $lib/ask
source $lib/brew

UNAME=$( uname )

info "'dot setup' is an alias to this step" " " true

if [ -n "$indent_level" ]; then
	original_level=$indent_level
else
	indent_level=2
fi

config_keys () {
	local file
	local spaces="            "
	((indent_level++))
	if ask "Custom keyboard settings ?"; then
		if silent brew cask install seil; then
			# Seil
			((indent_level++))
			local file=$DOTFILES_DIR/init/seil
			if silent source_file $file; then
				success "Seil" " "
				open /Applications/Seil.app
				((indent_level--))
			else
				fail "Seil" " "
				((indent_level--))
			fi
		fi
		if silent brew cask install karabiner; then
			# Karabiner
			((indent_level++))
			local file=$DOTFILES_DIR/init/karabiner
			if silent source_file $file; then
				success "Karabiner" " "
				open /Applications/Karabiner.app
				((indent_level--))
			else
				fail "Karabiner failed" " "
				((indent_level--))
			fi
		fi
		success "Keyboard"
	else
		skipped "keyboard"
	fi
	((indent_level--))
}

case $UNAME in

	Darwin)

		# HOMEBREW

		if install_homebrew; then

			# BREW LIBS

			# Install dependencies
			if ask "Bundle brew ?"; then
				brew_bundle "Brew" || step_failed=true
			else
				skipped "Brew"
			fi

			# CASK APPS

			# Install programs
			if ask "Bundle cask ?"; then
				if brew_bundle "Cask"; then
					config_keys || step_failed=true
				else
					step_failed=true
				fi
			else
				skipped "Cask"
			fi

		else
			skipped "Homebrew"
		fi

		;;

		# apt-get stuff ?
		# https://github.com/Homebrew/linuxbrew ?
	*)

		warn "No setup available" "$UNAME"

		;;

esac

# echo ''
indent_level=$original_level

[ "$step_failed" = true ] && return 1

#return 0
