#!/bin/bash
#
# Setup some defaults

# Import functions
lib=$DOTFILES_DIR/lib
CONFIG_FILE=$DOTFILES_DIR/config
source $lib/readconf
source $lib/print
source $lib/ask

source $DOTFILES_DIR/brew/brew.sh

UNAME=$( uname )

info "'dot setup' is an alias to this step" " " true

if [ -n "$indent_level" ]; then
	original_level=$indent_level
else
	indent_level=2
fi

case $UNAME in

	Darwin)

		# HOMEBREW

		if install_homebrew; then
			((indent_level++))

			# BREW LIBS

			# Install dependencies
			if ask "Bundle brew ?"; then
				brew_bundle "brew" || step_failed=true
			else
				skipped "Brew" " "
			fi

			# CASK APPS

			# Install programs
			if ask "Bundle cask ?"; then
				if brew_bundle "cask"; then
					for cask in ${cask_files[@]}; do
						do_cask "$cask"
					done
				else
					step_failed=true
				fi
			else
				skipped "Cask" " "
			fi

		else
			((indent_level++))
			skipped "Homebrew" " "
		fi

		((indent_level--))

		success "Homebrew" " "

		;;

		# apt-get stuff ?
		# https://github.com/Homebrew/linuxbrew ?
	*)

		warn "No setup available" "$UNAME"

		;;

esac

# echo ''
indent_level=$original_level

[ "$step_failed" = true ] && return 1

#return 0
