---
dependencies:
  - role: apt
    packages:
      - vim
    when: "ansible_os_family == 'Debian'"
  - role: brew
    packages:
      - name: vim
        install_options: with-override-system-vi, with-pyhton3
    when: "ansible_os_family == 'Darwin'"
  - role: symlinks
    role_dir: vim
