---
dependencies:

  - role: package
    packages: "{{ vim_packages }}"

  # - role: pacman-yaourt
  #   pacman_yaourt_packages:
  #     - vim-youcompleteme-git
  #   when: "ansible_os_family == 'Archlinux'"

  - role: dotfiles
    paths:
      - name: vim
        dest: .vim
        pattern: "*.j2"
        template: yes
      - name: vim
        dest: .vim
