---
enabled: "{{ .features.vscode }}"
packages:
  visual-studio-code: # vscli
    # nameOverwrite:
    #   arch: visual-studio-code-bin
    # type: '{{ eq .osIDLike "arch" | ternary "aur" (eq .osIDLike "darwin" | ternary "cask" nil) }}'
    nameOverwrite:
      arch: code
      fedora: com.visualstudio.code
    type: '{{ eq .osIDLike "darwin" | ternary "cask" (eq .osIDLike "fedora" | ternary "flatpak" nil) }}'
