---
packages:
  visual-studio-code: # vscli
    enabled: "{{ and .features.vscode (not .headless) }}"
    # nameOverwrite:
    #   arch: visual-studio-code-bin
    # type: '{{ eq .osIDLike "arch" | ternary "aur" (eq .osIDLike "darwin" | ternary "cask" nil) }}'
    nameOverwrite:
      arch: code
    type: '{{ eq .osIDLike "darwin" | ternary "cask" nil }}'
