{{- $taps := dict }}
{{- range $name, $pkg := .packages.brew }}
{{-   if contains "/" $name }}
{{-     $_ := $taps | setValueAtPath ($name | replaceAllRegex "/[\\w@-]+$" "") dict }}
{{-   end }}
{{- end }}

{{- $brewfile := joinPath (env "XDG_CONFIG_HOME" | default (joinPath  .chezmoi.homeDir ".config")) "homebrew/Brewfile" -}}
{{- $lines := list }}
{{- if stat $brewfile -}}
{{-   $lines = include $brewfile | splitList "\n" }}
{{- end -}}
{{- range without $lines "" }}
{{-   if eq (substr 0 1 .) "#" -}}
{{-     continue -}}
{{-   end -}}
{{-   $type := index (. | splitList " ") 0 }}
{{-   $pattern := printf "^%s \"(.*)\",? ?(.*)$" $type }}
{{-   $name := . | replaceAllRegex $pattern "${1}" }}
{{-   $options := . | replaceAllRegex $pattern "${2}" }}
{{-   if eq $type "tap" }}
{{-     if get $taps $name -}}
{{-       warnf "Overriding %s %s (%s -> %s)" $type $name (get (get $taps $name) "options") $options -}}
{{-     end -}}
{{-     $_ := set $taps $name (dict "options" $options) }}
{{-   else if eq $type "brew" }}
{{-     if get $.packages.brew $name -}}
{{-       warnf "Overriding %s %s (%s -> %s)" $type $name (get (get $.packages.brew $name) "options") $options -}}
{{-     end -}}
{{-     $_ := set $.packages.brew $name (dict "options" $options) }}
{{-   else if eq $type "cask" }}
{{-     if get $.packages.cask $name -}}
{{-       warnf "Overriding %s %s (%s -> %s)" $type $name (get (get $.packages.cask $name) "options") $options -}}
{{-     end -}}
{{-     $_ := set $.packages.cask $name (dict "options" $options) }}
{{-   else if eq $type "mas" }}
{{-     if get $.packages.mas $name -}}
{{-       warnf "Overriding %s %s (%s -> %s)" $type $name (get (get $.packages.mas $name) "options") $options -}}
{{-     end -}}
{{-     $_ := set $.packages.mas $name (dict "options" $options) }}
{{-   else if eq $type "vscode" }}
{{-     if get $.packages.vscode $name -}}
{{-       warnf "Overriding %s %s (%s -> %s)" $type $name (get (get $.packages.vscode $name) "options") $options -}}
{{-     end -}}
{{-     $_ := set $.packages.vscode $name (dict "options" $options) }}
{{-   end }}
{{- end }}

{{- $_ := set .packages "tap" $taps }}

{{- range $type := list "tap" "brew" "cask" "mas" "vscode" }}
{{-   if not (hasKey $.packages $type) }}
{{-     continue }}
{{-   end }}
{{-   range $name, $pkg := get $.packages $type }}
{{-     if not (kindIs "map" $pkg) }}
{{-       warnf "%s is not a map: %s" $name $pkg }}
{{-       $pkg = dict }}
{{-     end }}
{{ $type }} {{ $name | quote }}
{{-     if not (kindIs "map" $pkg) }}
{{-       warnf "%s: %s: %s" $type $name $pkg }}
{{-       continue }}
{{-     end }}
{{-     range $key, $value := pick $pkg
  "args"
  "conflicts_with"
  "link"
  "restart_service"
  "version_file"

  "appdir"
  "greedy"
  "require_sha"

  "id"
-}}
{{- /* if OS.linux? or OS.mac? */ -}}
{{- /* cask "java" unless system "/usr/libexec/java_home", "--failfast" */ -}}
, {{ $key }}: {{ $value | toJson }}
{{-     end }}
{{-     if get $pkg "options" -}}
, {{ $pkg.options }}
{{-     end }}
{{-   end }}
{{- end }}
# ENV["SOME_ENV_VAR"] = "some_value"
