{{- range $type := list "tap" "brew" "cask" "mas" "vscode" }}
{{-   if not (hasKey $.packages $type) }}
{{-     continue }}
{{-   end }}
{{-   range $name, $pkg := get $.packages $type }}
{{-     if not (kindIs "map" $pkg) }}
{{-       warnf "%s is not a map: %s" $name $pkg }}
{{-       $pkg = dict }}
{{-     end }}
{{ $type }} {{ $name | quote }}
{{-     if not (kindIs "map" $pkg) }}
{{-       warnf "%s: %s: %s" $type $name $pkg }}
{{-       continue }}
{{-     end }}
{{-     range $key, $value := pick $pkg
  "args"
  "conflicts_with"
  "link"
  "restart_service"
  "version_file"

  "appdir"
  "greedy"
  "require_sha"

  "id"
-}}
{{- /* if OS.linux? or OS.mac? */ -}}
{{- /* cask "java" unless system "/usr/libexec/java_home", "--failfast" */ -}}
, {{ $key }}: {{ $value | toJson }}
{{-     end }}
{{-     if get $pkg "options" -}}
, {{ $pkg.options }}
{{-     end }}
{{-   end }}
{{- end }}
# ENV["SOME_ENV_VAR"] = "some_value"
