---
- name: Install apt packages
  apt:
    name: "{{ item.name|default(item) }}"
    state: "{{ item.state|default(packages_state) }}"
  with_items: "{{ packages }}"
  when: packages_install
  become: yes
