---
- name: Check source path
  assert:
    that:
      - "source != inventory_dir"

# - name: Confirm destination
#   pause: prompt={{ destination }}

- name: "Ensure {{ role_dir }} targets are directories"
  file:
    path: "{{ item }}"
    state: directory
    follow: true
  with_items:
    - "{{ source }}"
    - "{{ destination }}"
