# General settings

set-option -g default-terminal "xterm-256color"
# screen, screen-256color, tmux, tmux-256color, xterm-256color...
# git pull/push w/o xterm-256color = fatal: protocol error: bad line length character

# General xterm(1) -style function key sequences
# set-option -g xterm-keys on

# Don't wait for escape characters (default: 500ms)
set-option -gs escape-time 50

# Scrollback size
set-option -g history-limit 10000

# Lock the session if inactive
set-option -g lock-after-time 1800

# Don't close dead panes
set-option -g remain-on-exit off

# Action on window bell
# any: a bell in any window causes a bell in the current one
# none: all bells are ignored
# current: only bells in windows other than the current are ignored
# other: bells in the current window are ignored
set-option -g bell-action current
