# General settings

# Weechat requires tmux* or screen*
# screen-256color -> fatal: protocol error: bad line length character
# screen, tmux, tmux-256color, xterm-256color...
# set-option -g default-terminal "xterm-256color"

# Don't wait for escape characters
set-option -gs escape-time 10

# Scrollback size
set-option -g history-limit 10000

# Locks
set-option -g lock-after-time 1800

# Keep windows around after they exit
# set-option -g remain-on-exit on

# Turn on xterm key bindings so that additional function keys get escape sequences
set-option -g xterm-keys on

# No bells at all
set-option -g bell-action none

# Disable window activity message
set-option -g visual-activity off

# Enable activity alerts
set-window-option -g monitor-activity on

# Automatically renumber windows
set-option -g renumber-windows on

# Start numbering at 1
set-option -g base-index 1
set-window-option -g pane-base-index 1

# Window renaming
set-window-option -g allow-rename on
set-window-option -g automatic-rename on
