# Theming

source-file ~/.tmux/colors/solarized-dark.conf

# Terminal title
# #H  Hostname of local host
# #I  Current window index
# #P  Current pane index
# #S  Session name
# #T  Current window title
# #W  Current window name
set-option -g set-titles on
# set-option -g set-titles-string '#S #I.#P #W #T'
# '#S:#I:#W - #T #{session_alerts}'

# Status
set-option -g status on
set-option -g status-interval 10
set-option -g status-justify left # centre, right
set-option -g status-position bottom
# set-option -g status-keys vi # emacs

# Window status
# setw -g window-status-format '#[fg=brightblack] #I#[fg=default]#{?window_flags,#F, }#[fg=brightblack]#W '
set-window-option -g window-status-format ' #I#{?window_flags,#F, }#W '

# Current window
# setw -g window-status-current-format '#[fg=brightblack] #I#[fg=default]#{?window_flags,#F, }#[fg=white]#W '
set-window-option -g window-status-current-format ' #I#{?window_flags,#F, }#W '

# Left status
set-option -g status-left-length 20
set-window-option -g status-left ''
# Prefix
set-window-option -ga status-left '#{?client_prefix,#[reverse],}'
# Session name
set-window-option -ga status-left ' #S ' # '[#S #I:#P] '

# Right status
set-option -g status-right-length 80
set-window-option -g status-right '' # '#{=21:pane_title} %H:%M %d-%b-%y'
# Public IP
set-window-option -ga status-right ' #(curl ipecho.net/plain;echo)'
# Host name
set-window-option -ga status-right ' #H'
# Date and time
set-window-option -ga status-right ' %a %b %d %H:%M '


### https://github.com/fcambus/ansiweather

## Styles
#setw -g status-style fg=white,bg=colour10
#setw -g status-left-style fg=colour12,bg=colour10
#setw -g status-right-style fg=colour12,bg=colour10

## Left section

#setw -g status-left ''
## Host
#setw -ga status-left '#[fg=black,bg=blue]'
#setw -ga status-left '#{?client_prefix,#[bg=green],}'
#setw -ga status-left ' #H '
##setw -ga status-left '#[nobold]'
#setw -ga status-left '#[fg=colour7,bg=colour11]'
## Session name, index and panel index
#setw -ga status-left ' #S #I.#P '
## User
##setw -ga status-left '#[fg=white,bg=brightblack] #(whoami) '
## System
##setw -ga status-left '#[fg=white,bg=default] #(uname -r | cut -c 1-6) #(echo $MACHTYPE) '
#setw -ga status-left '#[fg=colour11,bg=default] '

## Right section

#setw -g status-right ''

## Memory (npm install -g tmux-mem)
## Format ":currentBytes #[fg=:color]:percent#[fg=default] │#[fg=:color]:spark#[fg=default]│"
##setw -ga status-right '#(tmux-mem --format "#[fg=:color]:spark#[fg=default]") '
## CPU (npm install -g tmux-cpu)
## Format ":load #[fg=:color]:percent#[fg=default] │#[fg=:color]:spark#[fg=default]│"
##setw -ga status-right '#(tmux-cpu --format "#[fg=:color]:spark#[fg=default]") '

## IP
#setw -ga status-right '#[fg=brightblack]'
#setw -ga status-right ' #(curl ipecho.net/plain;echo) '
## Battery
## setw -ga status-right ' #{battery_percentage}#[bg=default] '
#setw -ga status-right '#[fg=colour7,bg=colour11]'
## Date
#setw -ga status-right ' %a %b %d '
#setw -ga status-right '#[fg=black,bg=blue]'
#setw -ga status-right '#{?client_prefix,#[bg=green],}'
## Time
#setw -ga status-right ' %H:%M '
## Session and panel index
##setw -ga status-right '#[fg=black,bg=blue]#{?client_prefix,#[bg=green],} #I: #P '

##(ifstat)
##(cpu-load 1)

## Windows

#setw -g window-status-style fg=colour11,bg=colour10
#setw -g window-status-format '#[fg=brightblack] #I#[fg=default]#{?window_flags,#F, }#[fg=brightblack]#W '

## Current window
#setw -g window-status-current-style fg=colour11,bg=black
#setw -g window-status-current-format '#[fg=brightblack] #I#[fg=default]#{?window_flags,#F, }#[fg=white]#W '

## Active window
#setw -g window-status-activity-style fg=colour12,bg=colour10 #fg=black,bg=brightblue

## Activity message
#set -g message-style fg=black,bg=green

## Pane borders
#set -g pane-border-style fg=colour10,bg=black
#set -g pane-active-border-style fg=colour11,bg=black
