# Titles

set-option -g set-titles on

# Example title format: '#S #I.#P #W #T'
# #H  Hostname of local host
# #I  Current window index
# #P  Current pane index
# #S  Session name
# #T  Current window title
# #W  Current window name
set-option -g set-titles-string '#S #W #T #{session_alerts}'
