# Bindings

# Use vi or emacs-style key bindings in the status line
set-option -g status-keys emacs

# Use vi or emacs-style key bindings in copy and choice modes
set-window-option -g mode-keys vi

# Vi-style selection (exclusive: no if tmux < 1.5)
# TODO: https://gist.github.com/brendanhay/1769870
# bind-key -t vi-copy 'v' begin-selection
# bind-key -t vi-copy 'y' copy-selection

# Change the default prefix binding to Ctrl-a
set -g prefix C-a
bind C-a send-prefix
unbind C-b

# Reload config
bind r source-file ~/.tmux.conf \; display-message 'Reloaded ~/.tmux.conf'

# Switch to last window
bind a last-window

# Open new window and splits in the same directory
bind c new-window -c '#{pane_current_path}'
bind '"' split-window -c '#{pane_current_path}'
bind % split-window -h -c '#{pane_current_path}'

# Vim style pane navigation
unbind-key j
bind-key j select-pane -D
unbind-key k
bind-key k select-pane -U
unbind-key h
bind-key h select-pane -L
unbind-key l
bind-key l select-pane -R

# Vim style pane resizing
bind H resize-pane -L 15
bind J resize-pane -D 15
bind K resize-pane -U 15
bind L resize-pane -R 15

# Quick pane cycling
# unbind ^A
# bind ^A select-pane -t :.+

# Some extra key bindings to select higher numbered windows
# bind F1 selectw -t:10
# bind F2 selectw -t:11
# bind F3 selectw -t:12
# bind F4 selectw -t:13
# bind F5 selectw -t:14
# bind F6 selectw -t:15
# bind F7 selectw -t:16
# bind F8 selectw -t:17
# bind F9 selectw -t:18
# bind F10 selectw -t:19
# bind F11 selectw -t:20
# bind F12 selectw -t:21
