# Windows

# Disable activity message
set-option -g visual-activity off

# Enable activity alerts
set-window-option -g monitor-activity on

# Automatically renumber windows
set-option -g renumber-windows on

# Start numbering at 1
set-option -g base-index 1
set-window-option -g pane-base-index 1

# Window renaming
set-window-option -g allow-rename on
set-window-option -g automatic-rename on
