---
- name: Install Homebrew Casks
  homebrew_cask:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default(homebrew_cask_state) }}"
  environment:
    HOMEBREW_CASK_OPTS: "--appdir={{ homebrew_cask_appdir }}"
  with_items: "{{ homebrew_cask_apps }}"
  when: homebrew_cask_install

# - name: Homebrew Casks cleanup
#   shell: brew cask cleanup
#   when: homebrew_cask_cleanup

# - name: Configure Homebrew Casks
#   command: "{{ item.1 }}"
#   args:
#     executable: "{{ item.0.cli }}"
#   with_subelements:
#     - "{{ casks_cli }}"
#     - options

# - name: Cask files
#   debug: msg={{ item }}
#   with_fileglob:
#     - "*"
