#!/bin/bash

on_click_event() {
  button=$(echo "$@" | i3cat decode button)
  [[ "$button" != 1 ]] && return

  name=$(echo "$@" | i3cat decode name)
  instance=$(echo "$@" | i3cat decode instance)

  echo "$name:$instance $(date)" >> ~/.i3debug
}

# Network speed
# $HOME/.config/i3/bin/net-speed

# i3 status
i3status --config "$HOME/.config/i3/status.conf"

# Read stdin from JSON click events
cat | while real line
do
  on_click_event "$line"
done
