---
- name: "Insert/update {{ blocks | length }} blocks"
  blockinfile:
    dest: "{{ item.dest }}"
    block: "{{ item.block }}"
    backup: "{{ item.backup | default(blockinfile_backup) }}"
    create: "{{ item.create | default(blockinfile_create) }}"
    state: "{{ item.state | default(omit) }}"
  with_items: "{{ blocks }}"
  when: "{{ item.when | default(true) }}"
