---
extraPackages:
  bash:
    enabled: '{{ and (get .features "bash") (eq .osIDLike "alpine" "darwin") }}'
  bash-completion:
    enabled: '{{ and (get .features "bash") (eq .osIDLike "alpine" "darwin") }}'
