---
packages:
  bash:
    enabled: '{{ and .features.bash (ne .os "windows") }}'
  bash-completion:
    enabled: '{{ and .features.bash (ne .os "windows") }}'
  bats:
    enabled: '{{ and .features.bash (eq .osIDLike "arch" "darwin") }}'
    # nameOverwrite:
    #   pacman: bats bats-assert bats-support
    type: brew
  kaos/shell/bats-assert kaos/shell/bats-support: # bats-file
    enabled: '{{ and .features.bash (eq .osIDLike "arch" "darwin") }}'
    type: brew
  kaos/shell/bats-mock:
    enabled: '{{ and .features.bash (eq .osIDLike "arch" "darwin") }}'
    type: brew
  kcov:
    enabled: '{{ and .features.bash (eq .osIDLike "arch" "darwin") }}'
