---
packages:
  bash:
    enabled: '{{ and .features.bash (ne .os "windows") }}'
  bash-completion:
    enabled: '{{ and .features.bash (ne .os "windows") }}'
  # FIXME: "mise install bats" 404 on android
  bats:
    enabled: '{{ and .features.bash (or .features.brew (eq .osIDLike "alpine" "arch")) }}'
    nameOverwrite:
      brew: bats-core
      # pacman: bats bats-assert bats-support
    type: '{{ not (eq .osIDLike "alpine" "arch") | ternary "brew" nil }}'
  # FIXME: bats-assert is missing stderr functions on alpine
  bats-assert bats-support bats-file:
    enabled: '{{ and .features.bash (or .features.brew (eq .osIDLike "arch")) }}' # "alpine"
    nameOverwrite:
      brew: kaos/shell/bats-assert kaos/shell/bats-support kaos/shell/bats-file
    # type: '{{ not (eq .osIDLike "alpine" "arch") | ternary "brew" nil }}'
    type: '{{ not (eq .osIDLike "arch") | ternary "brew" nil }}'
  bats-mock:
    enabled: "{{ and .features.bash .features.brew }}"
    nameOverwrite:
      brew: kaos/shell/bats-mock
    type: brew
  kcov:
    enabled: "{{ or .features.bash .features.brew }}"
    type: '{{ not (eq .osIDLike "arch") | ternary "brew" nil }}'
