---
packages:
  goss:
    enabled: "{{ .features.goss }}"
    nameOverwrite:
      arch: goss-bin
    type: '{{ eq .osID "alpine" "android" "darwin" "fedora" "ubuntu" | ternary "mise" (eq .osIDLike "arch" | ternary "aur" nil) }}'
