---
packages:
  goss:
    enabled: "{{ .features.goss }}"
    nameOverwrite:
      arch: '{{ eq .chezmoi.arch "arm64" | ternary "goss" "goss-bin" }}'
    # mise: android, darwin, fedora, ubuntu
    type: '{{ and (eq .osIDLike "arch") (ne .chezmoi.arch "arm64") | ternary "aur" "mise" }}'
