---
dependencies:

  - role: homebrew-cask
    homebrew_cask_apps:
      - hammerspoon
    # when: "ansible_os_family == 'Darwin'"

  # - role: dotfiles
  #   paths:
  #     - name: hammerspoon
  #       dest: .hammerspoon

galaxy_info:
  galaxy_tags: system
