---
# - name: Symlink
#   set_fact:
#     dot_paths: "{{ dot_paths | default([]) + [{
#         'name': item.name | default(item),
#         'src': dot_root + '/' + item.src + '/' + (item.pattern | default('*')) if item.src is defined else dot_root + '/' + (item.dir | default('roles')) + '/' + (item.name | default(item)) + '/' + (item.role_dir | default('files')) + '/' + (item.pattern | default('*')),
#         'dest': dot_home + '/' + item.dest if item.dest is defined else dot_home + '/' + (item.name | default(item)) + '/' + (item.prefix | default('')),
#         'paths': lookup('fileglob', dot_root + '/' + item.src + '/' + (item.pattern | default('*')) if item.src is defined else dot_root + '/' + (item.dir | default('roles')) + '/' + (item.name | default(item)) + '/' + (item.role_dir | default('files')) + '/' + (item.pattern | default('*'))),
#       }] }}"
#   with_items: "{{ paths }}"

# - debug:
#     msg: "{{ lookup('dotfile', 'ruby/files,roles.test', '*', {'dest': 'rc', 'prefix': 'tmux-'}) }}"
# - fail:

- name: Init
  set_fact:
    dot_paths: []
    dot_paths_dest: []

- name: Prepare
  set_fact:
    dot_paths: >
      {{ dot_paths + [
        {
          'state': 'template' if item.template is defined and item.template else item.state | default('link'),
          'items': lookup('dotfile',
            dot_local_dir + '/' + item.src if item.src is defined else item.name | default(item.name | default(item))
              + '/' + item.dir | default('templates' if item.template is defined and item.template else 'files')
              + ',' + (item.role_dir if item.role_dir is defined else role_dir | default('')),
            item.pattern | default('*'),
            {
              'dest': item.dest | default(''),
              'prefix': item.prefix | default(''),
              'substr': item.substr | default('.j2'),
              },
            wantlist=True),
        }
      ]}}
  with_items: "{{ paths }}"
  # with_fileglob: "{{ dot_paths | map(attribute='src') | list }}"

- set_fact:
    dot_paths_dest: "{{ dot_paths_dest + [item.dest | dirname] }}"
  with_flattened:
    - "{{ dot_paths | map(attribute='items') | list }}"
  # no_log: true

- name: Check destination
  file:
    path: "{{ item }}"
    state: directory
  with_items: "{{ dot_paths_dest | unique }}"
  # with_subelements:
  #     - "{{ dot_paths }}"
  #     - items

- name: Action
  action: "{{ 'file' if item.0.state in ['link','touch','absent','present'] else item.0.state }}"
  args:
    src: "{{ item.1.path }}"
    dest: "{{ item.1.dest }}"
    state: "{{ item.0.state if item.0.state not in ['template'] else omit }}"
    # backup: "{{ 'yes' if dot_backup_enable and dot_backup_templates else 'no' }}"
    # force: "{{ 'yes' if item.0.state not in ['template'] else 'no' }}"
  with_subelements:
      - "{{ dot_paths }}"
      - items
  # when: "item.0.state in ['template']"
