---
- name: Init
  set_fact:
    dot_paths: []
    dot_states:
      - absent
      - directory
      - link
      - present
      - touch

- name: Prepare
  vars:
    name: "{{ item.name | default(item) }}"
    dir: "{{ item.role_dir if item.role_dir is defined else role_dir | default('') }}"
    type: "{{ item.dir | default('templates' if item.template is defined and item.template else 'files') }}"
    action: "{{ 'template' if item.template is defined and item.template else item.state | default('link') }}"
  set_fact:
    dot_paths: >
      {{ dot_paths +
        lookup('dotfile',
          (
            dot_local_dir + '/' + item.src if item.src is defined else 
            name + '/' + type if '/' not in name else name
          ) + ',' + dir,
          item.pattern | default('*'), {
            'dest': item.dest | default(''),
            'prefix': item.prefix | default(''),
            'substr': item.substr | default('.j2'),
          },
          wantlist=True
        )
      | map('combine', {
        'state': action,
      }) | list }}
  with_items: "{{ paths }}"
  # with_fileglob: "{{ dot_paths | map(attribute='src') | list }}"

# - set_fact:
#     dot_paths_dest: "{{ dot_paths_dest + [item.dest | dirname] }}"
#   with_flattened:
#     - "{{ dot_paths | map(attribute='items') | list }}"
#   # no_log: true

- name: Check destination
  file:
    path: "{{ item }}"
    state: directory
  with_items: "{{ dot_paths | map(attribute='dest') | map('dirname') | list | unique }}"
  # with_subelements:
  #     - "{{ dot_paths }}"
  #     - items

- name: Action
  action: "{{ 'file' if item.state in dot_states else item.state }}"
  args:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: "{{ item.state if item.state not in ['template'] else omit }}"
  with_items: "{{ dot_paths }}"
    # backup: "{{ 'yes' if dot_backup_enable and dot_backup_templates else 'no' }}"
    # force: "{{ 'yes' if item.0.state not in ['template'] else 'no' }}"
  # with_subelements:
  #     - "{{ dot_paths }}"
  #     - items
  # when: "item.0.state in ['template']"
