var data = {files:[
{"link":"00-install-xdg.sh.eed7b8bb.html","title":"00-install-xdg.sh","summary_name":"/private/var/folders/6c/pzd640_546q6_yfn24r65c_40000gn/T/bats-XXXXXX.ihthBmaNTP/.chezmoiscripts/00-install-xdg.sh","covered_class":"lineCov","covered":"100.0","covered_lines":"14","uncovered_lines":"0","total_lines" : "14"},
{"link":"01-install-tools.sh.c4a4fcd8.html","title":"01-install-tools.sh","summary_name":"/private/var/folders/6c/pzd640_546q6_yfn24r65c_40000gn/T/bats-XXXXXX.ihthBmaNTP/.chezmoiscripts/01-install-tools.sh","covered_class":"lineCov","covered":"100.0","covered_lines":"12","uncovered_lines":"0","total_lines" : "12"},
{"link":"executable_nvim-sh.f54330bd.html","title":"executable_nvim-sh","summary_name":"/Users/runner/work/dotfiles/dotfiles/home/dot_local/bin/executable_nvim-sh","covered_class":"lineNoCov","covered":"0.0","covered_lines":"0","uncovered_lines":"19","total_lines" : "19"},
{"link":"02-install-brew-packages.sh.45a54031.html","title":"02-install-brew-packages.sh","summary_name":"/private/var/folders/6c/pzd640_546q6_yfn24r65c_40000gn/T/bats-XXXXXX.ihthBmaNTP/.chezmoiscripts/02-install-brew-packages.sh","covered_class":"lineCov","covered":"100.0","covered_lines":"7","uncovered_lines":"0","total_lines" : "7"},
{"link":"executable_chezmoi-execute.c66a6c27.html","title":"executable_chezmoi-execute","summary_name":"/Users/runner/work/dotfiles/dotfiles/home/dot_local/bin/executable_chezmoi-execute","covered_class":"lineNoCov","covered":"0.0","covered_lines":"0","uncovered_lines":"2","total_lines" : "2"},
{"link":"test.1360941a.html","title":"test","summary_name":"/Users/runner/work/dotfiles/dotfiles/script/test","covered_class":"lineCov","covered":"100.0","covered_lines":"8","uncovered_lines":"0","total_lines" : "8"},
{"link":"bootstrap.38b56fc6.html","title":"bootstrap","summary_name":"/Users/runner/work/dotfiles/dotfiles/script/bootstrap","covered_class":"linePartCov","covered":"40.9","covered_lines":"9","uncovered_lines":"13","total_lines" : "22"},
{"link":"executable_git-P.37405422.html","title":"executable_git-P","summary_name":"/Users/runner/work/dotfiles/dotfiles/home/dot_local/bin/executable_git-P","covered_class":"lineNoCov","covered":"0.0","covered_lines":"0","uncovered_lines":"2","total_lines" : "2"},
{"link":"executable_shpool-a.78bd3ea3.html","title":"executable_shpool-a","summary_name":"/Users/runner/work/dotfiles/dotfiles/home/dot_local/bin/executable_shpool-a","covered_class":"lineNoCov","covered":"0.0","covered_lines":"0","uncovered_lines":"10","total_lines" : "10"},
{"link":"container.aeb4c5ad.html","title":"container","summary_name":"/Users/runner/work/dotfiles/dotfiles/script/container","covered_class":"linePartCov","covered":"42.8","covered_lines":"80","uncovered_lines":"107","total_lines" : "187"},
{"link":"executable_t.c3e69d89.html","title":"executable_t","summary_name":"/Users/runner/work/dotfiles/dotfiles/home/dot_local/bin/executable_t","covered_class":"lineNoCov","covered":"0.0","covered_lines":"0","uncovered_lines":"13","total_lines" : "13"},
{"link":"executable_iperf3-plot.dd86af8a.html","title":"executable_iperf3-plot","summary_name":"/Users/runner/work/dotfiles/dotfiles/home/dot_local/bin/executable_iperf3-plot","covered_class":"lineNoCov","covered":"0.0","covered_lines":"0","uncovered_lines":"23","total_lines" : "23"},
{"link":"executable_package-manager.f0c50c5f.html","title":"executable_package-manager","summary_name":"/Users/runner/work/dotfiles/dotfiles/home/dot_local/bin/executable_package-manager","covered_class":"lineNoCov","covered":"18.5","covered_lines":"5","uncovered_lines":"22","total_lines" : "27"},
{"link":"executable_e.a956bd7b.html","title":"executable_e","summary_name":"/Users/runner/work/dotfiles/dotfiles/home/dot_local/bin/executable_e","covered_class":"lineNoCov","covered":"0.0","covered_lines":"0","uncovered_lines":"10","total_lines" : "10"},
{"link":"update.c46240d6.html","title":"update","summary_name":"/Users/runner/work/dotfiles/dotfiles/script/update","covered_class":"lineCov","covered":"100.0","covered_lines":"5","uncovered_lines":"0","total_lines" : "5"},
{"link":"bench.92c7499e.html","title":"bench","summary_name":"/Users/runner/work/dotfiles/dotfiles/script/bench","covered_class":"lineCov","covered":"92.1","covered_lines":"35","uncovered_lines":"3","total_lines" : "38"},
{"link":"executable_chezmoi-package.e7611b6c.html","title":"executable_chezmoi-package","summary_name":"/Users/runner/work/dotfiles/dotfiles/home/dot_local/bin/executable_chezmoi-package","covered_class":"linePartCov","covered":"35.6","covered_lines":"31","uncovered_lines":"56","total_lines" : "87"},
{"link":"executable_chezmoi-check.f31b689d.html","title":"executable_chezmoi-check","summary_name":"/Users/runner/work/dotfiles/dotfiles/home/dot_local/bin/executable_chezmoi-check","covered_class":"lineNoCov","covered":"0.0","covered_lines":"0","uncovered_lines":"15","total_lines" : "15"},
{"link":"executable_shpool-select.f2a994e8.html","title":"executable_shpool-select","summary_name":"/Users/runner/work/dotfiles/dotfiles/home/dot_local/bin/executable_shpool-select","covered_class":"lineNoCov","covered":"0.0","covered_lines":"0","uncovered_lines":"8","total_lines" : "8"},
{"link":"executable_repeat-last-command.15cf1b08.html","title":"executable_repeat-last-command","summary_name":"/Users/runner/work/dotfiles/dotfiles/home/dot_local/bin/executable_repeat-last-command","covered_class":"lineNoCov","covered":"0.0","covered_lines":"0","uncovered_lines":"5","total_lines" : "5"},
{"link":"executable_chezmoi-feature.26de099f.html","title":"executable_chezmoi-feature","summary_name":"/Users/runner/work/dotfiles/dotfiles/home/dot_local/bin/executable_chezmoi-feature","covered_class":"linePartCov","covered":"39.7","covered_lines":"25","uncovered_lines":"38","total_lines" : "63"},
{"link":"executable_list-package.5eb0518b.html","title":"executable_list-package","summary_name":"/Users/runner/work/dotfiles/dotfiles/home/dot_local/bin/executable_list-package","covered_class":"lineNoCov","covered":"15.2","covered_lines":"5","uncovered_lines":"28","total_lines" : "33"},
{"link":"check.c89106a8.html","title":"check","summary_name":"/Users/runner/work/dotfiles/dotfiles/script/check","covered_class":"linePartCov","covered":"56.5","covered_lines":"13","uncovered_lines":"10","total_lines" : "23"},
{"link":"executable_k.4eee907c.html","title":"executable_k","summary_name":"/Users/runner/work/dotfiles/dotfiles/home/dot_local/bin/executable_k","covered_class":"lineNoCov","covered":"0.0","covered_lines":"0","uncovered_lines":"8","total_lines" : "8"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "test", "date" : "2025-11-11 23:28:41", "instrumented" : 641, "covered" : 249,};
var merged_data = [];
