---
extraPackages:
  nodejs:
    enabled: '{{ and .features.node (eq .osIDLike "alpine" "android") }}'
    nameOverwrite:
      windows: OpenJS.NodeJS # .LTS
    # type: '{{ eq .osIDLike "windows" | ternary "winget" nil }}'
  npm:
    enabled: '{{ and .features.node (eq .osIDLike "alpine") }}'
    # enabled: '{{ .features.node }}'
    # type: ne .osIDLike  '{{"alpine" | ternary "npm" nil }}'
