---
extraPackages:
  nodejs:
    condition: and .features.node (eq .osIDLike "alpine" "android")
    nameOverwrite:
      windows: OpenJS.NodeJS # .LTS
    # type: eq .osIDLike "windows" | ternary "winget" nil
  npm:
    condition: and .features.node (eq .osIDLike "alpine")
