---
enabled: "{{ .features.node }}"
packages:
  bun:
    # FIXME: bun download fails in termux
    enabled: '{{ not (eq .osIDLike "android") }}'
    type: mise
  node-mise:
    enabled: '{{ not (eq .osIDLike "alpine" "android") }}'
    name: node
    version: lts # {{ `{{ env['NODE_VERSION'] | default(value='lts') }}` }}
    type: mise
  nodejs:
    enabled: '{{ eq .osIDLike "alpine" "windows" }}'
    nameOverwrite:
      alpine: node
      # android: nodejs # -lts
      # arch: nodejs # -lts-jod
      # darwin: node@24
      windows: OpenJS.NodeJS # .LTS
    # FIXME(termux): hangs terminal "No such file or directory (os error 2)"
    # ~/.local/share/mise/installs/node/23.11.0/bin/node -v
    # type: '{{ eq .osIDLike "alpine" | ternary nil "mise" }}'
    # version: '{{ eq .packageType "mise" | ternary "lts" "" }}'
  npm:
    type: '{{ eq .osIDLike "alpine" | ternary nil "npm" }}'
  pnpm:
    # pnpm.pnpm
    type: npm
  yarn:
    type: npm
  runme:
    type: npm
  "@fission-ai/openspec":
    enabled: "{{ .features.ai }}"
    type: npm
  "@kilocode/cli":
    enabled: "{{ .features.ai }}"
    type: npm
  "@qodo/command": # uv tool install pr-agent
    enabled: "{{ .features.ai }}"
    type: npm
  cline: # roocode
    enabled: "{{ .features.ai }}"
    type: npm
  bash-language-server:
    enabled: "{{ not .features.neovim }}"
    type: npm
  prettier:
    enabled: "{{ not .features.neovim }}"
    type: npm
  sql-language-server:
    enabled: "{{ and .features.sql (not .features.neovim) }}"
    type: npm
  typescript:
    enabled: "{{ not .features.neovim }}"
    type: npm
  typescript-language-server:
    enabled: "{{ not .features.neovim }}"
    type: npm
  # https://github.com/hrsh7th/vscode-langservers-extracted/pull/11
  vscode-langservers-extracted@4.8:
    enabled: "{{ not .features.neovim }}"
    type: npm
  yaml-language-server@next:
    enabled: "{{ not .features.neovim }}"
    type: npm
