---
dependencies:

  - role: package
    packages: "{{ ruby_packages }}"

  # Manage gems with pacman on arch: ruby-<gem>
  # https://wiki.archlinux.org/index.php/Ruby#Managing_RubyGems_using_pacman

  - role: symlink
    dot_files:
      ruby:
        prefix: .
