---
dependencies:

  # https://github.com/rvm/rvm1-ansible
  # rbenv?

  - role: package
    packages: "{{ ruby_packages }}"
    # Debian: You may need to run a full aptitude upgrade to get the ruby package

  - role: dotfiles
    paths:
      - ruby
      - name: ruby
        prefix: .
      - name: shell
        prefix: .
      - name: vim
        dest: .vim
        state: template
        pattern: "*.vimrc"
      - name: bin
        src: "{{ dot_root }}/bin"
        dest: bin
