---
dependencies:

  # https://github.com/rvm/rvm1-ansible
  # rbenv?

  - role: package
    packages: "{{ ruby_packages }}"
    # Debian: You may need to run a full aptitude upgrade to get the ruby package

  - role: symlink
    dot_files:
      ruby:
        prefix: .
