---
bash_dir: "{{ dot_home }}/.bash.d"

bash_blocks:
  # Source ~/.bash.d/init.bash from ~/.bashrc
  - dest: "{{ dot_home }}/.bashrc"
    block: |
      source "{{ bash_dir }}/init.bash"
  # Source ~/.bashrc from ~/.bash_profile
  - dest: "{{ dot_home }}/.bash_profile"
    block: |
      if [[ -f ~/.bashrc ]] && [[ -r ~/.bashrc ]]; then
        [[ -n "$PS1" ]] && source ~/.bashrc
      fi


bash_files:
  spark:
    url: "https://raw.githubusercontent.com/holman/spark/master/spark"
    dest: bin
    # mode: u=rwx,g=rx,o=rx
    mode: u+x # 0755
  # git-prompt.bash:
  #   url: "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh"
  #   dest: .bash.d/library
