---
dependencies:

  # Archlinux (nodejs, npm), MacOSX (node)
  - role: package
    packages: "{{ node_packages }}"
    when: node_packages | length > 0
    # and ansible_os_family in ['Archlinux', 'Darwin']

  # Debian/RedHat
  - role: node
    when: "ansible_os_family == 'Debian'"

  # Windows
  # Download and execute the installer on nodejs.org
  # Add '/cygdrive/c/Program Files/nodejs' to $PATH

  - role: template
    dot_files:
      npm:
        prefix: .

  - role: symlink
    dot_files:
      npm:
        prefix: .
