---
dependencies:

  # Install NodeJS for MacOSX
  - role: package
    packages:
      - node
    when: "ansible_os_family == 'Darwin'"

  # Install NodeJS for Debian/RedHat
  - role: node
    when: "ansible_os_family == 'Debian'"

  - role: template
    dot_files:
      npm:
        prefix: .

  - role: symlink
    dot_files:
      npm:
        prefix: .
