---
# http://beyondgrep.com/install/
# curl http://beyondgrep.com/ack-2.14-single-file > ~/bin/ack && chmod 0755 !#:3

- name: Rename ack-grep to ack
  command: dpkg-divert --local --divert /usr/bin/ack --rename --add /usr/bin/ack-grep
  args:
    creates: /usr/bin/ack
  become: yes
  when: "ansible_os_family == 'Debian'"
