---
dot_files: {}

dot_backup_enable: yes
dot_backup_files: yes
dot_backup_templates: yes
dot_backup_no_log: yes

dot_find_options: -maxdepth 0 -print ! -name '*~'
dot_find_pattern: /*

dot_roles_dir: roles
