---
caddy:
  admin:
    port: 2019
  sites:
    bifrost:
      feature: oage
      body: html
      port: 8180
      liveness: /
    claude-task-viewer:
      feature: claude
      body: html
      port: 3456
      liveness: /
    grafana:
      feature: otel
      body: '"database": "ok"'
      port: 3033
      liveness: /api/health
      caddy:
        dialTimeout: 1800s
        responseHeaderTimeout: 1800s
    mailpit:
      feature: php
      body: html
      port: 8025
      liveness: /
    # open-notebook:
    #   feature: oage
    #   body: html
    #   port: 8502
    #   health: /
    # open-notebook-api:
    #   feature: oage
    #   body: '{"status":"healthy"}'
    #   port: 5055
    #   health: /health
    open-webui:
      feature: oage
      body: '{"status":true}'
      port: 8503
      liveness: /health
    opencode:
      feature: opencode
      body: Unauthorized
      port: 4096
      liveness: /
      statusCode: 401
      tailscale: true
    process-compose:
      feature: processCompose
      body: '{"status":"alive"}'
      liveness: /live
      port: 8484
    prometheus:
      feature: otel
      body: Healthy
      port: 9090
      liveness: /-/healthy
    # surrealdb:
    #   feature: oage
    #   port: 8000
    #   health: /health
    tempo:
      feature: otel
      body: ready
      port: 3200
      liveness: /ready
    webhook:
      feature: otel
      body: OK
      liveness: /
      port: 9000
