" ~/.vimrc
" vim: foldenable foldmethod=marker

" github.com/mathiasbynens/dotfiles/blob/master/.vimrc
" github.com/tpope/vim-sensible/blob/master/plugin/sensible.vim"

set nocompatible

" Initialization {{{

" Autoload plugins
runtime bundle/pathogen/autoload/pathogen.vim
call pathogen#infect()
call pathogen#helptags()

if has('autocmd')
  filetype plugin indent on
endif

" Load matchit.vim, but only if the user hasn't installed a newer version.
if !exists('g:loaded_matchit') && findfile('plugin/matchit.vim', &rtp) ==# ''
  runtime macros/matchit.vim
endif

" }}}
" General {{{

set encoding=utf-8

if &history < 1000
  set history=1000
endif

" Reload files changed from the outside
set autoread

"if has('path_extra')
""  setglobal tags-=./tags tags-=./tags; tags^=./tags;
"endif

"if &shell =~# 'fish$'
"  set shell=/bin/bash
"endif

if &tabpagemax < 50
  set tabpagemax=50
endif

" Use Unix as the standard file type
set ffs=unix,dos,mac

" Use system clipboard
set clipboard=unnamed

" Fast terminal connection
set ttyfast

" Delete comment character when joining commented lines
if v:version > 703 || v:version == 703 && has("patch541")
  set formatoptions+=j
endif

" Tell vim to remember certain things when we exit
"  '10  :  marks will be remembered for up to 10 previously edited files
"  "100 :  will save up to 100 lines for each register
"  :20  :  up to 20 lines of command-line history will be remembered
"  %    :  saves and restores the buffer list
"  n... :  where to save the viminfo files
"set viminfo='10,\"100,:20,%,n~/.viminfo

if !empty(&viminfo)
  set viminfo^=!
endif

" Do not capture all global options
set sessionoptions-=options

set noswapfile
set nobackup
set nowb

" Keep undo history across sessions, by storing in file.
if has('persistent_undo') && !isdirectory(expand('~').'/.vim/backups')
  silent !mkdir ~/.vim/backups > /dev/null 2>&1
  set undodir=~/.vim/backups
  set undofile
endif

" }}}
" Theming {{{

set term=xterm-256color
"set term=screen-256color

" Disable BCE (Background Color Erase)
"if &term =~ '256color'
"  set t_ut=
"endif

if has('gui_running')
  set background=light
else
  set background=dark
endif

try
  "let base16colorspace=256
  colorscheme base16-railscasts
catch
  colorscheme torte
endtry

" Allow color schemes to do bright colors without forcing bold.
if &t_Co == 8 && $TERM !~# '^linux\|^Eterm'
  set t_Co=16
endif

" Enable syntax highlighting
if has('syntax') && !exists('g:syntax_on')
  syntax enable
endif

set synmaxcol=800
"set textwidth=80

set cursorline

if exists('+colorcolumn')
  set colorcolumn=80
  "let &colorcolumn=join(range(1,80),",")
endif

" }}}
" Colors {{{

" Hide line number background
"highlight LineNr ctermbg=none guibg=none

" Custom colors
hi clear SignColumn
hi VertSplit    ctermbg=236
hi ColorColumn  ctermbg=237
hi LineNr       ctermbg=236 ctermfg=240
hi CursorLineNr ctermbg=236 ctermfg=240
hi CursorLine   ctermbg=236

""hi StatusLineNC ctermbg=238 ctermfg=0
""hi StatusLine   ctermbg=240 ctermfg=12
"hi StatusLine   ctermfg=12 ctermbg=11
"hi StatusLineNC ctermfg=8 ctermbg=0

"hi IncSearch    ctermbg=3   ctermfg=1
"hi Search       ctermbg=1   ctermfg=3
hi Visual       ctermbg=3   ctermfg=0
"hi Pmenu        ctermbg=240 ctermfg=12
"hi PmenuSel     ctermbg=3   ctermfg=1
hi SpellBad     ctermbg=0   ctermfg=1

" Highlight the status bar
"if has("autocmd")
  "autocmd InsertEnter * hi StatusLine ctermfg=235 ctermbg=2
  ""autocmd InsertLeave * hi StatusLine ctermbg=240 ctermfg=12
  "autocmd InsertLeave * hi StatusLine ctermfg=12 ctermbg=11
"endif

highlight ExtraWhitespace ctermbg=1 guibg=red

"hi CursorColumn cterm=none ctermbg=darkgray ctermfg=white guibg=darkgray guifg=white
"hi ColorColumn ctermbg=darkgray guibg=darkgray
"call matchadd('ColorColumn', '\%81v', 100) "set column nr

" Hightlight text over 80 chars
"highlight OverLength ctermbg=red ctermfg=white guibg=#592929
"match OverLength /\%>80v.\+/

" }}}
" Interface {{{

" Line numbers
set number

" Use relative line numbers
if exists("&relativenumber")
  set relativenumber
  au BufReadPost * set relativenumber
endif

" Allow backspace in insert mode
set backspace=indent,eol,start

" Buffers can exist in the background
set hidden

" Height of the command bar
set cmdheight=1

" Show incomplete commands
set showcmd

" Hide current mode
set noshowmode

" Disable cursor blink (not working?)
set gcr=a:blinkon0

" Show matching brackets when text indicator is over them
set showmatch
" How many tenths of a second to blink when matching brackets
set mat=2

" Beeps and flash
"set noerrorbells
set visualbell
"set t_vb=

"set ttimeout
"set ttimeoutlen=100

if has("mouse")
  set mouse=a
endif

" Don't redraw while executing macros
set lazyredraw

" Shorter messages
set shortmess=atI

" Set the window title
set title

" Always show current position
set ruler
"set rulerformat=%l,%c%V%=%P

" Always show the status line
set laststatus=2

" }}}
" Spacing {{{

set autoindent
"set smartindent
"set smarttab

"set shiftwidth=2
"set softtabstop=2
set tabstop=2

" Use spaces instead of tabs
"set expandtab

" Display invisible characters
set list listchars=tab:▸\ ,trail:·,extends:❯,precedes:❮,nbsp:_,eol:¬

" Do no wrap lines
set nowrap

" Wrap lines at convenient points
set linebreak

" Linebreak on 500 characters
set tw=500

" }}}
" Folding {{{

" Add a bit extra margin to the left
"set foldcolumn=1

set foldmethod=indent
set foldnestmax=3
set nofoldenable

" }}}
" Scrolling {{{

" Start scrolling before the window border
if !&scrolloff
  set scrolloff=8
endif

if !&sidescrolloff
  set sidescrolloff=16
endif

if !&sidescroll
  set sidescroll=1
endif

"set display+=lastline

" }}}
" Search {{{

set gdefault

" Highlight search results
set hlsearch
" Search act like in modern browsers
set incsearch

" Ignore case when searching
set ignorecase
" Try to be smart about cases
set smartcase

" Turn magic on for regular expressions
set magic

" }}}
" Misc {{{

set esckeys

set binary
set noeol

set modeline
set modelines=4

" Enable per-directory .vimrc files and disable unsafe commands in them
set exrc
set secure

"set complete-=i
set nrformats-=octal

set nostartofline

if has("autocmd")
  " Auto reload .vimrc
  "autocmd BufWritePost .vimrc source $MYVIMRC
  "autocmd! BufWritePost .vimrc source %
  augroup reload_vimrc
    autocmd!
    autocmd bufwritepost $MYVIMRC nested source $MYVIMRC
  augroup END

  " Restore cursor position
  augroup resCur
    autocmd!
    autocmd BufWinEnter * call ResCur()
  augroup END

  " Treat .json files as .js
  autocmd BufNewFile,BufRead *.json setfiletype json syntax=javascript

  " Treat .md files as Markdown
  autocmd BufNewFile,BufRead *.md setlocal filetype=markdown

  " Highlight trailing witespaces in red
  match ExtraWhitespace /\s\+$/
  autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
  autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
  autocmd InsertLeave * match ExtraWhitespace /\s\+$/
  autocmd BufWinLeave * call clearmatches()
endif

function! ResCur()
  if line("'\"") <= line("$")
    normal! g`"
    return 1
  endif
endfunction

" }}}
" Key maps {{{

" Change leader to a comma instead of backslash
let mapleader=","
let g:mapleader=","

" Save a file as root (,W)
noremap <leader>W :w !sudo tee % > /dev/null<CR>

" Git commands
map <leader>b :Gblame<cr>
map <leader>l :!clear && git log -p %<cr>
map <leader>d :!clear && git diff %<cr>

" }}}

" Load custom settings
runtime settings.vim
