" ~/.vimrc
"
" github.com/mathiasbynens/dotfiles/blob/master/.vimrc
" github.com/tpope/vim-sensible/blob/master/plugin/sensible.vim"

set nocompatible

" Initialization ------------------------------------------------------

" Autoload plugins
runtime bundle/pathogen/autoload/pathogen.vim
call pathogen#infect()
call pathogen#helptags()

if has('autocmd')
  filetype plugin indent on
endif

" Load matchit.vim, but only if the user hasn't installed a newer version.
if !exists('g:loaded_matchit') && findfile('plugin/matchit.vim', &rtp) ==# ''
  runtime! macros/matchit.vim
endif

" General ---------------------------------------------------------------------

set encoding=utf-8

" Store :cmdline history
if &history < 1000
  set history=1000
endif

" Reload files changed from the outside
set autoread

"if has('path_extra')
""  setglobal tags-=./tags tags-=./tags; tags^=./tags;
"endif

if &shell =~# 'fish$'
  set shell=/bin/bash
endif

if &tabpagemax < 50
  set tabpagemax=50
endif

if !empty(&viminfo)
  set viminfo^=!
endif

" Use Unix as the standard file type
set ffs=unix,dos,mac

" Do not capture all global options
set sessionoptions-=options

" Delete comment character when joining commented lines
if v:version > 703 || v:version == 703 && has("patch541")
  set formatoptions+=j
endif

" Fast terminal connection
set ttyfast

" Bindings --------------------------------------------------------------------

" Change leader to a comma instead of backslash
let mapleader=","
let g:mapleader=","

" Save a file as root (,W)
noremap <leader>W :w !sudo tee % > /dev/null<CR>

" User interface --------------------------------------------------------------

let $LANG='en'
set langmenu=en
source $VIMRUNTIME/delmenu.vim
source $VIMRUNTIME/menu.vim

" Line numbers
set number

" Use relative line numbers
if exists("&relativenumber")
  set relativenumber
  au BufReadPost * set relativenumber
endif

" Allow backspace in insert mode
set backspace=indent,eol,start

" Buffers can exist in the background
set hidden

" Always show current position
set ruler

" Height of the command bar
set cmdheight=1

" Show incomplete commands
set showcmd

" Hide current mode
set noshowmode

" Disable cursor blink
set gcr=a:blinkon0

" Show matching brackets when text indicator is over them
set showmatch
" How many tenths of a second to blink when matching brackets
set mat=2

" Beeps and flash
set visualbell
set noerrorbells
"set t_vb=

"set ttimeout
"set ttimeoutlen=100

" Add a bit extra margin to the left
set foldcolumn=1

if has("mouse")
  set mouse=a
endif

" Don't redraw while executing macros
set lazyredraw

" Shorten messages
set shortmess=atI

" Set the window title
set title

" Theming ---------------------------------------------------------------------

" Enable syntax highlighting
if has('syntax') && !exists('g:syntax_on')
  syntax enable
endif

"set term=xterm-256color

set term=screen-256color
" Disable BCE (Background Color Erase)
"if &term =~ '256color'
"  set t_ut=
"endif

if has('gui_running')
  set background=light
  set t_Co=256
else
  set background=dark
endif

try
  "let g:solarized_termtrans=1
  "let g:solarized_termcolors=256
  let g:solarized_contrast="high"
  "let g:solarized_visibility="normal"
  colorscheme solarized
catch
  colorscheme torte
endtry

" Allow color schemes to do bright colors without forcing bold.
if &t_Co == 8 && $TERM !~# '^linux\|^Eterm'
  set t_Co=16
endif

set synmaxcol=800
"set textwidth=80

if exists('+colorcolumn')
  set colorcolumn=80
  "let &colorcolumn=join(range(1,80),",")
endif

set cursorline
"hi CursorColumn cterm=none ctermbg=darkgray ctermfg=white guibg=darkgray guifg=white
"hi ColorColumn ctermbg=darkgray guibg=darkgray
"call matchadd('ColorColumn', '\%81v', 100) "set column nr

" Hightlight text over 80 chars
"highlight OverLength ctermbg=red ctermfg=white guibg=#592929
"match OverLength /\%>80v.\+/

" Turn off swap files ---------------------------------------------------------

set noswapfile
set nobackup
set nowb

" Persistent undo -------------------------------------------------------------

" Keep undo history across sessions, by storing in file.
if has('persistent_undo') && !isdirectory(expand('~').'/.vim/backups')
  silent !mkdir ~/.vim/backups > /dev/null 2>&1
  set undodir=~/.vim/backups
  set undofile
endif

" Spacing ---------------------------------------------------------------------

set autoindent
"set smartindent
"set smarttab

"set shiftwidth=2
"set softtabstop=2
set tabstop=2

" Use spaces instead of tabs
"set expandtab

" Display invisible characters
" tab:>\ ,trail:-,extends:>,precedes:<,nbsp:+
if &listchars ==# 'eol:$'
  set list listchars=tab:▸\ ,trail:·,extends:❯,precedes:❮,nbsp:_,eol:¬
endif

" Do no wrap lines
set nowrap

" Wrap lines at convenient points
set linebreak

" Linebreak on 500 characters
set tw=500

" Folds -----------------------------------------------------------------------

set foldmethod=indent
set foldnestmax=3
set nofoldenable

" Completion ------------------------------------------------------------------

" Complete up to the point of ambiguity
set wildmode=list:longest
" Display completion options
set wildmenu
set wildignore=*.o,*~
set wildignore+=*.git/*,*/.DS_Store

" Scrolling -------------------------------------------------------------------

" Start scrolling before the window border
if !&scrolloff
  set scrolloff=8
endif

if !&sidescrolloff
  set sidescrolloff=16
endif

if !&sidescroll
  set sidescroll=1
endif

"set display+=lastline

" Search ----------------------------------------------------------------------

set gdefault

" Highlight search results
set hlsearch
" Search act like in modern browsers
set incsearch

" Ignore case when searching
set ignorecase
" Try to be smart about cases
set smartcase

" Turn magic on for regular expressions
set magic

" Misc ------------------------------------------------------------------------

set clipboard=unnamed

set esckeys

set binary
set noeol

set modeline
set modelines=4

" Enable per-directory .vimrc files and disable unsafe commands in them
set exrc
set secure

"set complete-=i
set nrformats-=octal

set nostartofline

if has("autocmd")
  " Auto reload .vimrc
  "autocmd BufWritePost .vimrc source $MYVIMRC
  " Enable file type detection
  filetype on
  " Treat .json files as .js
  autocmd BufNewFile,BufRead *.json setfiletype json syntax=javascript
  " Treat .md files as Markdown
  autocmd BufNewFile,BufRead *.md setlocal filetype=markdown
endif

" Status line -----------------------------------------------------------------

" Always show the status line
set laststatus=2

" Format the status line
"set statusline=\ %{HasPaste()}%F%m%r%h\ %w\ \ CWD:\ %r%{getcwd()}%h\ \ \ Line:\ %l

" Syntastic messages
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

" Load custom and plugin settings ---------------------------------------------

"source ~/.vim/settings.vim
runtime settings.vim
