" ~/.vimrc
" vim: foldenable foldmethod=marker

" github.com/mathiasbynens/dotfiles/blob/master/.vimrc
" github.com/tpope/vim-sensible/blob/master/plugin/sensible.vim"

set nocompatible

" Initialization {{{

filetype off

let g:pathogen_disabled = []
"call add(g:pathogen_disabled, 'syntastic')

" Add pathogen to runtime
runtime bundle/pathogen/autoload/pathogen.vim
" Autoload plugins
call pathogen#infect()
" Generate plugin help tags
call pathogen#helptags()

filetype plugin indent on

" Load matchit.vim, but only if the user hasn't installed a newer version.
if !exists('g:loaded_matchit') && findfile('plugin/matchit.vim', &rtp) ==# ''
  runtime macros/matchit.vim
endif

" }}}
" General {{{

set encoding=utf-8

if &history < 1000
  set history=1000
endif

" Reload unmodified files when changes are detected outside
set autoread

"if has('path_extra')
""  setglobal tags-=./tags tags-=./tags; tags^=./tags;
"endif

"if &shell =~# 'fish$'
"  set shell=/bin/bash
"endif

if &tabpagemax < 50
  set tabpagemax=50
endif

" Use Unix as the standard file type
set ffs=unix,dos,mac

" Use system clipboard
set clipboard=unnamed

" Fast terminal connection
set ttyfast

" Delete comment character when joining commented lines
if v:version > 703 || v:version == 703 && has("patch541")
  set formatoptions+=j
endif

" Tell vim to remember certain things when we exit
"  '10  :  marks will be remembered for up to 10 previously edited files
"  "100 :  will save up to 100 lines for each register
"  :20  :  up to 20 lines of command-line history will be remembered
"  %    :  saves and restores the buffer list
"  n... :  where to save the viminfo files
"set viminfo='10,\"100,:20,%,n~/.viminfo

if !empty(&viminfo)
  set viminfo^=!
endif

" Do not capture all global options
set sessionoptions-=options

set noswapfile
set nobackup
set nowb

" Keep undo history across sessions, by storing in file.
if has('persistent_undo') && !isdirectory(expand('~').'/.vim/backups')
  silent !mkdir ~/.vim/backups > /dev/null 2>&1
  set undodir=~/.vim/backups
  set undofile
endif

"set binary
"set noeol

" Number of lines checked for set commands (not safe)
set modeline
set modelines=2

" Enable per-directory .vimrc files and disable unsafe commands in them
set exrc
set secure

"set complete-=i
set nrformats-=octal

set nostartofline

" Buffers can exist in the background
set hidden

" }}}
" Theming {{{

"set term=xterm-256color
set term=screen-256color

" Disable BCE (Background Color Erase)
"if &term =~ '256color'
"  set t_ut=
"endif

if has('gui_running')
  set background=light
else
  set background=dark
endif

try
  "let base16colorspace=256
  colorscheme base16-ocean
catch
  colorscheme torte
endtry

" Allow color schemes to do bright colors without forcing bold.
if &t_Co == 8 && $TERM !~# '^linux\|^Eterm'
  set t_Co=16
endif

" Enable syntax highlighting
if has('syntax') && !exists('g:syntax_on')
  syntax enable
endif

set synmaxcol=800
"set textwidth=80

set cursorline

if exists('+colorcolumn')
  set colorcolumn=80
  "let &colorcolumn=join(range(1,80),",")
endif

" }}}
" Colors {{{

" Hide line number background
"highlight LineNr ctermbg=none guibg=none

" Custom colors
"hi clear SignColumn
hi VertSplit ctermbg=10
hi ColorColumn ctermbg=10

hi LineNr ctermbg=10
hi CursorLineNr ctermfg=12
"hi CursorLine ctermbg=10

" Not supported by Terminal.app
" See settings/terminal.vim
" hi Cursor ctermfg=1 ctermbg=7

hi IncSearch ctermfg=10 ctermbg=3
hi Search ctermfg=0 ctermbg=9
hi Visual ctermfg=10 ctermbg=3

"hi Pmenu        ctermbg=240 ctermfg=12
"hi PmenuSel     ctermbg=3   ctermfg=1
"hi SpellBad ctermfg=1 ctermbg=0

hi ExtraWhitespace ctermbg=1 guibg=red

" Customize invisible characters color
hi NonText ctermfg=11
hi SpecialKey ctermfg=11

"hi CursorColumn cterm=none ctermbg=darkgray ctermfg=white guibg=darkgray guifg=white
"hi ColorColumn ctermbg=darkgray guibg=darkgray
"call matchadd('ColorColumn', '\%81v', 100) "set column nr

" Hightlight text over 80 chars
"highlight OverLength ctermbg=red ctermfg=white guibg=#592929
"match OverLength /\%>80v.\+/

" }}}
" Interface {{{

" Line numbers
set number

" Use relative line numbers
if exists("&relativenumber")
  set relativenumber
  au BufReadPost * set relativenumber
endif

" Always show the status line
set laststatus=2


" Height of the command bar
set cmdheight=1

" Show incomplete commands
set showcmd

" Hide current mode
set noshowmode

" Disable cursor blinking
"set guicursor=a:blinkon0

" Do not show matching brackets when text indicator is over them
set noshowmatch
" How many tenths of a second to blink when matching brackets
"set mat=2

" HTML brackets
set matchpairs+=<:>

" Beeps and flash
"set noerrorbells
set visualbell
"set t_vb=

" Recognize escape immediately
set esckeys

set ttimeout
"set timeoutlen=1000 ttimeoutlen=0
set timeoutlen=1

" Mode switch fix?
" https://powerline.readthedocs.org/en/latest/tipstricks.html#vim
if !has('gui_running')
  set ttimeoutlen=10
  augroup FastEscape
    au!
    au InsertEnter * set timeoutlen=0
    au InsertLeave * set timeoutlen=1000
  augroup END
endif

"if has("mouse")
  set mouse=a
"endif

" Don't redraw while executing macros
set lazyredraw

" Shorter messages
set shortmess=atI

" Set the window title
set title

" Always show current position (overwriten by statusline)
set ruler
"set rulerformat=%l,%c%V%=%P

" Natural new split focus
set splitbelow
set splitright

" }}}
" Spacing {{{

if !exists("g:loaded_sleuth")
  " Identation
  set shiftwidth=2
  set softtabstop=2
  set tabstop=2
endif

" Use spaces instead of tabs
set expandtab

set autoindent
set smartindent
set smarttab

" Show invisible characters
" Highlight: NonText and SpecialKey
set list listchars=tab:▸\ ,trail:·,extends:❯,precedes:❮,nbsp:_,eol:¬

" Don't wrap lines
set nowrap

" Wrap lines at convenient points
set linebreak

" Linebreak on 500 characters
set tw=500

" }}}
" Folding {{{

" Add a bit extra margin to the left
"set foldcolumn=1

set foldmethod=indent
set foldnestmax=3
set nofoldenable

" }}}
" Scrolling {{{

" Start scrolling before the window border
if !&scrolloff
  set scrolloff=3
endif

if !&sidescrolloff
  set sidescrolloff=5
endif

if !&sidescroll
  set sidescroll=1
endif

"set display+=lastline

" }}}
" Search {{{

set gdefault

" Highlight search results
set hlsearch
" Search act like in modern browsers
set incsearch

" Ignore case when searching
set ignorecase
" Try to be smart about cases
set smartcase

" Turn magic on for regular expressions
set magic

" }}}
" Automatic commands {{{

if has("autocmd")
  " Auto reload .vimrc
  au BufWritePost .vimrc source $MYVIMRC
  "au! BufWritePost .vimrc source %
  "augroup reload_vimrc
  "  au!
  "  au BufWritePost $MYVIMRC nested source $MYVIMRC
  "augroup END

  " Treat .json files as .js
  au BufNewFile,BufRead *.json setfiletype json syntax=javascript

  " Treat .md files as Markdown
  au BufNewFile,BufRead *.md setlocal filetype=markdown

  " Treat .twig as .php (or htmljinja)
  au BufNewFile,BufRead *.twig set filetype=php

  " Highlight trailing witespaces in red
  match ExtraWhitespace /\s\+$/
  au BufWinEnter * match ExtraWhitespace /\s\+$/
  au InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
  au InsertLeave * match ExtraWhitespace /\s\+$/
  au BufWinLeave * call clearmatches()

  " Show cursor line on active window only
  au WinEnter * set cursorline
  au WinLeave * set nocursorline

  augroup resCur
    au!
    au BufWinEnter * call ResCur()
  augroup END
endif

" Restore cursor position
function! ResCur()
  if line("'\"") > 0 && line("'\"") <= line("$")
    normal! g`"
    return 1
  endif
endfunction

" }}}
" Key maps {{{

" Allow backspace in insert mode
set backspace=indent,eol,start

" Change leader to a comma instead of backslash
let mapleader=","
let g:mapleader=","

" Nope
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>

" Use virtual columns for vertical movements
nnoremap j gj
nnoremap k gk

" Quicker split navigation
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Clear highlighted search results
map <leader><Space> :noh<CR>

" Save a file as root (,W)
noremap <leader>W :w !sudo tee % > /dev/null<CR>

" Git commands
map <leader>b :Gblame<cr>
map <leader>l :!clear && git log -p %<CR>
map <leader>d :!clear && git diff %<CR>

" Sort css properties
nnoremap <leader>S ?{<CR>jV/^\s*\}?$<CR>k:sort<CR>:noh<CR>

" Open .vimrc in a new split
nnoremap <leader>rc <C-w><C-v><C-l>:e $MYVIMRC<CR>

" }}}

" Load custom settings
runtime settings.vim
