#!/usr/bin/env sh
# Ivan c00kiemon5ter V Kanakarakis (http://c00kiemon5ter.github.com)
# for noncopyright information see UNLICENSE file http://unlicense.org/ .
#
# wrapper around iii.sh
# spawns iii.sh in a tmux session named IRC with the channel as title
# accepts all env vars iii.sh accepts plus 't' which sets the terminal

iii="~/irc/bin/iii"

## collect options from env - all opts to iii.sh should be set here
opts="TERM="${t:-rxvt-unicode}" m="$m" h="$h" p="$p" n="$n" l="$l" i="$i" s="$s" c="$c""
tmux_opts="-n \'${c:-$s}\'"

## spawn a new tmux window named <channel> in a tmux session named IRC
if ! tmux list-sessions | awk -v r=1 '$1 == "IRC:" { exit r=0 } END { exit r }'
then
  tmux_cmd="new-session"
  tmux_opts="-s IRC $tmux_opts"
  [ -n "$TMUX" ] && tmux_opts="-d $tmux_opts"
elif ! tmux list-windows -t IRC | awk -v r=1 -v m="${c:-$s}" '$2 ~ "^"m"[*!-]*$" { exit r=0 } END { exit r }'
then
  tmux_cmd="new-window"
  tmux_opts="-d -t IRC $tmux_opts"
fi

if [ -n "$tmux_cmd" ]
then
  echo $tmux_cmd "$tmux_opts" "\'$opts $iii\'"
  tmux $tmux_cmd "$tmux_opts" "\'$opts $iii\'"
fi
