#!/usr/bin/env bash
# Ivan c00kiemon5ter V Kanakarakis (http://c00kiemon5ter.github.com)
# for noncopyright information see UNLICENSE file http://unlicense.org/ .
#
# wrapper around iii.sh
# spawns iii.sh in a tmux session named IRC with the channel as title
# accepts all env vars iii.sh accepts plus 't' which sets the terminal

iii="~/irc/bin/iii"

in_tmux() {
  [[ -n "$TMUX" ]]
}

has_session() {
  local session="$1"
  tmux list-sessions | awk -v r=1 -v m="$session" '$1 == m":" { exit r=0 } END { exit r }'
}

has_window() {
  local session="$1" window="$2"
  tmux list-windows -t "$session" | awk -v r=1 -v m="$window" '$2 ~ "^"m"[#*!-]*$" { exit r=0 } END { exit r }'
}

go_to_window() {
  local session="$1" window="$2" cmd="attach-session"
  in_tmux && cmd="switch-client"
  tmux "$cmd" -t "$session" \; select-window -t "$session":"$window"
}

# Session name
session="IRC"
# Window name cannot contain dots
window="${c:-$n}" # c:-$s
window=${window//./․} # One dot leader (U+2024)
# window=${window#irc.} # window=${window%.net}
# window=${window//./\\.}

## collect options from env - all opts to iii.sh should be set here
opts="m="$m" h="$h" p="$p" n="$n" l="$l" i="$i" s="$s" c="$c""
# TERM="${t:-rxvt-unicode}"

## spawn a new tmux window named <channel> in a tmux session named IRC
if ! has_session "$session"
then
  if in_tmux
  then
    tmux new-session -d -s "$session" -n "$window" "$opts $iii"
    go_to_window "$session" "$window"
  else
    tmux new-session -s "$session" -n "$window" "$opts $iii"
  fi
elif ! has_window "$session" "$window"
then
  tmux new-window -t "$session" -n "$window" -d "$opts $iii"
  if in_tmux
  then
    go_to_window "$session" "$window"
  fi
else
  go_to_window "$session" "$window"
fi

# #TERM="${t:-rxvt-unicode}"
# opts="m=$m h=$h p=$p n=$n l=$l i=$i s=$s c=$c"
# tmux_opts="-n \"${c:-$s}\""
# if ! tmux list-sessions | awk -v r=1 '$1 == "IRC:" { exit r=0 } END { exit r }'
# then
#   tmux_cmd="new-session"
#   in_tmux && tmux_opts="-d $tmux_opts"
#   tmux_opts="$tmux_opts -s IRC"
# elif ! tmux list-windows -t IRC | awk -v r=1 -v m="${c:-$s}" '$2 ~ "^"m"[*!-]*$" { exit r=0 } END { exit r }'
# then
#   tmux_cmd="new-window"
#   tmux_opts="-d $tmux_opts -t IRC"
# fi

# tmux $tmux_cmd "$tmux_opts" "\"$opts $iii\""
