---
- name: "Register {{ item.key }} symlinks target paths"
  set_fact:
    dot_target: "{{ item }}"
    dot_find_cmd: "find {{ item.value.src + item.value.pattern }} {{ dot_find_options }}"

- include: backup.yml
  when: dot_backup_enable

# # Source relative to dot_root, destination relative to dot_home  | basename?
- name: "Create {{ dot_target.key }} symlinks in {{ dot_target.value.dest }}"
  file:
    src: "{{ item }}"
    dest: "{{ dot_target.value.dest }}/{{ dot_target.value.prefix }}{{ item | basename }}"
    # src: "{{ item.value.src }}/{{ item.src | default(item) }}"
    # dest: "{{ item.value.dest }}/{{ item.value.prefix | default('') }}{{ item.dest | default(item) }}"
    state: link
  with_lines: "{{ dot_find_cmd }}"
  register: items

- name: "Log symlinks"
  vars:
    dest: "{{ dot_target.value.dest }}/{{ dot_target.value.prefix }}{{ item | basename }}"
  debug: var=dest
  with_items: "{{ items.results | map(attribute='item') | list }}"
  when: dot_log_enable
  # verbosity: 1
