---
- name: "Register {{ item.key }} symlinks target paths"
  set_fact:
    dot_target: "{{ item }}"
    dot_find_cmd: "find {{ item.value._src + item.value.pattern }} {{ dot_find_options }}"

- name: "Retrieve {{ dot_target.key }} files stat"
  stat:
    path: "{{ dot_target.value._dest }}/{{ dot_target.value.prefix }}{{ item | basename }}"
    follow: false
  with_lines: "{{ dot_find_cmd }}"
  register: dot_stat
  when: dot_backup_files

- name: "Backup existing {{ dot_target.key }} files"
  vars:
    dest: "{{ dot_target.value._dest }}/{{ dot_target.value.prefix }}{{ item.item | basename }}"
    ext: "{{ dot_backup_ext | default(ansible_date_time.date + '@' + ansible_date_time.time + '~') }}"
    # ext: "{{ dot_backup_ext | default(item.stat.mtime | datetime) }}~"
  command: "mv {{ dest }} {{ dest }}.{{ ext }}"
  # TODO: -rw-r--r-- ?
  args:
    creates: "{{ dest }}.{{ ext }}"
  with_items: "{{ dot_stat.results }}"
  when: dot_backup_enable and item.stat.exists and
    ((dot_backup_files and not item.stat.islnk) or
    (dot_backup_symlinks and item.stat.islnk and item.stat.lnk_source != item.item))
  no_log: "{{ dot_backup_no_log }}"

# # Source relative to dot_root, destination relative to dot_home  | basename?
- name: "Create {{ dot_target.key }} symlinks in {{ dot_target.value._dest }}"
  file:
    src: "{{ item }}"
    dest: "{{ dot_target.value._dest }}/{{ dot_target.value.prefix }}{{ item | basename }}"
    # src: "{{ item.value._src }}/{{ item._src | default(item) }}"
    # dest: "{{ item.value._dest }}/{{ item.value.prefix | default('') }}{{ item._dest | default(item) }}"
    state: link
  with_lines: "{{ dot_find_cmd }}"
  # with_items: "{{ files }}"
  register: items

# - debug: var=dot_files

# - name: Register sources
#   set_fact:
#     dot_files: "{{ dot_files | combine({item.key: item.value}) }}"
#     # "{{ dot_home }}{% if item.value._dest | default(false) %}/{{ item.value._dest }}{% endif %}"
#   # debug:
#   #   msg:
#   #     src: "{{ dot_root }}{% if item.value._src | default(false) %}/{{ item.value._src }}{% else %}/roles/{{ item.key }}/files{% endif %}"
#   #     dest: "{{ dot_home }}{% if item.value._dest | default(false) %}/{{ item.value._dest }}{% endif %}"
#   #     prefix: "{{ item.value.prefix | default('') }}"
#   with_dict: "{{ symlinks }}"
#   # with_subelements:
#   #   - "{{ dot_files.symlinks }}"
#   #   - src
#   #   - flags:
#   #     skip_missing: true
#   register: files

  # with_items: "{{ files.results }}"

# - name: Create symlinks
#   debug:
#     msg: "{{ item }}"
#   with_items: "{{ items }}"

# - name: "Log {{ dot_target.key }} symlinks"
#   debug:
#     msg: " {{ dot_target.value._dest }}/{{ dot_target.value.prefix }}{{ item | basename }}"
#   with_items: "{{ items.results | map(attribute='item') | list }}"
#   when: dot_log_enable
#   # verbosity: 1
