---
# - name: "Transform {{ dot_dict }}"
#   set_fact:
#     "{{ dot_dict }}": >
#       {{ hostvars[inventory_hostname][dot_dict] | combine({
#         item.key: {
#           'src': dot_root + ('/' + item.value.src if item.value.src | default(false) else '/' + dot_roles_dir + '/' + item.key + '/' + dot_dir if dot_dir and dot_roles_dir else 'nope'),
#           'dest': dot_home + ('/' + item.value.dest if item.value.dest | default(false) else ''),
#           'prefix': item.value.prefix | default(''),
#           'pattern': item.value.pattern | default(dot_find_pattern)
#         }
#       }) }}
#   with_dict: "{{ hostvars[inventory_hostname][dot_dict] }}"

# - debug:
#     msg: "{{ item }}"
#   with_dict: "{{ dot_files[dot_dict_key] }}"

- name: "Construct {{ dot_dir_name | default('directory') }} dict"
  set_fact:
    dot_files: >
      {{ dot_files | combine({
        dot_dict_key: {
          item.key: {
            '_src': dot_root + ('/' + item.value.src if item.value.src | default(false) else '/' + dot_roles_dir + '/' + item.key + '/' + dot_dir_name if dot_dir_name and dot_roles_dir else item.key),
            '_dest': dot_home + ('/' + item.value.dest if item.value.dest | default(false) else ''),
            'prefix': item.value.prefix | default(''),
            'pattern': item.value.pattern | default(dot_find_pattern)
          }
        }
      }, recursive=true) }}
  with_dict: "{{ dot_files[dot_dict_key] }}"

# - debug: var=dot_files[dot_dict_key]
#   when: dot_log_enable

# - name: "Gather facts about {{ dot_dir }}"
#   set_fact:
#     directory: "{{ item.key }}"
#     source: "{{ item.value.src }}"
#     destination: "{{ item.value.dest }}"
#     prefix: "{{ item.value.prefix }}"
#     dot_find: "find {{ item.value.src + item.value.pattern }} {{ dot_find_options }}"
#   with_dict: "{{ hostvars[inventory_hostname][dot_dict] }}"

# - name: Check source path
#   assert:
#     that:
#       - "source != inventory_dir"

# - name: Ensure source and destination directories exist
#   file:
#     path: "{{ item }}"
#     state: directory
#     follow: true
#   with_items:
#     - "{{ source }}"
#     - "{{ destination }}"
