---
enabled: "{{ .features.ai }}"
packages:
  # TODO: only if installed via brew
  # if [ "$(claude config set --global autoUpdates false)" = true ]; then
  #   claude config set --global autoUpdates false
  # fi
  claude-code:
    enabled: '{{ eq .osIDLike "arch" "darwin" "fedora" "windows" }}'
    nameOverwrite:
      npm: "@anthropic-ai/claude-code"
      windows: Anthropic.Claude
    type: '{{ eq .osIDLike "arch" | ternary "aur" (eq .osIDLike "darwin" "fedora" | ternary "cask" "npm") }}'
  # WARN: requires recent node and no custom config location
  claude-monitor:
    type: uv
  claude:
    enabled: '{{ and .gui (eq .osIDLike "darwin" "windows") }}'
    nameOverwrite:
      windows: Anthropic.ClaudeCode
    type: '{{ eq .osIDLike "darwin" | ternary "cask" nil }}'
  cc-sessions:
    enabled: '{{ eq .osIDLike "arch" "darwin" "fedora" }}'
    name: github:chronologos/cc-sessions
    type: mise
  beads:
    enabled: '{{ eq .osIDLike "arch" "darwin" "fedora" }}'
    # npm: "@beads/bd"
    type: brew
