---
enabled: "{{ .features.ai }}"
packages:
  # TODO: only if installed via brew
  # if [ "$(claude config set --global autoUpdates false)" = true ]; then
  #   claude config set --global autoUpdates false
  # fi
  claude-code:
    enabled: '{{ eq .osIDLike "arch" "darwin" "fedora" "windows" }}'
    nameOverwrite:
      npm: "@anthropic-ai/claude-code"
      windows: Anthropic.ClaudeCode
    type: '{{ eq .osIDLike "arch" | ternary "aur"
      (eq .osIDLike "darwin" "fedora" | ternary "cask" "npm") }}'

  claude-desktop:
    enabled: '{{ and .gui (eq .osIDLike "darwin" "fedora" "windows") }}'
    nameOverwrite:
      cask: claude
      mise: github:aaddrick/claude-desktop-debian
      windows: Anthropic.Claude
    type: '{{ eq .osIDLike "darwin" | ternary "cask"
      (eq .osIDLike "fedora" | ternary "mise" nil) }}'
    # before_script: |
    #   if command -v dnf >/dev/null || command -v rpm-ostree >/dev/null; then
    #     # run sudo curl -fsSL https://aaddrick.github.io/claude-desktop-debian/rpm/claude-desktop.repo -o /etc/yum.repos.d/claude-desktop.repo
    #     # run rpm-ostree install claude-desktop
    #
    #     run mise use -g github:aaddrick/claude-desktop-debian
    #     run rpm-ostree install "$(which claude-desktop-1.3883.0-2.0.3-1.x86_64.rpm)"
    #
    #     # run mise use -g rpm:aaddrick/claude-desktop-debian
    #   fi
    after_script: |
      if command -v claude-desktop >/dev/null; then
        claude-desktop --doctor
      fi
    # WARN: requires recent node and no custom config location
  claude-monitor:
    type: uv
  cc-sessions:
    enabled: '{{ eq .osIDLike "arch" "darwin" "fedora" }}'
    name: github:chronologos/cc-sessions
    type: mise
  # beads:
  #   enabled: '{{ eq .osIDLike "arch" "darwin" "fedora" }}'
  #   nameOverwrite:
  #     npm: "@beads/bd"
  #   type: npm
  # bv:
  # dolt:
  #   enabled: '{{ eq .osIDLike "arch" "darwin" "fedora" }}'
  #   type: brew
