---
# Source relative to dot_root, destination relative to dot_home |basename?
- name: "Create {{ role_dir }} symlinks in {{ destination }}"
  file:
    src: "{{ item }}"
    dest: "{{ destination }}/{{ prefix|default('') }}{{ item|basename }}"
    # src: "{{ source }}/{{ item.src|default(item) }}"
    # dest: "{{ destination }}/{{ prefix|default('') }}{{ item.dest|default(item) }}"
    state: link
  with_lines: "find {{ source }}/* {{ find_options }}"
  # with_items: "{{ files }}"
