---
dependencies:

  - role: pacman-yaourt
    pacman_yaourt_packages:
      - rxvt-unicode
    # when: "ansible_os_family == 'Archlinux'"

  # Requires X
  # - role: packages
  #   packages:
  #     - rxvt-unicode
  #   when: "os in ['Windows']"

  - role: dotfiles
    paths:
      - name: rxvt
        dest: .Xresources.d
