---
dependencies:

  - role: package
    packages: "{{ rxvt_packages }}"

  - role: pacman-yaourt
    pacman_yaourt_packages:
      - rxvt-unicode
    when: ansible_os_family == 'Archlinux'

  - role: dotfiles
    paths:
      - name: rxvt
        dest: .Xresources.d
