---
dependencies:

  - role: homebrew-cask
    homebrew_cask_apps:
      - hammerspoon
    # when: "ansible_os_family == 'Darwin'"

  - role: symlink
    dot_roles_dir: os_roles
    dot_files:
      hammerspoon:
        dest: .hammerspoon
