# Version >= 2.1

# Enable mouse
set-option -g mouse on

bind -T root WheelUpPane   if-shell -F -t = "#{alternate_on}" "send-keys up" "select-pane -t =; copy-mode -e; send-keys -M"
bind -T root WheelDownPane if-shell -F -t = "#{alternate_on}" "send-keys down" "select-pane -t =; send-keys -M"

# Fix wheel up and down and exit copy-mode when scrolling past bottom
# https://github.com/tmux/tmux/issues/145
# bind-key -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"
# bind-key -n WheelDownPane select-pane -t= \; send-keys -M

# set -g @plugin 'nhdaly/tmux-scroll-copy-mode'

# bind -n WheelUpPane   select-pane -t= \; copy-mode -e \; send-keys -M
# bind -n WheelDownPane select-pane -t= \;                 send-keys -M

# https://wiki.archlinux.org/index.php/Tmux#Mouse_scrolling
# set -g terminal-overrides 'xterm*:smcup@:rmcup@'
# bind -T root WheelUpPane   if-shell -F -t = "#{alternate_on}" "send-keys -M" "select-pane -t =; copy-mode -e; send-keys -M"
# bind -T root WheelDownPane if-shell -F -t = "#{alternate_on}" "send-keys -M" "select-pane -t =; send-keys -M"

# bind -n C-WheelUpPane select-pane -t= \; copy-mode -e \; send-keys -M
# bind -t vi-copy    C-WheelUpPane   halfpage-up
# bind -t vi-copy    C-WheelDownPane halfpage-down
# bind -t emacs-copy C-WheelUpPane   halfpage-up
# bind -t emacs-copy C-WheelDownPane halfpage-down

# Mouse without copy mode dragging?
# unbind -n MouseDrag1Pane
# unbind -temacs-copy MouseDrag1Pane
