# Version >= 2.1

# Enable mouse support
set-option -g mouse on

# https://github.com/tmux/tmux/issues/145
# https://wiki.archlinux.org/index.php/Tmux#Mouse_scrolling
# Select the pane, enter copy mode and scroll up (WheelUp)
bind -T root WheelUpPane   if-shell -F -t = "#{alternate_on}" "select-pane -t =; send-keys up" "select-pane -t =; copy-mode -e; send-keys -M"
# Scroll down the pane and exit copy mode when scrolling past bottom (WheelDown)
bind -T root WheelDownPane if-shell -F -t = "#{alternate_on}" "select-pane -t =; send-keys down" "select-pane -t =; send-keys -M"
# Or send arrow keys if the pane is a fullscreen application (alternate_screen: e.g. man, less)

# Faster scroll in copy mode with Ctrl-WheelUp/Down
bind -T root       C-WheelUpPane   select-pane -t =\; copy-mode -e \; send-keys -M
# FIXME: not enough arguments?
bind -t emacs-copy C-WheelUpPane   halfpage-up
bind -t emacs-copy C-WheelDownPane halfpage-down
bind -t vi-copy    C-WheelUpPane   halfpage-up
bind -t vi-copy    C-WheelDownPane halfpage-down

# bind -t emacs-copy C-WheelUpPane   if-shell -F -t = "#{alternate_on}" "select-pane -t =; halfpage-up"

# bind-key -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"
# bind-key -n WheelDownPane select-pane -t= \; send-keys -M

# set -g @plugin 'nhdaly/tmux-scroll-copy-mode'

# bind -n WheelUpPane   select-pane -t= \; copy-mode -e \; send-keys -M
# bind -n WheelDownPane select-pane -t= \;                 send-keys -M

# set -g terminal-overrides 'xterm*:smcup@:rmcup@'
# bind -T root WheelUpPane   if-shell -F -t = "#{alternate_on}" "send-keys -M" "select-pane -t =; copy-mode -e; send-keys -M"
# bind -T root WheelDownPane if-shell -F -t = "#{alternate_on}" "send-keys -M" "select-pane -t =; send-keys -M"

# Mouse without copy mode dragging?
# unbind -n MouseDrag1Pane
# unbind -t emacs-copy MouseDrag1Pane
