---
pip_install: yes
pip_upgrade: yes
pip_state: present
pip_packages: []
pip_base_packages:
  - name: pip
    state: latest
    when: "{{ pip_upgrade }}"
    # extra_args: --upgrade
pip_default_args: "{{ '--user python' if ansible_os_family in ['Darwin'] else '' }}"
python_packages: []
