---
vim_packages:
  - vim

# Vim Plug
# https://github.com/junegunn/vim-plug
vim_plug_url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim_plug_path: .vim/autoload
vim_plug_file: plug.vim

# Run :PlugInstall inside vim
vim_plug_install: yes
# Install plugins even if ~/.vim/plugged already exists
vim_plug_force: no

# Directory where the plugins will be cloned
vim_plugins_path: .vim/plugged

# List of plugins used in templates/plug.vim.j2
# TODO: handle plugin.opts without quotes: function('')
vim_plugins:
  # - itchyny/lightline.vim
  - LEI/vim-statusline
  - chriskempson/base16-vim
  # - whatyouhide/vim-gotham
  - tpope/vim-repeat
  - tpope/vim-surround
  - tpope/vim-endwise
  - tpope/vim-unimpaired
  - tpope/vim-commentary
  - tpope/vim-sleuth
  - tpope/vim-vinegar
  - tpope/vim-fugitive
  - ctrlpvim/ctrlp.vim
  - airblade/vim-gitgutter
  - sjl/gundo.vim
  - scrooloose/syntastic
  - repo: StanAngeloff/php.vim
    opts: { for: php }
  - repo: pangloss/vim-javascript
    opts: { for: javascript }
  - digitaltoad/vim-jade
  - Glench/Vim-Jinja2-Syntax
  - repo: syngan/vim-vimlint
    plug:
      - ynkdir/vim-vimlparser
  - keith/tmux.vim
  - repo: Valloric/YouCompleteMe
    # opts: { do: function('YCMInstall') }
  - repo: SirVer/ultisnips
    plug:
      - honza/vim-snippets
  # - Yggdroot/indentLine
  # - repo: godlygeek/tabular
  #   opts: { on: Tab }
  # - editorconfig/editorconfig-vim
