---
# Use https://github.com/egalpin/apt-vim ?
# Neovim on MacOSX: brew install neovim && pip install neovim
# Use neomake instead of syntastic & dispatch
# & dein as plugin manager?

vim_packages:
  - vim

# Cf. templates/plug.vim.j2
vim_plugins: []
vim_extra_plugins: []
vim_ignore_plugins: []

vim_files:
  - path: "{{ vim_plugins_path }}"
    state: directory
    # follow: true
  - path: "{{ nvim_init }}"
    state: touch
    when: "{{ nvim_install }}"

vim_dir: "{{ dot_home }}/.vim"
vim_rc: "{{ vim_dir }}/vimrc"
vim_extra_config: "{{ vim_dir }}/config.vim"
vim_extras: yes

# 'nvim' in vim_packages or 'neovim' in vim_packages 
nvim_install: "{{ neovim_install | default(false) }}"
nvim_init: "{{ dot_home }}/.vim/init.vim"

# https://github.com/junegunn/vim-plug
vim_plug_url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
# Vim Plug path
vim_plug_file: "{{ vim_dir }}/autoload/plug.vim"
# Runs :PlugInstall inside vim
vim_plug_install: yes
# Install plugins even if ~/.vim/plugged already exists
vim_plug_force: no
# Directory where the plugins will be downloaded
vim_plugins_path: "{{ vim_dir }}/plugged"

# Vim Warning:
# Output is not to a terminal / Input is not from a terminal
# -E -s -V +'source {{ dot_home }}/.vim/plug.vim' < /dev/tty
# "silent" is required or vim hangs on YCM installation
# YCM: ./install.py --tern-completer
vim_plug_cmd: "vim -E -s -u NONE +'source {{ vim_dir }}/plug.vim' -N +'silent PlugInstall{{ '!' if vim_plug_force else '' }}' +qall"

# vim_dein_repo: https://github.com/Shougo/dein.vim
# vim_dein_path: "{{ vim_plugins_path }}/repos/github.com/Shougo/dein.vim"
