---
# command/tokenscope.md:
#   type: file
#   url: https://raw.githubusercontent.com/ramtinJ95/opencode-tokenscope/refs/tags/v1.5.2/command/tokenscope.md

# https://github.com/openai/skills
# https://github.com/anthropics/skills
