---
opencode:
  server:
    hostname: 127.0.0.1 # localhost
    port: 4096
    # WARN: forces binding to 0.0.0.0
    # mdns: true
    # mdnsDomain: opencode.local
    cors:
      # - http://localhost:5173
      # - http://opencode.local
      - https://opencode.test
