---
- name: Install Homebrew Cask apps
  homebrew_cask:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default(homebrew_cask_state) }}"
  environment:
    HOMEBREW_CASK_OPTS: "--appdir={{ homebrew_cask_appdir }}"
  with_items: "{{ cask_apps }}"
  when: homebrew_cask_install

- name: Cleanup Homebrew Cask apps
  shell: brew cask cleanup
  when: homebrew_cask_cleanup
  register: cleanup
  changed_when: "'Nothing to do' not in cleanup.stdout_lines"

- name: Configure Homebrew Cask apps
  command: "./{{ item.0.name }} {{ item.1 }}"
  args:
    chdir: "{{ item.0.bin }}"
  with_subelements:
    - "{{ cask_options }}"
    - opt
  changed_when: false
