---
enabled: "{{ .features.void }}"
packages:
  void:
    nameOverwrite:
      arch: void-bin
      windows: GlassDevtools.Void
    type: '{{ eq .osIDLike "arch" | ternary "aur" (eq .osIDLike "darwin" | ternary "cask" nil) }}'
