---
- name: "Retrieve {{ dot_target.key }} files stat"
  stat:
    path: "{{ dot_target.value.dest }}/{{ dot_target.value.prefix }}{{ item | basename }}"
    # follow: false
  # with_lines: "{{ dot_find }}"
  with_items: "{{ dot_source.files | map(attribute='path') | list }}"
  register: dot_stat

- name: "Backup existing {{ dot_target.key }} files"
  vars:
    dest: "{{ dot_target.value.dest }}/{{ dot_target.value.prefix }}{{ item.item | basename }}"
    ext: "{{ dot_backup_ext | default(ansible_date_time.date + '@' + ansible_date_time.time + '~') }}"
    # ext: "{{ dot_backup_ext | default(item.stat.mtime | datetime) }}~"
  command: "mv {{ dest }} {{ dest }}.{{ ext }}"
  # TODO: -rw-r--r-- ?
  args:
    creates: "{{ dest }}.{{ ext }}"
  with_items: "{{ dot_stat.results }}"
  when: item.stat.exists and
    ((dot_backup_files and not item.stat.islnk) or
    (dot_backup_symlinks and item.stat.islnk and item.stat.lnk_source != item.item))
  no_log: "{{ dot_backup_no_log }}"

