---
- name: "Register {{ item.key }} symlinks target paths"
  set_fact:
    dot_target: "{{ item }}"
    # dot_find: "find {{ item.value.src + item.value.pattern }} {{ dot_find_options }}"

- name: "Find {{ item.value.src + item.value.pattern }} files"
  # shell: "find {{ item.value.src + '/' + item.value.pattern }} {{ dot_find_options }}"
  find:
    # contains:
    file_type: file
    hidden: yes
    path: "{{ item.value.src }}"
    pattern: "{{ item.value.pattern }}"
    recurse: no
  register: dot_files_items
  # changed_when: no # not dot_items.stdout_lines | length > 0

- name: "Find {{ item.value.src + item.value.pattern }} directories"
  # shell: "find {{ item.value.src + '/' + item.value.pattern }} {{ dot_find_options }}"
  find:
    # contains:
    file_type: directory
    hidden: yes
    path: "{{ item.value.src }}"
    pattern: "{{ item.value.pattern }}"
    recurse: no
  register: dot_files_dirs

- name: "Merge files and directories..."
  set_fact:
    dot_items:
      files: "{{ dot_files_items.files + dot_files_dirs.files }}"
      matched: "{{ dot_files_items.matched + dot_files_dirs.matched }}"
      examined: "{{ dot_files_items.examined + dot_files_dirs.examined }}"
      msg:
        file: "{{ dot_files_items.msg }}"
        directory: "{{ dot_files_dirs.msg }}"

- name: "Backup"
  include: backup.yml
  when: dot_backup_enable and dot_items.matched > 0

# # Source relative to dot_root, destination relative to dot_home  | basename?
- name: "Create {{ dot_target.key }} symlinks in {{ dot_target.value.dest }}"
  file:
    src: "{{ item }}"
    dest: "{{ dot_target.value.dest }}/{{ dot_target.value.prefix }}{{ item | basename }}"
    # src: "{{ item.value.src }}/{{ item.src | default(item) }}"
    # dest: "{{ item.value.dest }}/{{ item.value.prefix | default('') }}{{ item.dest | default(item) }}"
    state: link
  # with_lines: "{{ dot_find }}"
  with_items: "{{ dot_items.files | map(attribute='path') | list }}"
  register: dot_items

- name: "Log symlinks"
  vars:
    dest: "{{ dot_target.value.dest }}/{{ dot_target.value.prefix }}{{ item | basename }}"
  debug: var=dest
  with_items: "{{ dot_items.results | map(attribute='item') | list }}"
  when: dot_log_enable
  # verbosity: 1
