---
# https://github.com/nodesource/distributions
# 0.10, 0.12, 4.x or 6.x
node_version: "0.12"
node_force_install: no

# FIXME on Pi:
# https://github.com/nodejs/node-v0.x-archive/issues/7222

# Pin-Priority of NodeSource apt repository
node_nodesource_pin_priority: 500
