---
i3:
  themeName: Arc-Dark
  # iconThemeName: Arc-Dark
  iconThemeName: Papirus-Dark
  darkMode: true
  pmTray: true
  borderRadius: 18
  borderWidth: 1
  fontFamily: Noto Sans
  fontSize: 10
  opacity: 0.75
  barFont: pango:Noto Sans Mono, FontAwesome 10
  environment:
    GDK_DPI_SCALE: 1
    GDK_SCALE: 2
    # GTK_ICON_THEME:
    # GTK_THEME: Adwaita:dark
    QT_FONT_DPI: 192

    # GTK2_RC_FILES: "$HOME/.gtkrc-2.0"
    # GTK2_RC_FILES: "$HOME/.config/gtk-2.0"

    QT_AUTO_SCREEN_SCALE_FACTOR: 0 # 1
    # QT_QPA_PLATFORMTHEME: gtk2 # (xdg-desktop-portal)
    QT_QPA_PLATFORMTHEME: qt5ct
    # QT_QPA_PLATFORMTHEME: qt6ct

    QT_SCALE_FACTOR: 1
    # STEAM_FORCE_DESKTOPUI_SCALING: 1.5
    # STEAM_FORCE_DESKTOPUI_SCALING: 2.0
