---
packages:
  ruby-mise:
    enabled: false # {{ and .features.mise .features.ruby }}
    name: ruby
    type: mise
  ruby:
    enabled: "{{ .features.ruby }}"
    nameOverwrite:
      darwin: ruby ruby-build # ruby
      debian: ruby-dev
      fedora: ruby-devel
      # windows: RubyInstallerTeam.Ruby.3.4
  rubygems:
    enabled: '{{ and .features.ruby (eq .osIDLike "arch" "debian" "fedora") (not
      (and (eq .osID "ubuntu") (le (float64 .osVersion) 20.04))
      ) }}'
    nameOverwrite:
      debian: ruby-rubygems
