---
- name: Clone Arc icon theme
  git:
    repo: https://github.com/horst3180/arc-icon-theme
    dest: "{{ tmp_dir }}/arc-icon-theme"
    depth: 1

- name: Copy icons
  copy:
    remote_src: "{{ tmp_dir }}/arc-icon-theme/Arc"
    dest: "{{ ansible_env.HOME }}/.icons"
