---
- debug:
    var: tmp_dir
- name: Download Arc Icon Theme
  git:
    repo: https://github.com/horst3180/arc-icon-theme
    dest: "{{ tmp_dir }}arc-icon-theme"
    depth: 1
    force: yes

- name: Copy to ~/.icons
  command: "mv {{ tmp_dir }}arc-icon-theme/Arc {{ ansible_env.HOME }}/.icons/"
  args:
    creates: "{{ ansible_env.HOME }}/.icons/Arc"
    removes: "{{ tmp_dir}}arc-icon-theme/Arc"
  # copy:
  #   src: "{{ tmp_dir }}arc-icon-theme/Arc"
  #   dest: "{{ ansible_env.HOME }}/.icons/"
  #   remote_src: yes
