---
- name: "Construct {{ dot_files_dir | default('directory') }} dict"
  set_fact:
    dot_files_target: >
      {{{
        item.key: {
          'src': dot_root + ('/' + item.value.src if item.value.src | default(false) else '/' + dot_roles_dir + '/' + item.key + '/' + dot_files_dir if dot_files_dir and dot_roles_dir else item.key),
          'dest': dot_home + ('/' + item.value.dest if item.value.dest | default(false) else ''),
          'prefix': item.value.prefix | default(''),
          'pattern': item.value.pattern | default(dot_find_pattern)
        }
      }}}
  with_dict: "{{ dot_files }}"

# - debug:
#     # var: dot_files_target
#     msg: "{{ item.value }}"
#   with_dict: "{{ dot_files }}"
#   when: dot_log_enable

# - name: Check source path
#   assert:
#     that:
#       - "source != inventory_dir"

# - name: Ensure source and destination directories exist
#   file:
#     path: "{{ item }}"
#     state: directory
#     follow: true
#   with_items:
#     - "{{ source }}"
#     - "{{ destination }}"


# - name: "Construct {{ dot_files_dir | default('directory') }} dict"
#   set_fact:
#     dot_target_map: >
#       {{ dot_target_map | combine({
#         dot_dict_key: {
#           item.key: {
#             '_src': dot_root + ('/' + item.value.src if item.value.src | default(false) else '/' + dot_roles_dir + '/' + item.key + '/' + dot_files_dir if dot_files_dir and dot_roles_dir else item.key),
#             '_dest': dot_home + ('/' + item.value.dest if item.value.dest | default(false) else ''),
#             'prefix': item.value.prefix | default(''),
#             'pattern': item.value.pattern | default(dot_find_pattern)
#           }
#         }
#       }, recursive=true) }}
#   with_dict: "{{ dot_files }}"
