---
- name: "Construct {{ dot_dir_name | default('directory') }} dict"
  set_fact:
    dot_files: >
      {{ dot_files | combine({
        item.key: {
          '_src': dot_root + ('/' + item.value.src if item.value.src | default(false) else '/' + dot_roles_dir + '/' + item.key + '/' + dot_dir_name if dot_dir_name and dot_roles_dir else item.key),
          '_dest': dot_home + ('/' + item.value.dest if item.value.dest | default(false) else ''),
          'prefix': item.value.prefix | default(''),
          'pattern': item.value.pattern | default(dot_find_pattern)
        }
      }, recursive=true) }}
  with_dict: "{{ dot_files }}"

# - debug:
#     msg: "{{ item }}"
#   with_dict: "{{ dot_files }}"
#   when: dot_log_enable

# - name: Check source path
#   assert:
#     that:
#       - "source != inventory_dir"

# - name: Ensure source and destination directories exist
#   file:
#     path: "{{ item }}"
#     state: directory
#     follow: true
#   with_items:
#     - "{{ source }}"
#     - "{{ destination }}"
