---
# Tokyonight Day.itermcolors:
#   type: file
#   url: https://raw.githubusercontent.com/folke/tokyonight.nvim/refs/heads/main/extras/iterm/tokyonight_day.itermcolors
#   refreshperiod: 168h
# Tokyonight Storm.itermcolors:
#   type: file
#   url: https://raw.githubusercontent.com/folke/tokyonight.nvim/refs/heads/main/extras/iterm/tokyonight_storm.itermcolors
#   refreshperiod: 168h
