#!/bin/sh
#
# https://pqrs.org/osx/karabiner/
# Key repeat overwrite

cli=/Applications/Karabiner.app/Contents/Library/bin/karabiner

$cli set repeat.wait 25
/bin/echo "repeat.wait 25"
$cli set repeat.initial_wait 400
/bin/echo "repeat.initial_wait 400"
