---
packages:
  # neovide:
  #   enabled: '{{ and .features.neovim (eq .osIDLike "darwin") (not .headless) }}'
  #   link: false
  neovide-app:
    enabled: '{{ and .features.neovim (eq .osIDLike "darwin") (not .headless) }}'
    type: '{{ eq .osIDLike "darwin" | ternary "cask" nil }}'
