---
packages:
  # neovide:
  #   enabled: '{{ and .features.neovim (eq .osIDLike "darwin") (not .headless) }}'
  #   link: false
  neovide-app:
    enabled: '{{ and .features.neovim (eq .osIDLike "darwin" "fedora") (not .headless) }}'
    nameOverwrite:
      fedora: dev.neovide.neovide
    type: '{{ eq .osIDLike "darwin" | ternary "cask" (eq .osIDLike "fedora" | ternary "flatpak" nil) }}'
    after_script: |
      {{- if eq .osIDLike "fedora" }}
      # cmd flatpak override dev.neovide.neovide --filesystem=home
      if ! [ -L ~/.var/app/dev.neovide.neovide/config/nvim ]; then
        cmd ln -s ~/.config/nvim ~/.var/app/dev.neovide.neovide/config/nvim
      fi
      {{- end }}
