---
packages:
  starship:
    nameOverwrite:
      mise: github:starship/starship # Segmentation fault with aqua backend on ARM
      windows: Starship.Starship
    type: '{{ eq .osIDLike "alpine" "debian" "fedora" "rhel" | ternary "mise" nil }}'
