---
dependencies:

  - role: package
    packages:
      - gnome-themes-standard
      - arc-theme
    when: "{{ ansible_os_family == 'Debian' }}"

  - role: package
    packages:
      - gnome-themes-standard
    when: "{{ ansible_os_family == 'Archlinux' }}"

    # gtk, icons & firefox
  - role: pacman-yaourt
    pacman_yaourt_packages:
      - arc-firefox-theme
      - arc-icon-theme
      - gtk-theme-arc
      # - vlc-arc-dark-git
    when: "{{ ansible_os_family == 'Archlinux' }}"
