#
# ~/.bashrc
#

# https://github.com/mathiasbynens/dotfiles/blob/master/.bash_profile
# https://github.com/mathiasbynens/dotfiles/blob/master/.functions
# https://github.com/Bash-it/bash-it/blob/master/lib/helpers.bash
# https://github.com/Bash-it/bash-it/blob/master/settings/available/base.plugin.bash

# If not running interactively, do not do anything
[[ $- != *i* ]] && return

# Bash directory
BASH_DIR="$HOME/.bash.d"

source $BASH_DIR/library/utils.bash

# TODO? Source completion with ~/.bash_completion (not loaded on OSX)
_source $BASH_DIR/{aliases,completion,settings}

_source $BASH_DIR/library/{colorize-cat-less,colors,pathmunge}.bash

# Colors are used in ~/.bash_prompt
# ~/.path is using pathmunge
# ~/.extra may not exist
_source ~/.{bash_prompt,exports,path,extra} 2>/dev/null
