#
# ~/.bashrc
#

# https://github.com/mathiasbynens/dotfiles/blob/master/.bash_profile
# https://github.com/mathiasbynens/dotfiles/blob/master/.functions
# https://github.com/Bash-it/bash-it/blob/master/bash_it.sh
# https://github.com/Bash-it/bash-it/blob/master/lib/helpers.bash
# https://github.com/Bash-it/bash-it/blob/master/settings/available/base.plugin.bash
# https://github.com/barryclark/bashstrap

# If not running interactively, do not do anything
[[ $- != *i* ]] && return

# Bash directory
BASH_DIR="$HOME/.bash.d"

main() {
  # local user="$(id -un)" # $(whoami)
  # local host="$(hostname -s)"

  # TODO
  # use .aliases, .functions...
  # Source completion with ~/.bash_completion (not loaded on OSX)
  load $BASH_DIR/{aliases,completion,functions,plugins,settings}

  # Colors are used in ~/.bash.d/prompt
  # ~/.bash.d/path is using pathmunge
  load $BASH_DIR/{colors,exports,path,prompt}.bash

  PROMPT_SYMBOL='› '
  PROMPT_COMMAND='__prompt_command'
  PS1=$(__prompt_string "$PROMPT_SYMBOL") # $ ✓ → ×
  PS2=${PROMPT_SYMBOL:-> }

  # Extra settings
  load ~/.bashrc.local 2>/dev/null
}

# Source a list of path recursively
load() {
  for path in "$@"; do
    if [[ -d "$path" ]]; then
      load $path/*
    elif [[ -f "$path" ]]; then
      # echo >&2 "Loaded: $path"
      source "$path"
    else
      echo >&2 "No such file or directory: $path"
    fi
  done
  unset path
}

main "$@"
