---
# https://github.com/folke/tokyonight.nvim/tree/main/extras/iterm
tokyonight-day.itermcolors:
  type: file
  url: https://raw.githubusercontent.com/folke/tokyonight.nvim/main/extras/iterm/tokyonight_day.itermcolors
  refreshPeriod: 168h
tokyonight-moon.itermcolors:
  type: file
  url: https://raw.githubusercontent.com/folke/tokyonight.nvim/main/extras/iterm/tokyonight_moon.itermcolors
  refreshPeriod: 168h
tokyonight-night.itermcolors:
  type: file
  url: https://raw.githubusercontent.com/folke/tokyonight.nvim/main/extras/iterm/tokyonight_night.itermcolors
  refreshPeriod: 168h
tokyonight-storm.itermcolors:
  type: file
  url: https://raw.githubusercontent.com/folke/tokyonight.nvim/main/extras/iterm/tokyonight_storm.itermcolors
  refreshPeriod: 168h
