---
# https://github.com/folke/tokyonight.nvim/tree/main/extras/iterm
Tokyonight Day.itermcolors:
  type: file
  url: https://raw.githubusercontent.com/folke/tokyonight.nvim/main/extras/iterm/tokyonight_day.itermcolors
  refreshPeriod: 168h
Tokyonight Storm.itermcolors:
  type: file
  url: https://raw.githubusercontent.com/folke/tokyonight.nvim/main/extras/iterm/tokyonight_storm.itermcolors
  refreshPeriod: 168h
