var data = {lines:[
{"lineNum":"    1","line":"#!/bin/sh"},
{"lineNum":"    2","line":""},
{"lineNum":"    3","line":"set -eu","class":"lineCov","hits":"1","order":"104","possible_hits":"0",},
{"lineNum":"    4","line":""},
{"lineNum":"    5","line":". \"$CHEZMOI_WORKING_TREE/home/.chezmoitemplates/helpers.sh\"","class":"lineCov","hits":"1","order":"105","possible_hits":"0",},
{"lineNum":"    6","line":""},
{"lineNum":"    7","line":"# https://github.com/b3nj5m1n/xdg-ninja/tree/main/programs"},
{"lineNum":"    8","line":"# https://github.com/twpayne/dotfiles/blob/master/home/dot_zshrc.tmpl"},
{"lineNum":"    9","line":"export XDG_CACHE_HOME=\"$HOME/.cache\"","class":"lineCov","hits":"2","order":"106","possible_hits":"0",},
{"lineNum":"   10","line":"export XDG_CONFIG_HOME=\"$HOME/.config\"","class":"lineCov","hits":"2","order":"107","possible_hits":"0",},
{"lineNum":"   11","line":"export XDG_DATA_HOME=\"$HOME/.local/share\"","class":"lineCov","hits":"2","order":"108","possible_hits":"0",},
{"lineNum":"   12","line":"export XDG_STATE_HOME=\"$HOME/.local/state\"","class":"lineCov","hits":"2","order":"109","possible_hits":"0",},
{"lineNum":"   13","line":"export CURL_HOME=\"${CURL_HOME:-$XDG_CONFIG_HOME/curl}\"","class":"lineCov","hits":"2","order":"110","possible_hits":"0",},
{"lineNum":"   14","line":"export LESSHISTFILE=\"${LESSHISTFILE:-$XDG_STATE_HOME/lesshst}\"","class":"lineCov","hits":"2","order":"111","possible_hits":"0",},
{"lineNum":"   15","line":"# TODO: move to global env"},
{"lineNum":"   16","line":"export LESSSECURE=1","class":"lineCov","hits":"2","order":"112","possible_hits":"0",},
{"lineNum":"   17","line":"# LESSSECURE_ALLOW=edit,examine,glob,history,lesskey,lessopen,logfile,osc8,pipe,shell,stop,tags"},
{"lineNum":"   18","line":"export LESSSECURE_ALLOW=edit,examine,glob,osc8,pipe,shell,stop,tags","class":"lineCov","hits":"2","order":"113","possible_hits":"0",},
{"lineNum":"   19","line":"# unset LESSOPEN LESSPIPE"},
{"lineNum":"   20","line":"# TODO: export GNUPGHOME=\"$XDG_DATA_HOME/gnupg\""},
{"lineNum":"   21","line":"export INPUTRC=\"${INPUTRC:-$XDG_CONFIG_HOME/readline/inputrc}\"","class":"lineCov","hits":"2","order":"114","possible_hits":"0",},
{"lineNum":"   22","line":"export STARSHIP_CONFIG=\"$XDG_CONFIG_HOME/starship/starship.toml\"","class":"lineCov","hits":"2","order":"115","possible_hits":"0",},
{"lineNum":"   23","line":"export PSQLRC=\"$XDG_CONFIG_HOME/psql/psqlrc\"","class":"lineCov","hits":"2","order":"116","possible_hits":"0",},
{"lineNum":"   24","line":"export RIPGREP_CONFIG_PATH=\"$XDG_CONFIG_HOME/ripgrep/config\"","class":"lineCov","hits":"2","order":"117","possible_hits":"0",},
{"lineNum":"   25","line":"export WGETRC=\"$XDG_CONFIG_HOME/wget/wgetrc\"","class":"lineCov","hits":"2","order":"118","possible_hits":"0",},
{"lineNum":"   26","line":"# export ZDOTDIR=\"$XDG_CONFIG_HOME/zsh\""},
{"lineNum":"   27","line":"# export XAUTHORITY=\"$XDG_RUNTIME_DIR/Xauthority\""},
{"lineNum":"   28","line":""},
{"lineNum":"   29","line":"# https://askubuntu.com/a/961459"},
{"lineNum":"   30","line":"# if [ -d ~/.Xauthority ] && ! [ -d \"$XAUTHORITY\" ]; then"},
{"lineNum":"   31","line":"#   cmd mv ~/.Xauthority \"$XAUTHORITY\""},
{"lineNum":"   32","line":"#   cmd ln -s \"$XAUTHORITY\" ~/.Xauthority"},
{"lineNum":"   33","line":"# fi"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "test", "date" : "2025-11-11 22:14:53", "instrumented" : 15, "covered" : 15,};
var merged_data = [];
