var data = {lines:[
{"lineNum":"    1","line":"#!/bin/sh"},
{"lineNum":"    2","line":""},
{"lineNum":"    3","line":"# Usage: xdg-open \"https://github.com/$(nvim-sh)\""},
{"lineNum":"    4","line":""},
{"lineNum":"    5","line":"set -eu","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"    6","line":""},
{"lineNum":"    7","line":"bkt=","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"    8","line":"if command -v bkt >/dev/null; then","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"    9","line":"  ttl=1d","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   10","line":"  bkt=\"bkt --ttl=$ttl --\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   11","line":"fi"},
{"lineNum":"   12","line":"# shellcheck disable=SC2016"},
{"lineNum":"   13","line":"search=\"$bkt \"\'curl -LSfs https://nvim.sh/s/$tag\'","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   14","line":"cmd=\"echo; $bkt curl https://nvim.sh/t | sort\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   15","line":"# shellcheck disable=SC2034"},
{"lineNum":"   16","line":"tag=\"$(sk --ansi --cmd=\"$cmd\" --interactive --preview=\"tag={}; $search\")\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   17","line":"search() {"},
{"lineNum":"   18","line":"  cmd=\"$(eval \"echo \\\"$search\\\"\") | tail -n+2\" # | tr -s \' \' \';\'","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   19","line":"  preview=\"echo {}\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   20","line":"  if command -v gh >/dev/null; then","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   21","line":"    # shellcheck disable=SC2016"},
{"lineNum":"   22","line":"    preview=\"$bkt \"\'gh repo view $(echo {} | cut -d\" \" -f1)\'","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   23","line":"    if command -v glow >/dev/null; then","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   24","line":"      preview=\"$preview | CLICOLOR_FORCE=1 COLORTERM=truecolor glow --style=dark\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   25","line":"    fi"},
{"lineNum":"   26","line":"  fi"},
{"lineNum":"   27","line":"  sk --ansi --cmd=\"$cmd\" --interactive --preview=\"$preview\" \"$@\" # --delimiter=\";\" --nth=1","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   28","line":"}"},
{"lineNum":"   29","line":"# Name Stars OpenIssues Updated Description"},
{"lineNum":"   30","line":"name=\"$(search \"$@\" | cut -d\' \' -f1)\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   31","line":"if [ -z \"$name\" ]; then","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   32","line":"  exit 1","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   33","line":"fi"},
{"lineNum":"   34","line":"echo \"$name\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "test", "date" : "2025-12-13 20:53:49", "instrumented" : 19, "covered" : 0,};
var merged_data = [];
