---
packages:
  notmuch:
    enabled: "{{ .features.mail }}"
    # type: '{{ eq .osIDLike "arch" | ternary "aur" nil }}'
  notmuch-vim:
    enabled: "{{ .features.mail }}"
    # type: '{{ eq .osIDLike "arch" | ternary "aur" nil }}'
