---
dependencies:

  - role: package
    packages: "{{ redshift_packages }}"

  # - role: pacman-yaourt
  #   pacman_yaourt_packages:
  #     - redshift
  #     - redshift-gtk

  - role: dotfiles
    paths:
      - name: redshift
        dest: .config
        template: yes
