#!/bin/bash
#
# Homebrew utils
# Uses files: utils, print, ask

install_homebrew () {
	# If OS X and brew not already installed
	if [[ "$OSTYPE" =~ ^darwin ]] && [[ ! "$(type -P brew)" ]]; then

		if ask "Install Homebrew ?" Y; then
			info "Installing Homebrew" "..." true

			#Skip the "Press enter to continue…" prompt.
			true | ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
		fi

	else
		success "Homebrew already present"
	fi
}

brew_bundle () {
	local opts="--appdir=/Applications"

	if [ -n $HOMEBREW_CASK_OPTS ]; then
		opts=$HOMEBREW_CASK_OPTS
	fi

	local file=init/$1file

	info "brew bundle $file" "..."

	if [ -f "$file" ] && silent_et brew bundle "$file" $opts; then
		success "$1 successfully bundled !"
		return 0
	else
		fail "$1 failed to bundle !"
		return 1
	fi
}
