#!/bin/bash
#
# Homebrew utils
# Uses files: utils, print, ask

install_homebrew () {
	# If OS X and brew not already installed
	if [[ "$OSTYPE" =~ ^darwin ]] && [[ ! "$(type -P brew)" ]]; then

		if ask "Download Homebrew ?" Y; then

			#Skip the "Press enter to continue…" prompt.
			true | ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
			info "Homebrew installed"
		fi

	else
		success "Homebrew already here" " " true
	fi
}

brew_bundle () {
	local opts="--appdir=/Applications"

	if [ -n $HOMEBREW_CASK_OPTS ]; then
		opts=$HOMEBREW_CASK_OPTS
	fi

	local file=init/$1file

	info "brew bundle $file" "..."

	[ -f "$file" ] || warn "$file does not exists"

	if [ -f "$file" ] && silent brew bundle "$file" "$opts"; then
		success "$1 successfully bundled !"
		return 0
	else
		fail "$1 failed to bundle !"
		return 1
	fi
}
