#!/bin/bash
#
# Copy with rsync
# Uses lib/utils

src=$1
dst=$2

if [ "$src" = '' -o "$dst" = '' ]
then
	echo "Argument error" > /dev/stderr
	exit 1
fi

silent rsync --exclude-from "lib/exclude" -avh --no-perms $src $dst # > /dev/null;
