#!/bin/bash
#
# Setup some defaults

# Import prompt functions
lib=$DOTFILES/lib
source $lib/print
source $lib/ask

UNAME=$( uname )

if ask "Set defaults ?" Y true; then

	indent_level=2

	info "Using $UNAME specific defaults" " " true

	case $UNAME in

		Darwin)

			if [ "$(whoami)" != "root" ]; then
				warn "Administrator access is required for $(whoami)" && sudo -v
			fi

			# TERMINAL

			# Search for the terminal configuration
			TERM_FILE=`find $DOTFILES -name *.terminal`
			base_name=$(basename $TERM_FILE)
			TERM_PROFILE=${base_name%%.*}
			# Custom version of the Solarized Dark theme
			[ -n "$TERM_PROFILE" ] || TERM_PROFILE='LEI'

			CURRENT_PROFILE="$(defaults read com.apple.terminal 'Default Window Settings')"


			if [ "${CURRENT_PROFILE}" != "${TERM_PROFILE}" ]; then
				if ask "Change Terminal settings ? Currently $CURRENT_PROFILE)" Y; then
					indent_level=3
					open "$TERM_FILE"
					sleep 1 # Wait a bit to make sure the theme is loaded
					defaults write com.apple.terminal 'Default Window Settings' -string "${TERM_PROFILE}"
					defaults write com.apple.terminal 'Startup Window Settings' -string "${TERM_PROFILE}"

					success "Window settings" "Default now set to $TERM_PROFILE.terminal"
				fi
			else
				warn "Window settings" "Already set to $TERM_PROFILE.terminal"
			fi

			indent_level=2

			# SUBLIME TEXT

			if ask "Link Sublime Text preferences ?" Y; then

				st_prefix=~/Library/Application\ Support/Sublime\ Text
				st_suffix=/Packages/User/Preferences.sublime-settings

				for f in "$st_prefix"*"$st_suffix"; do

					rm "$f" # -f ?
					ln -s "$DOTFILES/init/Preferences.sublime-settings" "$f"

					st_success=true
					st_version=${f#$st_prefix}
					success "Sublime Text ${st_version:1:1}" "Symlinked Preferences.sublime-settings"
				done

				[ ! -n "$st_success" ] && fail "No application found" "$st_prefix*$st_suffix"
			fi

			indent_level=2

			# SYSTEM

			if ask "Set OS defaults ?" N; then

				indent_level=3

				ask "SSD specific commands ? ?" N && SSD=true
				info "Executing .osx" "..." true
				if source $DOTFILES/init/.osx; then
					info "Some changes may require a logout/restart to take effect"
				else
					fail "$DOTFILES/init/.osx"
				fi
			fi

			;;

		Linux)

			indent_level=3

			echo $UNAME

			;;

	esac

	indent_level=2

	info "'set-defaults' is an alias to this step" " " true

else
	skipped
fi
