#!/bin/bash
#
# File manipulations

copy () {
	local src=$1

	((indent_level++))
	if [ -f "$src" -o -d "$src" ] && \
		. $lib/copy $src $TARGET_DIR; then
		# ^ > /dev/null
		success "$src" "Copied to ~/$src"
	else
		fail "$src" "Failed to be copied"
	fi
	((indent_level--))
}

remove () {
	local src=$1
	# Find target
	local dst=$TARGET_DIR/${src#$DOTFILES_DIR/}

	((indent_level++))
	if [ ! -e "$dst" ]; then
		success "${dst#$HOME/}" "Not found" true
	elif [ -d "$dst" ]; then
		info "${dst#$HOME/}" "Directory ignored" true
	elif [ -f "$dst" -o -L "$dst" ] && \
		rm $dst; then
		#      ^ 2> /dev/null ?
		success "${dst#$HOME/}" "Removed"
	else
		fail "${dst#$HOME/}" "Cannot be removed"
	fi
	((indent_level--))
}

check_file () {
	local file=$1

	if [ -f $file ]; then
		return 1
	else
		return 0
	fi
}

source_file () {
	local file=$1

	if [ -f $file ] && source "$file"; then
		#success "Operation successfull !"
		return 1
	else
		#fail "Command failed !"
		return 0
	fi
}
