#!/bin/bash
#
# Set Git Credentials
# Uses lib/print

gitmodule () {
	user "username/repository ?" "GitHub"
	read -e MODULE_NAME

	user "Path ?" "Relative to $DOTFILES"
	read -e MODULE_PATH

	git submodule add https://github.com/$MODULE_NAME.git $MODULE_PATH
}
