#!/bin/bash
#
# Set Git Credentials
# Uses lib/print 

gitconfig () {
	local CREDENTIAL="cache"
	[ "$(uname -s)" == "Darwin" ] && CREDENTIAL="osxkeychain"

	if [ ! -n "$NAME" ]; then
		user "What is your github author name ?" " "
		read -e NAME
	fi
	
	if [ ! -n "$EMAIL" ]; then
		user "What is your github author email ?" " "
		read -e EMAIL
	fi

	sed -e "s/GIT_AUTHOR_NAME/$NAME/g" \
		-e "s/GIT_AUTHOR_EMAIL/$EMAIL/g" \
		-e "s/GIT_CREDENTIAL_HELPER/$CREDENTIAL/g" \
		git/gitconfig.sample > git/gitconfig.

	success "Git credentials generated." "git/gitconfig."
}

gitmodule () {
	user "username/repository ?" "GitHub"
	read -e MODULE_NAME

	user "Path ?" "Relative to $DOTFILES"
	read -e MODULE_PATH

	git submodule add https://github.com/$MODULE_NAME.git $MODULE_PATH
}
