#!/bin/bash
#
# Set Git Credentials
# Uses lib/print

gitconfig () {
	local git_credential="cache"

	[ "$(uname -s)" == "Darwin" ] && git_credential="osxkeychain"

	user "What is your github author name ?"
	read -e GIT_AUTHOR_NAME
	user "What is your github author email ?"
	read -e GIT_AUTHOR_EMAIL

	sed -e "s/AUTHORNAME/$GIT_AUTHOR_NAME/g" \
		-e "s/AUTHOREMAIL/$GIT_AUTHOR_EMAIL/g" \
		-e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" \
		git/gitconfig.tpl > git/gitconfig.

	success "Git credentials generated."
}
