#!/bin/bash
#
# Setup some defaults

# Import prompt functions
lib=$DOTFILES/lib
source $lib/print
source $lib/ask
source $lib/brew

UNAME=$( uname )

info "'set-up' is an alias to execute Brew and Cask files" " " true
echo ''

if [ -n "$indent_level" ]; then
	original_level=$indent_level
else
	indent_level=2
fi

case $UNAME in

	Darwin)

		# HOMEBREW

		if install_homebrew; then

			# BREW LIBS

			# Install dependencies
			if ask "Bundle brew ?" Y; then
				((indent_level++))
				brew_bundle "Brew"
			else
				skipped "Brew"
				((indent_level++))
			fi

			((indent_level--))

			# CASK APPS

			# Install programs
			if ask "Bundle cask ?" Y; then
				((indent_level++))
				brew_bundle "Cask"
			else
				skipped "Cask"
				((indent_level++))
			fi

			((indent_level--))

		else
			skipped "Homebrew"
		fi


		# indent_level=2
		# if ask "Set OS defaults ?" N; then

		# 	indent_level=3

		# 	ask "SSD ?" N && SSD=true
		# 	info "Executing commands" "..." true
		# 	if source $DOTFILES/init/.osx; then
		# 		info "Some changes may require a logout/restart to take effect"
		# 	else
		# 		fail "$DOTFILES/init/.osx"
		# 	fi
		# fi


		;;

	Linux)

		# apt-get stuff ?
		# https://github.com/Homebrew/linuxbrew ?

		;;

esac

echo ''
indent_level=$original_level

return 1

