#!/bin/bash
#
# Usage

source $lib/colors

echo "$DOTFILES/${white}bootstrap${reset}"
echo ""
echo "   Usage: dot [command] [options]"
echo ""
echo "   Where <command> is:  (alias)"
echo "         install        'dot'"
echo "         uninstall      'undot'"
echo "         defaults       'set-defaults'"
echo "         bundle         'set-up'"
echo ""
echo "   And <option> is:"
echo "      -d, --debug       Do less print more"
# echo "      -?, --default     Use predefined answers"
# echo "      -f, --force       Do everything blindlessly"
# echo "      -m, --mute        Only show main logs"
echo "      -s, --sandbox     Use another directory"
echo "      -h, --help        Show this message"

exit 0
