#!/bin/bash
#
# Usage

source $lib/colors

echo "$DOTFILES/bootstrap"
echo ""
echo "   Usage: dot [command] [options]"
echo ""
echo "   Where <command> is:  alias:"
echo "         install        dot"
echo "         uninstall      undot"
echo "         defaults       ~/.dotfiles/defaults"
echo "         setup          ~/.dotfiles/setup"
echo ""
echo "   And <option> is:"
echo "      -d, --debug       Not ready yet"
# echo "      -?, --default     Use predefined answers"
# echo "      -f, --force       Do everything blindlessly"
echo "      -h, --help        Show this message"
echo "      -s, --sandbox     Use another directory"
echo "      -u, --ugly        Remove colors for light backgrounds"
echo "      -v, --verbose     Print secondary logs"
echo ""
echo "   More details on commands:"
echo "      You need to run './bootstrap' one time in order to symlink '~/bin' and use the 'dot' command."
echo "      'dot' will execute all bootstrap steps unless it is stopped."
echo "      'dot defaults' is available on OS X only (for now) and may require to restart."
echo "      setup consists to check for Homebrew then install bundles with init/Brewfile and init/Caskfile."
echo "      'dot uninstall / undot' only undo:"
echo "         - Symbolic links (files '*.$' and 'bin/*')"
echo "         - Copied files (root directory '^.*') in $DOTFILES tree"
echo "      It does not reverse 'dot defaults' and does not uninstall dependencies installed by 'dot setup'."

exit 0
