#!/bin/bash
#
# Usage

echo "bootstrap [command] [options]"
echo "$DOTFILES/${white}bootstrap${reset}"
echo ""
echo "Usage: dot install [options]"
echo "   or: dot uninstall [options]"
echo "   or: dot defaults (set-defaults)"
echo "   or: dot bundle (set-up)"
echo ""
echo "   dot is an alias for ${0#$DOTFILES/}"
echo "   undot is an alias for dot uninstall"
echo ""
echo "Options:"
echo "   -d, --debug     Debug"
#echo "   -d, --default   Use predefined answers"
#echo "   -f, --force     Do everything blindlessly"
echo "   -s, --sandbox   Use another directory"
echo "   -h, --help      Show this message"

# echo "bootstrap [command] [options]"
# echo "$DOTFILES/${white}script/bootstrap${reset}"
# echo ""
# echo "Usage: dot install [options]"
# echo "   or: dot uninstall [options]"
# echo "   or: dot brew (brew bundle init/Brewfile)"
# echo "   or: dot cask (brew bundle init/Caskfile)"
# echo ""
# echo "   dot is an alias for ${0#$DOTFILES/}"
# echo "   undot is an alias for dot uninstall"
# echo ""
# echo "Options:"
# echo "   -d, --default   Use predefined answers"
# echo "   -f, --force     Do everything blindlessly"
# echo "   -m, --mute      Only show main logs"
# echo "   -s, --sandbox   Use another directory"
# echo "   -t, --test   Debug"
# echo "   -h, --help      Show this message"

echo ''
exit 0
