#!/bin/bash
#
# Utility functions

# TODO : wtf
silent_et () {
	if [ "$verbose" = true ] ; then
		eval "$@"
	else
		eval "$@" &>/dev/null # (2|&)>/dev/null
	fi
}

silent () {
	if [ "$verbose" = true ] ; then
		eval "$@"
	else
		eval "$@" >/dev/null # (2|&)>/dev/null
	fi
}
