---
- name: "Install global Composer packages in {{ composer_home_path }}"
  composer:
    command: require
    arguments: "{{ item.name | default(item) }}:{{ item.release | default(composer_packages_release) }}"
    working_dir: "{{ composer_home_path }}"
  # shell: "composer global require {{ item.name | default(item) }}:{{ item.release | default(composer_packages_release) }} --no-progress"
  # args:
  #   creates: "{{ composer_home_path }}/vendor/{{ item.name | default(item) }}"
  with_items: "{{ composer_packages }}"

# - name: Add Composer bin directory to global $PATH
#   template:
#     src: composer.sh.j2
#     dest: /etc/profile.d/composer.sh
#     mode: 0644
#   when: composer_add_to_path

# export PATH=$PATH:$COMPOSER_HOME/$COMPOSER_BIN_DIR

# - name: add {{extra_path}} to path
#   lineinfile: >
#     dest=/etc/environment
#     state=present
#     backrefs=yes
#     regexp='PATH=(["]*)((?!.*?{{extra_path}}).*?)(["]*)$'
#     line="PATH=\1\2:{{extra_path}}\3"
