---
# getcomposer.org/download/

#   php -r "readfile('https://getcomposer.org/installer');" > composer-setup.php
#   php -r "if (hash('SHA384', file_get_contents('composer-setup.php')) === '41e71d86b40f28e771d4bb662b997f79625196afcca95a5abf44391188c695c6c1456e16154c75a211d238cc3bc5cb47') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
#   php composer-setup.php
#   php -r "unlink('composer-setup.php');

# Save the checksum on the managing machine to be used with the file lookup
- name: Get Composer installer signature
  # get_url:
  #   url: https://composer.github.io/installer.sig
  #   dest: "{{ tmp_dir }}composer-installer.sig"
  local_action: >
    get_url
    url=https://composer.github.io/installer.sig
    dest="{{ tmp_dir }}composer-installer.sig"

- name: Download Composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: "{{ tmp_dir }}composer-installer.php"
    mode: 0755
    checksum: "sha384:{{ lookup('file', tmp_dir + 'composer-installer.sig') }}"
  # check mode: lookup fails

- name: Run Composer installer
  shell: "{{ php_executable }} composer-installer.php --install-dir={{ composer_bin_path }} --filename=composer {% if composer_version != '' %} --version={{ composer_version }}{% endif %}"
  args:
    chdir: "{{ tmp_dir }}"
  become: "{{ 'yes' if ansible_os_family in ['Archlinux', 'Debian', 'RedHat'] else 'no' }}"

# - name: Move Composer to be accessed globally
#   shell: "mv {{ tmp_dir }}composer.phar {{ composer_path }}"
#   args:
#     creates: "{{ composer_path }}"
