---
# github.com/geerlingguy/ansible-role-composer
# github.com/osxstrap/ansible-osx-php

- name: Check if Composer is installed
  command: composer --version
  changed_when: composer_version_result.rc != 0
  failed_when: false
  register: composer_version_result

- include: install-composer.yml
  when: composer_version_result.rc != 0 or composer_force_install

- name: Update Composer
  # composer:
  #   command: self-update
  #   working_dir: "{{ composer_home_path }}"
  shell: "{{ php_executable }} {{ composer_bin_path }}/composer self-update"
  register: composer_update_result
  when: composer_update
  changed_when: "'Updating to version' in composer_update_result.stdout"
  become: "{{ 'yes' if ansible_os_family != 'Darwin' else 'no' }}"

- include: global-require.yml
  when: composer_packages | length > 0
