---
# dependencies:

#   - role: package
#     packages:
#       - ack-grep
#     when: "ansible_os_family == 'Debian'"

#   - role: package
#     packages:
#       - ack
#     when: "ansible_os_family == 'Darwin'"
