---
- name: "{{ role_dir }} : Register source and destination"
  # set_fact:
  #   "{{ item.key }}": "{{ item.value.root }}/{{ item.value ...".
  # with_dict:
  set_fact:
    # source: "{{ dot_root }}" #{{ '/' + paths.src if paths.src else 'roles/' + role_name  }}"
    # destination: "{{ dot_home }}" #{{ '/' + paths.dst if paths.dst else '' }}"
    source: "{{ dot_root }}{{ '/' + vars[directory + '_source'] if vars[directory + '_source'] else '/roles/' + role_dir + '/' + directory if role_dir else '' }}"
    destination: "{{ dot_home }}{{ '/' + vars[directory + '_destination'] if vars[directory + '_destination'] else '' }}"

- name: "{{ role_dir }} : Ensure targets exists"
  file:
    path: "{{ item }}"
    state: directory
    follow: true
  with_items:
    - "{{ source }}"
    - "{{ destination }}"
