---
vim:
  plugins:
    airline:
      repo: vim-airline/vim-airline
      tag: v0.11
    catppuccin:
      repo: catppuccin/vim

    commentary:
      repo: tpope/vim-commentary
      # version: v1.3

    # dadbod:
    #   repo: tpope/vim-dadbod
    #   tag: v1.4
    # dadbod-ui:
    #   repo: kristijanhusak/vim-dadbod-ui
    # dadbod-completion:
    #   repo: kristijanhusak/vim-dadbod-completion

    endwise:
      repo: tpope/vim-endwise
      tag: v1.3
    eunuch:
      repo: tpope/vim-eunuch
      tag: v1.3
    fugitive:
      repo: tpope/vim-fugitive
      tag: v3.7

    polyglot:
      repo: sheerun/vim-polyglot
      tag: v4.17.0

    sensible:
      repo: tpope/vim-sensible
      # version: 2.0.0

    sleuth:
      repo: tpope/vim-sleuth
      # version: 2.0.0

    surround:
      repo: tpope/vim-surround
      tag: v2.2

    undotree:
      repo: mbbill/undotree
      tag: rel_6.1
