---
packages:
  # gvim:
  # macvim:
  #   enabled: '{{ and .features.vim (eq .osIDLike "darwin") (not .headless) }}'
  macvim-app:
    enabled: '{{ and .features.vim (eq .osIDLike "darwin") (not .headless) }}'
    type: '{{ eq .osIDLike "darwin" | ternary "cask" nil }}'
  vim:
    enabled: "{{ .features.vim }}"
    nameOverwrite:
      fedora: vim-enhanced # vim-minimal
      windows: vim.vim
    # type: '{{ eq .osIDLike "windows" | ternary "winget" nil }}'
