"
" ~/.vim/vimrc
"

" zi Folding on/off
" zR Open all
" zM Close all
" za Toggle current
" zj Down to the start of the next
" zk Up to the end of the previous

" github.com/mathiasbynens/dotfiles/blob/master/.vimrc
" github.com/tpope/vim-sensible/blob/master/plugin/sensible.vim"

" Before {{{1

set nocompatible

runtime plug.vimrc

" Load matchit.vim, but only if the user hasn't installed a newer version
if !exists('g:loaded_matchit') && findfile('plugin/matchit.vim', &rtp) ==# ''
  runtime macros/matchit.vim
endif

" General {{{1

" set encoding=utf-8

if has("autocmd")
  " Enable filetype detection
  filetype plugin indent on
endif

if &history < 1000
  set history=1000
endif

" Reload unmodified files when changes are detected outside
set autoread

"if has('path_extra')
""  setglobal tags-=./tags tags-=./tags; tags^=./tags;
"endif

"if &shell =~# 'fish$'
"  set shell=/bin/bash
"endif

if &tabpagemax < 50
  set tabpagemax=50
endif

" Use Unix as the standard file type
set ffs=unix,dos,mac

" Use system clipboard
set clipboard=unnamed

" Fast terminal connection
if !has('nvim')
  set ttyfast
endif

" Delete comment character when joining commented lines
if v:version > 703 || v:version == 703 && has("patch541")
  set formatoptions+=j
endif

" Tell vim to remember certain things when we exit
"  '10  :  marks will be remembered for up to 10 previously edited files
"  "100 :  will save up to 100 lines for each register
"  :20  :  up to 20 lines of command-line history will be remembered
"  %    :  saves and restores the buffer list
"  n... :  where to save the viminfo files
"set viminfo='10,\"100,:20,%,n~/.viminfo

if !empty(&viminfo)
  set viminfo^=!
endif

" Do not capture all global options
set sessionoptions-=options

" Disable swapfiles and backups
set noswapfile
set nobackup
set nowritebackup

" Keep undo history across sessions, by storing in file.
if has('persistent_undo') && !isdirectory(expand('~').'/.vim/backups')
  silent !mkdir ~/.vim/backups > /dev/null 2>&1
  set undodir=~/.vim/backups
  set undofile
endif

"set binary
"set noeol

set modeline
set modelines=2

" Enable per-directory .vimrc files and disable unsafe commands in them
set exrc
set secure

"set complete-=i
set nrformats-=octal

set nostartofline

" Modified buffers can persist in the background
set hidden

" Don't redraw while executing macros
set lazyredraw

set timeout
" Wait for input, but not when returning to normal mode
set timeoutlen=666 ttimeoutlen=0

" Interface {{{1

" Normal backspace in insert mode
set backspace=indent,eol,start

" Recognize escape immediately
set esckeys

" Set the window title
set title

" Always show the status line
set laststatus=2

" Display current mode (not needed with a custom statusline)
set noshowmode

" Display incomplete commands
set showcmd

" Height of the command bar
set cmdheight=1

" Always show current position
set ruler
"set rulerformat=%l,%c%V%=%P

" Line numbers
set number

" Use relative line numbers
if exists("&relativenumber")
  set relativenumber
endif

" Disable cursor blinking
"set guicursor=a:blinkon0

" Do not show matching brackets when text indicator is over them
set noshowmatch
" How many tenths of a second to blink when matching brackets
"set mat=2

" HTML brackets
set matchpairs+=<:>

"if has("mouse")
set mouse=a
"endif

" Natural new split focus
set splitbelow
set splitright

" Shorter messages
set shortmess=atI

set noerrorbells
set visualbell
set t_vb=

" Spacing {{{1

if !exists("g:loaded_sleuth")
  let s:tabsize=4

  " Indent commands
  let &shiftwidth = s:tabsize
  " Set the number of columns for a tab
  let &softtabstop = s:tabsize
  " Visual width of a tabulation
  let &tabstop = s:tabsize

  " Use spaces instead of tabs
  set expandtab
endif

" Automatically insert indents
set autoindent

set smartindent

" Make <Tab> insert indents instead of tabs at the beginning of a line
set smarttab

" Don't wrap lines by default (see ftplugin)
set nowrap

" Break lines at convenient points (soft wrap)
set linebreak

" Line break on 500 characters
set textwidth=500

" Show line breaks (or nr2char(0x08627))
let &showbreak=nr2char(0x21AA)

" set fillchars+=stl:\ ,stlnc:\
" let &fillchars='vert:|,fold:-,stl:x,stlnc:y'

" Show invisible character (highlighted with NonText and SpecialKey)
set list
let &listchars='tab:'.nr2char(0x25B8).' '
let &listchars.=',trail:'.nr2char(0x00B7)
let &listchars.=',extends:'.nr2char(0x276F)
let &listchars.=',precedes:'.nr2char(0x276E)
let &listchars.=',nbsp:'.nr2char(0x005F)
let &listchars.=',eol:'.nr2char(0x00AC)

" Folding {{{1

" Add a bit extra margin to the left
"set foldcolumn=1

set foldmethod=indent
set foldnestmax=3
set nofoldenable

" Scrolling {{{1

" Start scrolling before the window border
if !&scrolloff
  set scrolloff=3
endif

if !&sidescrolloff
  set sidescrolloff=5
endif

if !&sidescroll
  set sidescroll=1
endif

"set display+=lastline

" Search {{{1

set gdefault

" Highlight search results
set hlsearch
" Search act like in modern browsers
set incsearch

" Ignore case when searching
set ignorecase
" Try to be smart about cases
set smartcase

" Turn magic on for regular expressions
set magic

" Colors {{{1

" FIXME: Graphical issues if not xterm-256color
" set term=$TERM
" set term=screen-256color
" set term=xterm-256color

" Background Color Erase (clearing bg color)
" if &term =~ '256color'
"   set t_ut=
" endif

" " Allow color schemes to do bright colors without forcing bold
" if &t_Co == 8 && $TERM !~# '^linux\|^Eterm'
"   set t_Co=16
" endif

" Enable syntax highlighting
if has('syntax')
  syntax enable
endif

set synmaxcol=500

" Cf. ~/.vim/plugin/colorcolumn.vim
if exists('+colorcolumn')
  set colorcolumn=80
  " Relative to textwidth
  "set colorcolumn=+1
  "let &colorcolumn=join(range(1,80),",")
endif

function! SetBackground(...)
  if !exists('*strftime')
    " let l:background = &background == 'light' ? 'dark' : 'light'
    if has('gui_running')
      let l:background = 'light'
    else
      let l:background = 'dark'
    endif
  else
    let l:sunrise = a:0 > 0 ? a:1 : 7
    let l:sunset = a:0 > 1 ? a:2 : 20
    let l:hour = strftime('%H')
    if l:hour > l:sunrise && l:hour < l:sunset
      let l:background = 'light'
    else
      let l:background = 'dark'
    endif
  endif
  if &background != l:background
    let &background = l:background
  endif
endfunction

call SetBackground()
try
  " let g:solarized_termtrans = 1
  colorscheme solarized
  call togglebg#map("<F5>")
catch /E185:/
  colorscheme default
endtry

" Hide line number background
"highlight LineNr ctermbg=none guibg=none

" " Custom Base16 colors
" " "hi clear SignColumn
" hi VertSplit ctermfg=10 ctermbg=10
" " hi ColorColumn ctermbg=10
" hi ColorColumn ctermfg=10 ctermbg=1
" "
" " hi LineNr ctermbg=10
" hi CursorLineNr ctermfg=12
" " hi CursorLine ctermbg=10

" " Not supported by Terminal.app
" " See settings/terminal.vim
" " hi Cursor ctermfg=1 ctermbg=7

" hi MatchParen ctermfg=13 ctermbg=11

" hi IncSearch ctermfg=10 ctermbg=9
" hi Search ctermfg=10 ctermbg=3
" "hi Visual ctermfg=11 ctermbg=3

" "hi Pmenu        ctermbg=240 ctermfg=12
" "hi PmenuSel     ctermbg=3   ctermfg=1
" "hi SpellBad ctermfg=1 ctermbg=0 cterm=underline
"
" "hi SpellBad ctermfg=13 ctermbg=1
" "hi SpellCap ctermfg=13 ctermbg=9
"
" "hi CursorColumn cterm=none ctermbg=darkgray ctermfg=white guibg=darkgray guifg=white
" call matchadd('ColorColumn', '\%81v', 100) "set column nr
"
" " Hightlight text over 80 chars
" "highlight OverLength ctermbg=red ctermfg=white guibg=#592929
" "match OverLength /\%>80v.\+/

" " Customize invisible characters color
" hi NonText ctermfg=11
" hi SpecialKey ctermfg=11

" Commands {{{1

" Enable soft wrap with ':Wrap'
command! -nargs=* Wrap setlocal wrap linebreak nolist

" Quick spell lang switch
command! En set spelllang=en
command! Fr set spelllang=fr

" Auto commands {{{1

" Show cursor line on active window only
" set cursorline
augroup HideCursorline
  autocmd!
  autocmd WinEnter * set cursorline
  autocmd WinLeave * set nocursorline
augroup END

augroup VimReload
  autocmd!
  autocmd BufWritePost $MYVIMRC nested source %
augroup END

" https://powerline.readthedocs.org/en/latest/tipstricks.html#vim
"if !has('gui_running')
"  augroup FastEscape
"    autocmd!
"    autocmd InsertEnter * set timeoutlen=0
"    autocmd InsertLeave * set timeoutlen=1000
"  augroup END
"endif

" Bindings {{{1

" Change leader
let g:mapleader = "\<Space>"

" Do not use arrows
" nnoremap <up> <nop>
" nnoremap <down> <nop>
" nnoremap <left> <nop>
" nnoremap <right> <nop>
" inoremap <up> <nop>
" inoremap <down> <nop>
" inoremap <left> <nop>
" inoremap <right> <nop>

" Move vertically on wrapped lines
nnoremap j gj
nnoremap k gk

" Quicker split navigation
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Repeat latest f, t, F or T [count] times
noremap <Tab> ;
" Repeat last command on next match
noremap ; :normal n.<CR>
" ; ? nnoremap Q :normal n.<CR>

" Edit in the same directory as the current file
cnoremap %% <C-R>=fnameescape(expand('%:h')).'/'<cr>

" Edit in window
noremap <Leader>ew :e %%
" Edit in split
noremap <Leader>es :sp %%
" Edit in vertical split
noremap <Leader>ev :vsp %%
" Edit in tab
noremap <Leader>et :tabe %%

" Quicker quit
noremap <Leader>q :q<CR>
" Save a file
noremap <Leader>w :w<CR>
" Save as root
noremap <Leader>W :w !sudo tee % > /dev/null<CR>

" Visually select the whole buffer
noremap <Leader>a <Esc>ggVG

" Clear highlighted search results
noremap <Leader><Space> :noh<CR>

" Remove trailing whitespaces (see TrimWhitespace())
" noremap <Leader><BS> :%s/\s\+$//e<CR>

" Sort css properties
" nnoremap <Leader>S ?{<CR>jV/^\s*\}?$<CR>k:sort<CR>:noh<CR>

" Git shortcuts
" noremap <Leader>b :Gblame<cr>
" noremap <Leader>l :!clear && git log -p %<CR>
" noremap <Leader>d :!clear && git diff %<CR>

" Open .vimrc in a new split
nnoremap <Leader>rc <C-w><C-v><C-l>:e $MYVIMRC<CR>

" 1}}}

" vim: foldenable foldmethod=marker et sts=2 sw=2 ts=2
