---
tmux_conf: yes
tmux_directory: .tmux
tmux_path: "$HOME/{{ tmux_directory }}"
tmux_colors: tmux-solarized-dark
tmux_plugin_manager: yes
tmux_plugin_manager_path: "{{ tmux_path }}/plugins"
tmux_plugin_install: yes

# set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com/user/plugin'
# set -g @plugin 'git@bitbucket.com/user/plugin'
tmux_plugins: []

# Y U NO {{ !role_path }}
tmux_role_path: ../roles/tmux

# Dynamic template:
# tmux_template_glob: tmux-*-*.conf.j2
# tmux_template_pattern: ^tmux-(.*)-(.*)\.conf\.j2$
# tmux_template_path: ../roles/tmux/templates
# "{{ lookup('first_found', tmux_templates, skip=true) }}"
# tmux_templates:
#   # - "{{ lookup('first_found', 'tmux.' + (ansible_distribution | lower) + '.conf.j2') }}"
#   - "{{ tmux_template_path }}/tmux-{{ ansible_distribution | lower }}.conf.j2"
#   - "{{ tmux_template_path }}/tmux-{{ ansible_os_family | lower }}.conf.j2"
#   - "{{ tmux_template_path + '/' + tmux_template }}"

# vim: foldmethod=marker foldmarker=START,END
# {% for template in lookup('fileglob', tmux_template_path + '/' + tmux_template_glob, wantlist=true) | sort %}
# # START {{ template | basename | regex_replace(tmux_template_pattern, '\2') | upper }}
# {{ lookup('template', template) }}
# # END {{ template | basename | regex_replace(tmux_template_pattern, '\2') | upper }}
# {% endfor %}
