---
tmux_conf: yes
tmux_install_plugins: yes
# tmux_update_plugins: all
tmux_plugin_manager: yes
tmux_plugins:
  - tmux-plugins/tpm
  - tmux-plugins/tmux-resurrect
  # - battery

tmux_template_path: ../roles/tmux/templates/tmux-*.conf.j2
tmux_template_name: ^tmux-(.*)-(.*)\.conf\.j2$
