---
- name: Update pacman cache
  pacman:
    update_cache: yes
  when: packages_update
  become: yes
  # register: pacman_cache
  # changed_when: "pacman_cache.msg != 'Updated the package master lists'"

- name: Upgrade pacman packages
  pacman:
    upgrade: yes
  when: packages_upgrade
  become: yes

# Arch User Repository
# TODO: ini_file
# https://github.com/jpic/jpic.pacman/blob/master/tasks/main.yml
# - name: "Check {{ pacman_conf }}"
#   lineinfile:
#     dest: "{{ pacman_conf }}"
#     state: present
#     line: "{{ item }}"
#   with_items:
#     - "[archlinuxfr]"
#     - "SigLevel = Never"
#     - "Server = http://repo.archlinux.fr/$arch"
