---
# - name: Setup Homebrew install path permissions
#   file:
#     path: "{{ homebrew_install_path }}"
#     group: admin
#     mode: 0775
#     state: directory
#     # recurse: true
#   become: yes

- name: Ensure Homebrew is installed
  command: "ruby -e '$(curl -fsSL {{ homebrew_install_script }})'"
  args:
    executable: "/usr/bin/env bash"
    creates: "{{ homebrew_install_path }}/{{ homebrew_creates }}"
    # creates: "{{ homebrew_install_path }}/bin/brew"
  when: homebrew_install

- name: Homebrew taps
  homebrew_tap:
    tap: "{{ item }}"
    state: "{{ homebrew_taps_state }}"
  with_items: "{{ homebrew_taps }}"

- name: Update Homebrew
  homebrew: update_homebrew=yes
  when: packages_update

- name: Upgrade Homebrew packages
  homebrew: upgrade_all=yes
  when: packages_upgrade

- name: Cleanup Homebrew
  shell: brew cleanup
  register: cleanup
  changed_when: "cleanup.stdout_lines | length > 0"
  when: homebrew_cleanup

# - name: Check Homebrew
#   command: brew doctor
#   register: brew_doctor
#   failed_when: brew_doctor != 0
#   when: homebrew_doctor

# TODO: check lineinfile homebrew.casks --appdir
