---
dependencies:

  - role: dotfiles
    paths:
      - name: bin
        src: bin
        dest: bin
      - name: shell
        prefix: .

  - role: block-in-file
    blocks: "{{ bash_blocks }}"

  - role: get-url
    files: "{{ bash_files }}"
