---
dependencies:

  - role: symlink
    dot_files:

      bin:
        # ~/.dotfiles/bin
        src: bin
        # ~/bin
        dest: bin

      shell:
        prefix: .

  - role: get-url
    files: "{{ bash_download }}"
