---
dependencies:

  - role: dotfiles
    paths:
      - name: bin
        src: "{{ dot_root }}/bin"
        dest: bin
      - name: shell
        prefix: .

  - role: get-url
    files: "{{ bash_download }}"
