#!/bin/sh

# Install bootstrap dependencies

set -eux

if [ -n "${PREFIX:-}" ]; then
  echo >&2 "Skip in termux"
  exit
fi

if command -v apk >/dev/null; then
  apk update --quiet
  apk add bash chezmoi curl sudo unzip
elif command -v apt-get >/dev/null; then
  apt-get update --quiet
  apt-get install --no-install-recommends --quiet --yes ca-certificates curl locales sudo unzip
elif command -v dnf >/dev/null; then
  dnf update --assumeyes --quiet
  dnf install --assumeyes --quiet chezmoi which unzip
elif command -v pacman >/dev/null; then
  pacman --sync --needed --noconfirm --quiet --refresh chezmoi sudo which
else
  echo >&2 "bootstrap-deps: unsupported package manager"
  exit 1
fi
