#!/usr/bin/env bash

set -euo pipefail

source home/.chezmoitemplates/helpers.sh

PATH="$HOME/.local/bin:$PATH"
# Add shims on PATH unless mise is already activated
if [ -z "${MISE_SHELL:-}" ]; then
  PATH="$PATH:$HOME/.local/share/mise/shims"
fi

DOCTOR="${DOCTOR:-false}"
DRYRUN="${DRYRUN:-false}"
UPDATE="${UPDATE:-false}"

BINS=("chezmoi")

check_chezmoi() {
  echo >&2 "Checking chezmoi..."
  cmd chezmoi --version
  if [ "$DOCTOR" = true ]; then
    cmd chezmoi doctor --no-network || true
  fi
  # set -- --debug --verbose "$@"
  chezmoi_args=""
  if [ "$DRYRUN" = true ]; then
    chezmoi_args="--dry-run"
  fi
  # NOTE: template output changes after installation (starship preset, gen config...)
  # out="$(chezmoi diff --exclude=scripts)"
  # if [ "$out" != "" ]; then
  #   echo >&2 "$out"
  #   echo >&2 "Expected empty diff without scripts, see output above"
  #   exit 1
  # fi
  cmd chezmoi apply $chezmoi_args
  out="$(cmd chezmoi diff $chezmoi_args)"
  if [ "$out" != "" ]; then
    echo >&2 "Expected empty diff: $out"
    exit 1
  fi
  out="$(cmd chezmoi status)"
  if [ "$out" != "" ]; then
    echo >&2 "Expected empty status: $out"
    exit 1
  fi
}

check_features() {
  echo >&2 "Checking features..."

  local features
  features="$(chezmoi cat-config | yq .data.features)"

  has_feature() {
    local name="$1"
    cmd yq --exit-status ".$name" <<<"$features" >/dev/null 2>&1
  }

  if has_feature atuin; then
    cmd atuin --version
    # cmd atuin dotfiles alias list
    # if [ "$DOCTOR" = true ]; then
    #   cmd atuin doctor
    # fi
    BINS+=("atuin")
    ble="$HOME/.local/share/blesh/ble.sh"
    if [ -f "$ble" ]; then
      cmd "$SHELL" "$ble" --version
    fi
  fi

  if has_feature bash; then
    cmd bash --version | head -n1
    BINS+=("bash")
  fi

  if has_feature bat; then
    if command -v batcat >/dev/null; then
      cmd batcat --version
      BINS+=("batcat")
    else
      cmd bat --version
      BINS+=("bat")
    fi
  fi

  if has_feature bottom; then
    cmd btm --version
    BINS+=("btm")
  fi

  if has_feature brew; then
    if [ -d /home/linuxbrew/.linuxbrew ]; then
      eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
    fi
    cmd brew --version
    if [ "$DOCTOR" = true ]; then
      # FIXME: ignore deprecated or disabled formulaes
      cmd brew doctor || true
    fi
    BINS+=("brew")
  fi

  if has_feature carapace; then
    cmd carapace --version
    BINS+=("carapace")
  fi

  if has_feature direnv; then
    cmd direnv --version
    cmd direnv export bash # "${SHELL##*/}"
    BINS+=("direnv")
  fi

  if has_feature eza; then
    cmd eza --version | head -n2 | tail -n1
    BINS+=("eza")
  fi

  if has_feature git; then
    cmd git --version
    BINS+=("git" "ghq" "lazygit")
  fi

  if has_feature helix; then
    cmd hx --version
    BINS+=("hx")
  fi

  if has_feature mise; then
    # cmd mise trust # --all
    cmd mise --version | head -n1
    # cmd mise ls
    # cmd mise trust --show
    if [ "$DOCTOR" = true ]; then
      cmd mise doctor
    fi
    BINS+=("mise")
  fi

  if has_feature node; then
    cmd node --version
    BINS+=("node")
  fi

  if has_feature nushell; then
    cmd nu --version
    BINS+=("nu")
  fi

  if has_feature neovim; then
    # cmd nvim --version 2>/dev/null | head -n1
    cmd nvim --version | head -n1
    if [ "$UPDATE" = true ]; then
      # if [ "$(nvim --headless -u NONE "+echo has('nvim-0.8')" +qa 2>&1)" = 1 ]; then
      cmd timeout 5m nvim --headless +LazyUpdate! +qa # >/dev/null
      echo
      # fi
    fi
    if [ "$DOCTOR" = true ]; then
      cmd timeout 5m nvim --headless +checkhealth +qa # >/dev/null
      echo
    fi
    BINS+=("nvim")
  fi

  if has_feature python; then
    # cmd command -v python
    cmd python --version || cmd python3 --version
    if command -v pipx >/dev/null; then
      cmd pipx --version
      BINS+=("pipx")
    fi
    cmd uvx --version
    BINS+=("uvx" "python")
  fi

  if has_feature ripgrep; then
    cmd rg --version | head -n1
    BINS+=("rg")
  fi

  if has_feature tmux; then
    cmd tmux -V 2>/dev/null
    if [ "$UPDATE" = true ]; then
      export TMUX_PLUGIN_MANAGER_PATH="$HOME/.config/tmux/plugins/"
      cmd timeout 5m ~/.config/tmux/plugins/tpm/bin/update_plugins all
    fi
    BINS+=("tmux")
  fi

  if has_feature topgrade; then
    cmd topgrade --version
    if [ "$DRYRUN" = true ]; then
      cmd topgrade \
        --disable=chezmoi \
        --dry-run # >/dev/null
    fi
    BINS+=("topgrade")
  fi

  if has_feature vim; then
    vim --version | head -n1
    BINS+=("vim")
  fi

  if has_feature zellij; then
    cmd zellij --version
    BINS+=("zellij")
  fi

  if has_feature zoxide; then
    cmd zoxide --version
    BINS+=("zoxide")
  fi

  if has_feature zsh; then
    cmd zsh --version | head -n1
    BINS+=("zsh")
  fi
}

check_versions() {
  echo >&2 "Checking versions..."

  os="$(uname -s)"

  # coreutils
  if [ "$os" = Darwin ]; then
    cmd gdd --version | head -n1
  else
    if ! cmd dd --version | head -n1; then
      echo >&2 "dd exited with code: $?"
    fi

    if command -v lsblk >/dev/null; then
      cmd lsblk --version # util-linux
    fi
  fi
  # cmd bws --version
  cmd fd --version
  # cmd ghostty --version | head -n1
  cmd jq --version
  cmd progress --version
  if [ "$os" != Darwin ]; then
    cmd ps --version
  fi
  cmd yq --version

  if command -v needs >/dev/null; then
    cmd needs \
      dd \
      fd \
      jq \
      progress \
      ps \
      yq \
      "${BINS[@]}" \
      "$@"
  fi
}

check_chezmoi
check_features
check_versions "$@"
chezmoi package diff --type=all

if [ "${DEBUG:-}" = true ]; then
  echo >&2 "DEBUG enabled"
  bash
fi
