#!/usr/bin/env bash

set -euo pipefail

source home/.chezmoitemplates/helpers.sh

PATH="$HOME/.local/bin:$PATH"

# Add shims on PATH unless mise is already activated
if [ -z "${MISE_SHELL:-}" ]; then
  PATH="$PATH:$HOME/.local/share/mise/shims"
fi

DOCTOR="${DOCTOR:-false}"
DRYRUN="${DRYRUN:-false}"
UPDATE="${UPDATE:-false}"

BINS=("chezmoi")

check_chezmoi() {
  echo >&2 "Checking chezmoi..."
  dry_run chezmoi --version
  if [ "$DOCTOR" = true ]; then
    dry_run chezmoi doctor --no-network || true
  fi
  # set -- --debug --verbose "$@"
  chezmoi_args=""
  if [ "$DRYRUN" = true ] || [ "${DRY_RUN:-}" = true ]; then
    chezmoi_args="--dry-run"
  fi
  # NOTE: template output changes after installation (starship preset, gen config...)
  # out="$(chezmoi diff --exclude=scripts)"
  # if [ "$out" != "" ]; then
  #   echo >&2 "$out"
  #   echo >&2 "Expected empty diff without scripts, see output above"
  #   exit 1
  # fi
  dry_run chezmoi apply $chezmoi_args
  out="$(dry_run chezmoi diff $chezmoi_args)"
  if [ "$out" != "" ]; then
    echo >&2 "Expected empty diff: $out"
    exit 1
  fi
  out="$(dry_run chezmoi status)"
  if [ "$out" != "" ]; then
    echo >&2 "Expected empty status: $out"
    exit 1
  fi
}

check_features() {
  echo >&2 "Checking features..."

  local features
  features="$(chezmoi cat-config | yq .data.features)"

  has_feature() {
    local name="$1"
    dry_run yq --exit-status ".$name" <<<"$features" >/dev/null 2>&1
  }

  if has_feature atuin; then
    dry_run atuin --version
    # dry_run atuin dotfiles alias list
    # if [ "$DOCTOR" = true ]; then
    #   dry_run atuin doctor
    # fi
    BINS+=("atuin")
    ble="$HOME/.local/share/blesh/ble.sh"
    if [ -f "$ble" ]; then
      dry_run "$SHELL" "$ble" --version
    fi
  fi

  if has_feature bash; then
    dry_run bash --version | head -n1
    BINS+=("bash")
  fi

  if has_feature bat; then
    if command -v batcat >/dev/null; then
      dry_run batcat --version
      BINS+=("batcat")
    else
      dry_run bat --version
      BINS+=("bat")
    fi
  fi

  if has_feature bottom; then
    dry_run btm --version
    BINS+=("btm")
  fi

  if has_feature brew; then
    if [ -d /home/linuxbrew/.linuxbrew ]; then
      eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
    fi
    dry_run brew --version
    if [ "$DOCTOR" = true ]; then
      # FIXME: ignore deprecated or disabled formulaes
      dry_run brew doctor || true
    fi
    BINS+=("brew")
  fi

  if has_feature carapace; then
    dry_run carapace --version
    BINS+=("carapace")
  fi

  if has_feature direnv; then
    dry_run direnv --version
    dry_run direnv export bash # "${SHELL##*/}"
    BINS+=("direnv")
  fi

  if has_feature eza; then
    dry_run eza --version | head -n2 | tail -n1
    BINS+=("eza")
  fi

  if has_feature git; then
    dry_run git --version
    BINS+=("git" "ghq" "lazygit")
  fi

  if has_feature helix; then
    dry_run hx --version
    BINS+=("hx")
  fi

  if has_feature mise; then
    dry_run mise --version | head -n1
    # dry_run mise ls
    # dry_run mise trust --show
    if [ "$DOCTOR" = true ]; then
      dry_run mise doctor
    fi
    BINS+=("mise")
  fi

  if has_feature node; then
    dry_run node --version
    BINS+=("node")
  fi

  if has_feature nushell; then
    dry_run nu --version
    BINS+=("nu")
  fi

  if has_feature neovim; then
    # dry_run nvim --version 2>/dev/null | head -n1
    dry_run nvim --version | head -n1
    if [ "$UPDATE" = true ]; then
      # if [ "$(nvim --headless -u NONE "+echo has('nvim-0.8')" +qa 2>&1)" = 1 ]; then
      # dry_run timeout 5m nvim --headless +LazyUpdate! +qa # >/dev/null
      dry_run timeout 5m nvim --headless try \| +LazyUpdate! \| +quitall \| catch \| +cquitall \| end
      echo
      # fi
    fi
    if [ "$DOCTOR" = true ]; then
      # dry_run timeout 5m nvim --headless +checkhealth +qa # >/dev/null
      dry_run timeout 5m nvim --headless try \| +checkhealth \| +quitall \| catch \| +cquitall \| end
      echo
    fi
    BINS+=("nvim")
  fi

  if has_feature python; then
    # command -v python
    python=python
    if ! command -v python >/dev/null && command -v python3 >/dev/null; then
      python=python3
    fi
    dry_run $python --version
    if command -v pipx >/dev/null; then
      dry_run pipx --version
      BINS+=("pipx")
    fi
    dry_run uvx --version
    BINS+=("uvx" "$python")
  fi

  if has_feature ripgrep; then
    dry_run rg --version | head -n1
    BINS+=("rg")
  fi

  if has_feature tmux; then
    dry_run tmux -V 2>/dev/null
    if [ "$UPDATE" = true ]; then
      export TMUX_PLUGIN_MANAGER_PATH="$HOME/.config/tmux/plugins/"
      dry_run timeout 5m ~/.config/tmux/plugins/tpm/bin/update_plugins all
    fi
    BINS+=("tmux")
  fi

  if has_feature topgrade; then
    dry_run topgrade --version
    if [ "$DRYRUN" = true ]; then
      dry_run topgrade \
        --disable=chezmoi \
        --dry-dry_run # >/dev/null
    fi
    BINS+=("topgrade")
  fi

  if has_feature vim; then
    dry_run vim --version | head -n1
    BINS+=("vim")
  fi

  if has_feature zellij; then
    dry_run zellij --version
    BINS+=("zellij")
  fi

  if has_feature zoxide; then
    dry_run zoxide --version
    BINS+=("zoxide")
  fi

  if has_feature zsh; then
    dry_run zsh --version | head -n1
    BINS+=("zsh")
  fi
}

check_versions() {
  echo >&2 "Checking versions..."

  os="$(uname -s)"

  # coreutils
  if [ "$os" = Darwin ]; then
    dry_run gdd --version | head -n1
  else
    if ! dry_run dd --version | head -n1; then
      echo >&2 "dd exited with code: $?"
    fi

    if command -v lsblk >/dev/null; then
      dry_run lsblk --version # util-linux
    fi
  fi
  # dry_run bws --version
  dry_run fd --version
  # dry_run ghostty --version | head -n1
  dry_run jq --version
  dry_run progress --version
  if [ "$os" != Darwin ]; then
    dry_run ps --version
  fi
  dry_run yq --version

  if command -v needs >/dev/null; then
    dry_run needs \
      dd \
      fd \
      jq \
      progress \
      ps \
      yq \
      "${BINS[@]}" \
      "$@"
  fi
}

main() {
  check_chezmoi

  # run chezmoi execute-template --refresh-externals=never '{{ .features | toPrettyJson }}'
  check_features

  # run chezmoi managed | grep '.chezmoiscript\|.local/bin\|install-'
  check_versions "$@"

  # run chezmoi package diff all

  if [ "${DEBUG:-}" = true ]; then
    echo >&2 "DEBUG enabled"
    bash
  fi
}

main "$@"
