#!/bin/bash
#
# bootfiles dotstrap
# Configuration file (each line is evaluated separately)

# GLOBAL ######################################################################

# Git
[ "$(uname)" == "Darwin" ] && CREDENTIAL="osxkeychain" || CREDENTIAL="cache"
# Style
indent_size=3

# PATHS #######################################################################

# Config files
sample_files=("npm=config/npmrc." "git=git/gitconfig.")
# Files ending by a dot are automatically symlinked in ~
# Directories copied to ~
directories=(".atom" ".vim")
# Cask CLI Applications
cask_files=("seil" "karabiner")

# IGNORE ######################################################################

ignore_global=(".DS_Store" ".gitignore" ".git" "*.md" "*.markdown")
# Files ending by a dot
ignore_dot=("*.")
# Specific directories
ignore_atom=(${ignore_global[@]} ${ignore_dot[@]})
ignore_vim=(${ignore_global[@]} ${ignore_dot[@]})
