#!/usr/bin/env bash
#MISE description="mise container"

# PROFILE=minimal mise container alpine up --build --detach
# PROFILE=minimal mise container alpine exec -it alpine-latest-minimal bash -i

# https://www.chezmoi.io/reference/commands/docker/

set -euxo pipefail

# CHEZMOI_PROFILE="${CHEZMOI_PROFILE:-}" # minimal
# EPHEMERAL="${EPHEMERAL:-false}"
# HEADLESS="${HEADLESS:-false}"

# PREFIX="${PREFIX:-}" # termux prefix
PROVIDER="${PROVIDER:-podman}"

tag_prefix=chezmoi

if [ $# -eq 0 ]; then
  echo >&2 "Usage: container <name[:version]>"
  exit 1
fi

NAME="$1"
shift

container_status() {
  $PROVIDER container inspect --format '{{.State.Status}}' "$@"
}

build_container() {
  name="$1"
  shift
  image_name="${name%:*}"
  if [[ "$name" = *:* ]]; then
    image_version="${name#*:}"
  else
    image_version=latest
  fi
  container="$tag_prefix-$image_name-$image_version"
  if [ "$image_name" = archlinux ] && [ "$(uname -m)" = arm64 ]; then
    image_name_arg=docker.io/ogarcia/archlinux
    # base, base-devel
  elif [ "$image_name" = macos ]; then
    image_name_arg=docker.io/sickcodes/docker-osx
  elif [ "$image_name" = termux ]; then
    image_name_arg=docker.io/termux/termux-docker
    # aarch64, arm, i686 (latest), x86_64
    if [ "$(uname -m)" = arm64 ]; then
      image_version_arg=aarch64
    else
      image_version_arg=x86_64
    fi
    # prefix=/data/data/com.termux/files/home
    # user=a0_test
    # TODO: prefix bootstrap only for termux in docker
  fi

  # case "$image_name" in
  # *) ;;
  # esac

  # container_user=test
  user="test"
  home="/home/$user"
  if [ "$image_name" = macos ]; then
    home="/Users/$user"
  elif [ "$image_name" = termux ]; then
    prefix=/data/data/com.termux/files
    home="$prefix/home"
    # container_user=root
    user=root # a0_test
  fi
  chezmoi_root="$home/.local/share/chezmoi"

  $PROVIDER build . \
    --build-arg=IMAGE_NAME="${image_name_arg:-$image_name}" \
    --build-arg=IMAGE_VERSION="${image_version_arg:-$image_version}" \
    --tag="$container"
  # --build-arg=USER="$user"

  # $PROVIDER run -it --name="$container" --rm "$container" "$@"
  # --userns=keep-id
  # --volume="$PWD:$chezmoi_root:ro"

  # # Stop running container
  # if [ "$(container_status "$container")" = running ]; then
  #   $PROVIDER stop "$container"
  # fi

  # # Remove existing container
  # if $PROVIDER container inspect "$container" >/dev/null; then
  #   $PROVIDER container rm "$container"
  # fi

  # Create container
  if ! $PROVIDER container inspect "$container" >/dev/null; then
    $PROVIDER create --name="$container" "$container"
  fi

  # https://github.com/sickcodes/Docker-OSX/issues/381
  if [ "$image_name" = macos ]; then
    # export XAUTHORITY="$HOME/.Xauthority"
    # xhost +local:root
    # xhost +
    # sudo usermod -aG kvm $USER
    $PROVIDER run -it --name="$container" \
      -device /dev/kvm \
      -p 50922:10022 \
      -p 22222:22 \
      -p 5999:5999 \
      -v /tmp/.X11-unix:/tmp/.X11-unix \
      -e "DISPLAY=:1" \
      -e AUDIO_DRIVER=pa,server=unix:/tmp/pulseaudio.socket \
      -v "/run/user/$(id -u)/pulse/native:/tmp/pulseaudio.socket" \
      -e MASTER_PLIST_URL="https://raw.githubusercontent.com/sickcodes/osx-serial-generator/master/config-custom.plist" \
      -e EXTRA="-vnc 0.0.0.0:99,password=off" \
      -e SHORTNAME=tahoe \
      "$container"
    return
  fi

  # Start container
  if [ "$(container_status "$container")" != running ]; then
    $PROVIDER start "$container"
  fi

  # $PROVIDER wait "$container"

  # Verify container is running
  status="$(container_status "$container")"
  if [ "$status" != running ]; then
    echo >&2 "Container $container is not running (status: $status)"
    exit 1
  fi

  command=(./script/bootstrap --verbose)
  if [ "$image_name" = termux ]; then
    prefix_command=(
      proot
      -b "$prefix/usr/etc/resolv.conf:/etc/resolv.conf"
      -b "$prefix/usr/etc/tls:/etc/ssl"
    )
    command=(
      "${prefix_command[@]}"
      "${command[@]}"
    )
    user=system
    $PROVIDER exec "$container" sh -euxc 'ln -sf ${PREFIX}/etc/termux/mirrors/default ${PREFIX}/etc/termux/chosen_mirrors'
    # NOTE: Cannot run 'pkg' command as root
    $PROVIDER exec --user=$user "$container" sh -euxc 'pkg update --quiet && pkg install --quiet --yes chezmoi proot'
  else
    # Wait for test user
    $PROVIDER exec "$container" sh -euxc "
      until id -u $user >/dev/null 2>&1; do
        echo 'Waiting for $user user to be created...'
        sleep 1
      done
    "
  fi
  $PROVIDER exec "$container" mkdir -p "$chezmoi_root"
  $PROVIDER container cp .chezmoiroot "$container:$chezmoi_root/"
  $PROVIDER container cp .chezmoiversion "$container:$chezmoi_root/"
  $PROVIDER container cp --overwrite home "$container:$chezmoi_root/"
  $PROVIDER container cp script "$container:$chezmoi_root/"
  $PROVIDER container cp test "$container:$chezmoi_root/"
  if [ -d test_support ]; then
    $PROVIDER container cp test_support "$container:$chezmoi_root/"
  fi
  $PROVIDER exec "$container" chown -R $user:$user "$home"

  $PROVIDER exec \
    --env=CHEZMOI_UPGRADE=true \
    --env=CI=true \
    --user="$user" \
    --workdir="$chezmoi_root" \
    "$container" "${command[@]}"

  $PROVIDER exec --user="$user" --workdir="$chezmoi_root" "$container" ./script/check
  $PROVIDER exec --user="$user" --workdir="$chezmoi_root" "$container" ./script/update
  $PROVIDER exec --tty --user="$user" --workdir="$chezmoi_root" "$container" ./script/test

  if [ $# -eq 0 ]; then
    # FIXME: override temporary directory to avoid permission issues in termux
    if [ "$image_name" = termux ]; then
      set -- bash --version
    else
      set -- bash -ic "chezmoi package diff all"
    fi
  fi
  $PROVIDER exec \
    --interactive \
    --tty \
    --user="$user" \
    --workdir="$chezmoi_root" \
    "$container" "$@"
  # $PROVIDER stop "$container"
}

if [ "$NAME" = all ]; then
  NAME=alpine,archlinux,debian,ubuntu,fedora,termux
fi

for name in ${NAME//,/ }; do
  time build_container "$name" "$@"
done
