#!/bin/bash
#
# Setup some defaults
# Steps specific to init folder & depending on OS type

UNAME=$(uname)

info "dot defaults" " " true

if [ -n "$indent_level" ]; then
	original_level=$indent_level
else
	indent_level=2
fi

case $UNAME in

	Darwin)

		# SYSTEM

		if ask "Set OS defaults ?" N; then
			((indent_level++))

			confirm "Apply SSD specific tweaks ?" N && \
				SSD_SPECIFIC=true

			confirm "Disable 'natural' scrolling ?" N && \
				DISABLE_NATURAL_SCROLLING=true

			[ "$(whoami)" != "root" ] && \
				warn "Administrator access may be required" " "
				# sudo -v

			osx_file=init/osx

			info "Executing $osx_file" "..." true

			if source $DOTFILES_DIR/$osx_file; then
				warn "Some changes may require a logout/restart to take effect" " "

				# Restart so that changes take effect
				#killall -HUP SystemUIServer
				# or
				# Kill affected applications
				# if ask "Kill affected applications now ? Terminal will be closed." N; then
				# 	for app in "Activity Monitor" "Address Book" "Calendar" "Contacts" "cfprefsd" \
				# 		"Dock" "Finder" "Mail" "Messages" "Safari" "SizeUp" "SystemUIServer" \
				# 		"Terminal" "Transmission" "Twitter" "iCal"; do
				# 		killall "${app}" > /dev/null 2>&1
				# 	done
				# fi

			else
				fail "$DOTFILES/$osx_file" "Failed"
				step_failed=true
			fi
		else
			((indent_level++))
		fi

		((indent_level--))

		# SUBLIME TEXT
		# TODO check for current symlink
		if ask "Set up Sublime Text ?" Y; then

			st_prefix=~/Library/Application\ Support/Sublime\ Text
			#st_suffix=/Packages/User/Preferences.sublime-settings

			# For each version of Sublime Text
			for dir in "$st_prefix"*; do
				if [ -d "$dir" ]; then
					found=true
					# Link theme & color scheme used in preferences
					st_theme="Spacegray"
					[ -d "$dir/Packages/Theme - $st_theme" ] || \
						ln -s "$DOTFILES_DIR/init/$st_theme" "$dir/Packages/Theme - $st_theme"
					st_color="Base16"
					[ -d "$dir/Packages/Color Scheme - $st_color" ] || \
						ln -s "$DOTFILES_DIR/init/$st_color" "$dir/Packages/Color Scheme - $st_color"
					# Backup then link preferences
					[ -f "$dir/Packages/User/Preferences.sublime-settings" ] && \
						mv "$dir/Packages/User/Preferences.sublime-settings" "$dir/Packages/User/Preferences.sublime-settings.bak"
					ln -s "$DOTFILES_DIR/init/Preferences.sublime-settings" "$dir/Packages/User/Preferences.sublime-settings"

					st_version=${f#$st_prefix}
					success "Sublime Text ${st_version:1:1}" "Symlinked Preferences.sublime-settings"
				fi
			done

			if [ ! "$found" = true ]; then
				fail "Application not found" "$st_prefix*"
				step_failed=true
			fi
		fi

		# TERMINAL

		# Search for the terminal configuration
		for f in `find $DOTFILES_DIR -name *.terminal`; do
			base_name=$(basename $f)
			THEME=${base_name%%.*}
			TERM_PROFILE=$f
		done

		# Get current profile
		CURRENT_PROFILE="$(defaults read com.apple.terminal 'Default Window Settings')"

		if [ ! -n "$THEME" ]; then
			fail "Terminal window" "Settings not found"
		elif [ ! -n "$TERM_PROFILE" ]; then
			fail "Terminal window" "$THEME.terminal not found"
		elif [ "${CURRENT_PROFILE}" != "${THEME}" ]; then
			info "Terminal window" "Currently uses ${CURRENT_PROFILE#$HOME/}" true
			if ask "Change window settings ?" Y true; then
				open "$TERM_PROFILE"
				sleep 1 # Wait a bit to make sure the theme is loaded
				defaults write com.apple.terminal 'Default Window Settings' -string "${TERM_PROFILE}" # FIXME
				defaults write com.apple.terminal 'Startup Window Settings' -string "${TERM_PROFILE}"

				success "Terminal window" "$THEME profile added"
			fi
		else
			success "Terminal window" "Already set to $THEME.terminal" true
		fi

		;;

	Linux)

		# APT-GET

		ubuntu_file=init/ubuntu

		if source $DOTFILES_DIR/$ubuntu_file; then
			success "apt-get" "Packages installed"
		else
			fail "$DOTFILES/$ubuntu_file" "Failed"
			step_failed=true
		fi

		;;

	*)

		warn "No configuration available" "$UNAME"

		;;

esac

# echo ''
indent_level=$original_level

[ "$step_failed" = true ] && return 1

return
