#!/usr/bin/env bash

# dot

# Yet Another Dotfiles Manager
# github.com/TheLocehiliosan/yadm/blob/master/yadm.md
# github.com/TheLocehiliosan/yadm/blob/master/yadm
# www.agwa.name/projects/git-crypt/

# set -o xtrace
set -o nounset
set -o errexit
set -o pipefail

# Extend matching operators
shopt -s extglob
# Loop on dotfiles
shopt -s dotglob
# # Do not loop on empty directory
# shopt -s nullglob
# # Recursive globbing (bash 4)
# shopt -s globstar

main() {
  unset -f main

  check_env

  # Paths
  # export DOT_ROOT=$HOME/.dotfiles
  # cd $(dirname "${BASH_SOURCE[0]}")/..
  # cd $(dirname "$(readlink "${BASH_SOURCE[0]}")")/..
  # DOT_ROOT=$(pwd -P)
  DOT_TARGET=$HOME
  DOT_SCRIPT="$DOT_ROOT/script"
  DOT_RC="$DOT_ROOT/.dotrc"

  source $DOT_SCRIPT/lib/import.sh # TODO import->load?
  # Load libraries
  import "lib/log"
  import "lib/usage"
  import "lib/utils"
  import "lib/prompt"
  import "lib/config"

  # Parse command options, main command empty by default
  DOT_CMD=
  parse_arguments "$@"

  # Read config file and set config variables -> ${!DOT_CONFIG_SECTION_*}
  # Looks for ${DOT_RC}.template
  config "$DOT_RC" || die "$DOT_RC"
  # var_dump "DOT_CONFIG_"

  # Set global script variables
  DEBUG="${DEBUG-${DOT_CONFIG_DEBUG-false}}"
  DRY_RUN="${DRY_RUN-${DOT_CONFIG_DRY_RUN-false}}"
  FORCE="${FORCE-${DOT_CONFIG_FORCE-false}}"
  TIMESTAMPS="${TIMESTAMPS-${DOT_CONFIG_TIMESTAMPS-false}}"

  # Platform name
  UNAME=$(uname -s) # Darwin|Linux

  # Git config credential helper
  if [[ "$UNAME" = "darwin" ]]; then
    DOT_USER_GIT_CREDENTIAL="osxkeychain"
  else
    DOT_USER_GIT_CREDENTIAL="cache"
  fi

  # Greeting
  log_info "Hello, $DOT_USER_NICK" "$DOT_USER_NAME <$DOT_USER_EMAIL>"
  log_debug "Debug mode enabled" "$BASH_VERSION"
  log_debug "DRY RUN" "$DRY_RUN"

  # Start script
  boot "$DOT_CMD"
}

check_env() {
  MIN_BASH_VERSION=3
  ENV_BASH_VERSION=${BASH_VERSION%%[^0-9]*}

  if [[ $ENV_BASH_VERSION -lt $MIN_BASH_VERSION ]]; then
    die "This script requires bash > ${MIN_BASH_VERSION}"
  fi

  # Check files?
  if [[ ! -d "${DOT_ROOT-}" ]]; then
    die "${DOT_ROOT-undefined}: '\$DOT_ROOT' is not a directory"
  fi
}

parse_arguments() {
  while [[ $# -gt 0 ]]; do
    local key=$1
    local val=${2-}
    # echo "Parsing $1 (#$#)"
    case $key in
      # All dot commands
      install|uninstall|update|list|link|unlink|defaults)
        # Check if a command is already registered
        [[ -n "${DOT_CMD-}" ]] && usage 1 "Too many arguments: $key"
        key="dot_$key"
        if is_function $key; then
          # Register main action
          DOT_CMD="$key"
        else
          log_error "Unsupported command" "$key"
          die "$key"
        fi
        shift
        ;;
      -v|--verbose|--debug)
        DEBUG=true
        shift
        ;;
      -d|--dry-run)
        DRY_RUN=true
        shift
        ;;
      # -t|--target)
      # 	shift
      #
      # 	# Loop until next '-', cannot handle ' -' without quotes
      # 	# while [[ $# -gt 0 ]] && [[ $1 != -* ]]; do
      # 	# 	DOT_TARGET+=" $1"
      # 	# 	shift
      # 	# done
      #
      # 	# Check value until the delimiter '-' is found or end of args
      # 	if [[ $# -gt 0 ]] && [[ ! -z "$val" ]] && [[ $val != -* ]]; then
      # 		shift
      # 	else
      #         # Ask for the missing value
      #         local prompt="Please specify a target path (default: $HOME): "
      #         read -e -r -p "$prompt" val # -i "$HOME"
      #         # Use default
      #         [[ -z "$val" ]] && break
      # 	fi
      # 	# Check destination path
      # 	[[ -d "$val" ]] || usage 1 "Not a directory: $key $val"
      # 	DOT_TARGET="$val"
      # 	;;
      # --uninstall)
      #   UNINSTALL=true
      #   shift
      #   ;;
      -h|--help)
        usage
        ;;
      *)
        usage 1 "Unknown option: $key"
        ;;
    esac
  done
}

# Dot command
boot() {
  local cmd=$1

  case $cmd in
    '') # Default process
      if confirm "**Update repository" "" Y; then
        dot_update
      fi
      if confirm "**Install packages" "" Y; then
        dot_install
      fi
      if confirm "**Symlink files to $DOT_TARGET" "" Y; then
        dot_link
      fi
      if confirm "**Setup $UNAME defaults" "" Y; then
        dot_defaults
      fi
      ;;
    *) # Execute function
      $cmd
      ;;
  esac

  if [[ $? -eq 0 ]]; then
    log_success "Done" "-> $?"
  else
    log_error "Error" "-> $?"
    return $?
  fi
}

# Required command
require() {
  local cmd="$1"

  command -v $cmd >/dev/null 2>&1 || {
    log_error "The command '${cmd}' could not be located"
    exit 1
  }
}

# Install packages

dot_install() {
  import "install"

  # Install dependencies
  install_packages || \
    log_warn "Install aborted" "$?"
}

dot_uninstall() {
  import "install"

  uninstall_packages || \
    log_warn "Uninstall aborted" "$?"
}

dot_update() {
  require "git"
  import "lib/git"

  # Pulls
  git_submodule_update
}

# Bootstrap dotfiles

dot_list() {
  import "bootstrap/symlinks"
  bootstrap_symlinks list
}

dot_link() {
  import "bootstrap/templates"
  import "bootstrap/symlinks"

  bootstrap_templates && \
    bootstrap_symlinks link || \
    log_warn "Bootstrap aborted" "$?"
}

dot_unlink() {
  import "bootstrap/symlinks"

  bootstrap_symlinks unlink || \
    log_warn "Bootstrap unlink aborted" "$?"
}

# Setup platform specific defaults

dot_defaults() {
  import "defaults"

  # Set platform defaults
  platform_defaults || \
    log_warn "Defaults aborted" "$?"
}

[[ "$0" == "$BASH_SOURCE" ]] && main "$@"
