#!/bin/bash
#
# Setup some defaults

UNAME=$( uname )

info "dot setup" " " true

if [ -n "$indent_level" ]; then
	original_level=$indent_level
else
	indent_level=2
fi

do_cask () {
	((indent_level++))
	local cask=$1
	if silent brew cask install $cask; then
		local file=$DOTFILES_DIR/cask/$cask
		local app="$(tr '[:lower:]' '[:upper:]' <<< ${cask:0:1})${cask:1}"
		if source_file $file | sed "s/^/         /"; then
			success "$app" " "
			open /Applications/$app.app
		else
			fail "$app" " "
		fi
	fi
	((indent_level--))
}

case $UNAME in

	Darwin)

		# HOMEBREW
		homebrew_file=init/.homebrew
		info "Executing $homebrew_file" "..." true
		if silent source "$homebrew_file"; then
			if ask "Configure cask apps ?"; then
				for cask in ${cask_files[@]}; do
					do_cask "$cask"
				done
			fi

			# TODO

			# https://gist.github.com/DanHerbert/9520689
			# brew install node --without-npm
			# echo prefix=~/.node >> ~/.npmrc
			# curl -L https://www.npmjs.org/install.sh | sh
			# https://gist.github.com/lakenen/676c60e85779b190c2d4
			# npm install -g ...
			success "Homebrew" "$homebrew_file"
		else
			fail "Homebrew" "$homebrew_file"
			step_failed=true
		fi

		;;

	# Linux) ;;	# https://github.com/Homebrew/linuxbrew ?

	*)

		warn "No setup available" "$UNAME"

		;;

esac

# echo ''
indent_level=$original_level

[ "$step_failed" = true ] && return 1

#return 0
