#!/bin/bash
#
# Setup some defaults

# # Import functions
# lib=$DOTFILES_DIR/lib
# CONFIG_FILE=$DOTFILES_DIR/config
# source $lib/readconf
# source $lib/print
# source $lib/ask

UNAME=$( uname )

info "'dot setup' is an alias to this step" " " true

if [ -n "$indent_level" ]; then
	original_level=$indent_level
else
	indent_level=2
fi

do_cask () {
	local cask=$1
	((indent_level++))
		if silent brew cask install $cask; then
			((indent_level++))
			local file=$DOTFILES_DIR/cask/$cask
			local app="$(tr '[:lower:]' '[:upper:]' <<< ${cask:0:1})${cask:1}"
			if silent source_file $file; then
				success "$app" " "
				open /Applications/$app.app
				((indent_level--))
			else
				fail "$app" " "
				((indent_level--))
			fi
		fi
	((indent_level--))
}

case $UNAME in

	Darwin)

		# HOMEBREW

		homebrew_file=init/Homebrew.sh
		if ask "Homebrew ?" Y; then
			if silent source "$homebrew_file"; then
				for cask in ${cask_files[@]}; do
					do_cask "$cask"
				done
				success "Homebrew" "$homebrew_file"
			fi
		else
			skipped "Homebrew" "$homebrew_file"
		fi


		;;

		# apt-get stuff ?
		# https://github.com/Homebrew/linuxbrew ?
	*)

		warn "No setup available" "$UNAME"

		;;

esac

# echo ''
indent_level=$original_level

[ "$step_failed" = true ] && return 1

#return 0
