#!/usr/bin/env bash
#MISE description="Measure aggregate shell startup time (JSON output)"
#USAGE arg "[shell]" help="Shell to measure (default: current shell)" {
#USAGE   choices "bash" "zsh"
#USAGE }

# https://github.com/shunk031/dotfiles/blob/master/scripts/run_benchmark.sh

set -euo pipefail

BENCH_ITERATIONS="${BENCH_ITERATIONS:-10}"
UNAME="${UNAME:-$(uname -s)}"

command_time() {
  local file="$1.txt"
  local time_args=("-a" "-o" "$file")
  shift
  if [ "$UNAME" = Darwin ]; then
    TIMEFORMAT="%R"
  else
    time_args+=("-f" "%e")
  fi
  command time "${time_args[@]}" -- "$@"
}

initial_time() {
  local output="$1"
  shift

  echo "initial startup: $*" >&2
  command_time "$output" "$@"

  column -t <"$output.txt" | cut -d' ' -f1
}

average_time() {
  local iterations="$1"
  shift
  local output="$1"
  shift

  for i in $(seq 1 "$iterations"); do
    echo "startup $i/$iterations: $*" >&2
    command_time "$output-$i" "$@"
  done

  awk '{ total += $1 } END { print total/NR }' "$output-"*.txt
}

main() {
  if [ $# -gt 1 ]; then
    echo "startup: expected at most 1 argument, got $#" >&2
    exit 2
  fi

  local shell="${1:-${SHELL##*/}}"
  shell="${shell:-bash}"

  case "$shell" in
  bash | zsh | dummy) ;;
  *)
    echo "startup: invalid shell '$shell', expected bash or zsh" >&2
    exit 2
    ;;
  esac

  local cmd="$shell -ci exit"
  local name="${cmd%% *}"

  local tmpdir
  tmpdir="$(mktemp -d)"
  local output="${tmpdir}/startup-$name"

  export SHELDON_DATA_DIR="$tmpdir/sheldon-data"

  # shellcheck disable=SC2086
  initial_startup_time="$(initial_time "$output" $cmd)"

  # shellcheck disable=SC2086
  average_startup_time="$(average_time "$BENCH_ITERATIONS" "$output" $cmd)"

  cat <<EOF
[
    {
        "name": "$name average startup time",
        "unit": "Second",
        "value": ${average_startup_time}
    },
    {
        "name": "$name initial startup time",
        "unit": "Second",
        "value": ${initial_startup_time}
    }
]
EOF
}

main "$@"
