#!/bin/sh
#MISE description="Trace sourced files during shell init"
# Usage: script/trace bash
#        script/trace zsh
set -eu

shell="${1:-bash}"

case "$shell" in
  bash)
    PS4='+ ${BASH_SOURCE[0]##*/}:${LINENO}: ' \
      bash -xic exit 2>&1 \
      | grep -E '^\+* [^:]+:[0-9]+: (\. |source )' \
      | sed "s|$HOME|~|g"
    ;;
  zsh)
    zsh --source-trace -ic exit 2>&1 \
      | sed "s|$HOME|~|g"
    ;;
  *)
    echo >&2 "Usage: script/trace bash|zsh"
    exit 1
    ;;
esac
