---
packages:
  # TODO: only if installed via brew
  # if [ "$(claude config set --global autoUpdates false)" = true ]; then
  #   claude config set --global autoUpdates false
  # fi
  claude-code:
    enabled: '{{ and .features.ai (eq .osIDLike "arch" "darwin" "fedora" "windows") }}'
    nameOverwrite:
      npm: "@anthropic-ai/claude-code"
      windows: Anthropic.Claude
    type: '{{ eq .osIDLike "arch" | ternary "aur" (eq .osIDLike "darwin" "fedora" | ternary "cask" "npm") }}'
  # https://github.com/Maciek-roboblog/Claude-Code-Usage-Monitor/issues/119
  # claude-monitor:
  #   enabled: "{{ .features.ai }}"
  #   type: uv
  # claude:
  #   enabled: '{{ and .features.ai (eq .osIDLike "darwin" "windows") (not .headless) }}'
  #   nameOverwrite:
  #     windows: Anthropic.ClaudeCode
  #   type: '{{ eq .osIDLike "darwin" | ternary "cask" nil }}'
