# User completions (generated by chezmoi from #USAGE directives)
fpath=("$HOME/.local/share/zsh/completions" $fpath)

zmodload zsh/complist
autoload -U +X compinit

# -C skips security check and reuses the completion dump file
zcompdump="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/zcompdump"
[ -d "${zcompdump%/*}" ] || mkdir -p "${zcompdump%/*}"
compinit_flags=(-d "$zcompdump")
now=$(date +%s)
mtime=$(stat -f%m "$zcompdump" 2>/dev/null || stat -c%Y "$zcompdump" 2>/dev/null || echo 0)
# Reuse cached dump if less than a day old
if [ "$((now - mtime))" -lt 86400 ]; then
  compinit_flags+=(-C)
fi
compinit "${compinit_flags[@]}"

# Group header
zstyle ':completion:*' format $'\e[2;37mCompleting %d\e[m'

# Interactive menu on first tab
zstyle ':completion:*' menu yes select

# Space accepts completion without doubling the trailing space
bindkey -M menuselect ' ' accept-line

# Group completions by type
zstyle ':completion:*' group-name ''

# Show descriptions alongside completions
zstyle ':completion:*' verbose yes

# Color completions using LS_COLORS
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"

# Case-insensitive, partial-word, then substring matching
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|=*' 'l:|=* r:|=*'

# Show all completions without prompting (default: 100)
LISTMAX=200
