---
extraPackages:
  atuin: # ddworken/hishtory, dvorka/hstr
    # name: atuin atuin-sync
    condition: >
      and .features.atuin (not (or
        (and (eq .osID "debian") (le (int .osVersion) 12))
        (and (eq .osID "ubuntu") (le (float64 .osVersion) 24.04))
      ))
    nameOverwrite:
      windows: atuin.atuin
    type: eq .osIDLike "windows" | ternary "winget" nil
