---
packages:
  atuin: # ddworken/hishtory, dvorka/hstr
    # name: atuin atuin-sync
    enabled: "{{ .features.atuin }}"
  ble.sh:
    enabled: '{{ ne .osID "alpine" }}'
    name: github:akinomyoga/ble.sh
    type: mise
