# TODO: https://docs.atuin.sh/self-hosting/server-setup/
auto_sync = false
common_subcommands = [
  "apt",
  "cargo",
  "composer",
  "dnf",
  "docker",
  "gh",
  "git",
  "glab",
  "go",
  "ip",
  "kubectl",
  "nix",
  "nmcli",
  "npm",
  "pecl",
  "pnpm",
  "podman",
  "port",
  "systemctl",
  "tmux",
  "yarn",

  # https://github.com/atuinsh/atuin/issues/2458
  "c",
  "d",
  "g",
  "k",

  "chezmoi",
  "just",
  "make",
  "mise",
  "task",
]
# enter_accept = true
inline_height = 0
keymap_mode = "vim-insert"
prefers_reduced_motion = true # NO_MOTION
show_preview = true
update_check = false

[dotfiles]
enabled = true

[keys]
# If disabled, using the up/down key won't exit the TUI when scrolled past the first/last entry.
scroll_exits = false
# The left arrow key will exit the TUI when scrolling before the first character
exit_past_line_start = false
# The right arrow key performs the same functionality as Tab and copies the selected line to the command line to be modified.
accept_past_line_end = false
