---
packages:
  topgrade:
    enabled: '{{ and .features.topgrade (ne .osIDLike "debian") }}'
    nameOverwrite:
      arch: topgrade-bin
      manjaro: topgrade
      windows: topgrade-rs.topgrade
    type: |-
      {{ if and (eq .osIDLike "arch") (ne .osID "manjaro") -}}
      aur
      {{- else if eq .osIDLike "fedora" -}}
      brew
      {{- end -}}
