---
# pre_commands:
#   Pre commands: set -x; chezmoi status && chezmoi diff
commands:
  # Dotfiles: set -x; chezmoi apply --init --interactive --verbose
  Makefiles: |
    find ~/.config -mindepth 2 -maxdepth 2 -type f -name Makefile \
      -exec sh -c 'dir="$(dirname {})"; set -x; cd "$dir" && make' \;
# post_commands:
#   Post commands: set -x; chezmoi status && chezmoi diff

git:
  # https://github.com/topgrade-rs/topgrade/blob/v16.0.4/src/steps/git.rs#L36
  pull_predefined: false
  repos:
    # - ~/.local/share/*/
    - ~/code/*/
    - ~/projects/*/
    - ~/src/*/*/*/

misc:
  disable:
    - containers
    - git_repos
    - node
    - vagrant
  # Do not ask to retry failed steps (default: false)
  no_retry: true
  # Skip sending a notification at the end of a run
  skip_notify: true
