---

# http://benoliver999.com/2014/02/18/weechatconf/
# https://robots.thoughtbot.com/weechat-for-slacks-irc-gateway
# https://wiki.archlinux.org/index.php/WeeChat

weechat_brew_install_options:
  - with-lua
  - with-python
  - with-perl
  - with-ruby
