---
dependencies:
  # - role: ini_block
  #   /etc/pacman.conf:
  #     [archlinuxfr]
  #     SigLevel = Never
  #     Server = http://repo.archlinux.fr/$arch

  - role: package
    packages:
      - yaourt

  - role: dotfiles
    role_dir: roles/packages
    paths:
      - name: pacman-yaourt
        prefix: .
