---
# github.com/mjanser/ansible-role-tmux

- name: Ensure ~/.tmux.conf is sourcing ~/.tmux/tmux.conf
  lineinfile:
    dest: "{{ dot_home }}/.tmux.conf"
    line: "source ~/.tmux/tmux.conf"
    create: yes
  # become: yes
  # become_user: "{{ item }}"
  # when: item in home_dirs.stdout_lines
  # with_items: "{{ tmux_users }}"

- name: Ensure .tmux/plugins exists
  file:
    path: "{{ destination }}/plugins"
    state: directory

- name: Clone tmux plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: "{{ destination }}/plugins/tpm"

# TODO: tpm C-<prefix> I
