---
dependencies:

  - role: package
    packages: "{{ weechat_packages }}"

  # TODO

  # - role: symlink
  #   dot_files:
  #     weechat:
  #       dest: .weechat

  # - role: template
  #   dot_files:
  #     weechat:
  #       dest: .weechat
