---
- name: Check if node is installed
  command: node --version
  ignore_errors: yes
  changed_when: false
  register: node_version

- include: debian.yml
  when: node_version.rc != 0 and
    ansible_os_family == 'Debian'

- include: redhat.yml
  when: node_version.rc != 0 and
    ansible_os_family == 'RedHat'
