---
# - name: Check if npm is installed
#   command: npm -v
#   ignore_errors: yes
#   changed_when: false
#   register: npm_version

# - debug: var=npm_version #.stdout
# - fail:

- name: Ensure npm is installed
  stat:
    path: /usr/bin/npm
  register: npm_installed

- include: debian.yml
  when: not npm_installed.stat.exists and
    ansible_os_family == 'Debian'
    # {{ npm_installed_version.rc | default(false) }} != 0 and

- include: redhat.yml
  when: not npm_installed.stat.exists and
    ansible_os_family == 'RedHat'
    # {{ npm_installed_version.rc | default(false) }} != 0 and
