---
dependencies:

  - role: symlink
    dot_files:
      bin:
        src: bin # ~/.dotfiles/bin
        dest: bin # ~/bin
      bash:
        prefix: .

  - role: get-url
    files:
      spark:
        url: "https://raw.githubusercontent.com/holman/spark/master/spark"
        dest: bin
        mode: 0755
      git-prompt.bash:
        url: "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh"
        dest: .bash.d/lib
