# Active directives only, non-default aerc settings
# Full reference and defaults: man aerc-config

[general]
pgp-provider = gpg

[ui]
mouse-enabled=true
styleset-name=tokyonight_storm.ini

[viewer]
header-layout=From|To,Cc|Bcc,Date,Subject|Labels # |DKIM|SPF|DMARC
always-show-mime=true

[compose]
empty-subject-warning=true

[filters]
text/plain=colorize
text/calendar=calendar
message/delivery-status=colorize
message/rfc822=colorize
text/html=! html
.headers=colorize
