---
- name: "Insert/update {{ lines | length }} lines"
  lineinfile:
    dest: "{{ item.dest }}"
    line: "{{ item.line }}"
    backup: "{{ item.backup | default(lineinfile_backup) }}"
    create: "{{ item.create | default(lineinfile_create) }}"
    state: "{{ item.state | default(omit) }}"
  with_items: "{{ lines }}"
  when: "{{ item.when | default(true) }}"
