---
packages:
  helix:
    enabled: '{{ and .features.helix (ne .osIDLike "debian") }}'
    nameOverwrite:
      alpine: helix tree-sitter-grammars
      android: helix helix-grammars
      windows: helix.helix
  helixbinhx:
    enabled: '{{ and .features.helix (eq .osID "arch") }}' # ne .osID "manjaro"
    type: '{{ eq .osIDLike "arch" | ternary "aur" nil }}'
