{{- /* chezmoi:modify-template */ -}}
{{- $config := includeTemplate "dot_config/helix/.config.yaml" | fromYaml -}}
{{ includeTemplate "block-in-file.tmpl" (dict
"chezmoi" .chezmoi
	"contents" ($config | toToml)
) -}}
