---
- name: Check if node is installed
  command: node --version
  register: node_version_result
  changed_when: node_version_result.rc != 0
  failed_when: false
  check_mode: no # ansible >= 2.2
  # always_run: yes

- name: Check if npm is installed
  command: npm --version
  register: npm_version_result
  changed_when: npm_version_result.rc != 0
  failed_when: false
  check_mode: no # ansible >= 2.2
  # always_run: yes

- name: Register node and npm version
  set_fact:
    node_installed: "{{ node_version_result.rc == 0 and npm_version_result.rc == 0 }}"
    node_installed_version: "{{ node_version_result.stdout if node_version_result.stdout is defined and node_version_result.rc != 0 else false }}"
    npm_installed_version: "{{ npm_version_result.stdout if npm_version_result.stdout is defined and npm_version_result.rc != 0 else false }}"
