---
dependencies:

  - role: package
    packages:
      - "{{ 'git' if ansible_distribution != 'Debian' else 'git-core' }}"

  - role: symlink
    dot_files:
      git:
        prefix: .

  - role: template
    dot_files:
      git:
        prefix: .
