---
dependencies:

  - role: package
    packages:
      - git

  #   when: "ansible_os_family == 'Debian'"
  # - role: brew
  #   packages:
  #     - git
  #   when: "ansible_os_family == 'Darwin'"

  - role: template
    role_dir: git

  - role: symlink
    role_dir: git
