---
# https://github.com/transcode-open/apt-cyg
# https://github.com/naokirin/ansible-apt-cyg-module
- name: "{{ packages | length }} packages : {{ packages_state }}"
  apt_cyg:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default(packages_state) }}"
  with_items: "{{ apt_cyg_packages }}"
  when: packages_install
