#!/usr/bin/env bash
#
# ~/.bash_prompt
#
# github.com/necolas/dotfiles
# github.com/mathiasbynens/dotfiles/blob/master/.bash_prompt
# github.com/demure/dotfiles/blob/master/subbash/prompt

# user=$(whoami)
# host=$(hostname)

PROMPT_SYMBOL="› " # $ ✓ →
PROMPT_SYMBOL_ERROR="× " # ! ×

PROMPT_COMMAND='prompt_command'
PS2="${PROMPT_SYMBOL:->} "

# PROMPT_COMMAND='__git_ps1 "\u at \h in \w" "\n\\\$ "'
# __git_ps1 " on %s" | sed -re "s/(\son\s)(\W*)(\w+)(\W*)/\1\2$red\3$white\4/"

# Colored hints (only when used with 2 arguments as prompt command)
GIT_PS1_SHOWCOLORHINTS=1

# * unstaged changes
# + staged changes
GIT_PS1_SHOWDIRTYSTATE=1

# $ stashed items
GIT_PS1_SHOWSTASHSTATE=1

# % untracked files
GIT_PS1_SHOWUNTRACKEDFILES=1

# Difference between HEAD and its upstream:
# <           behind
# >           ahead
# <>          diverged
# =           no difference
# GIT_PS1_SHOWUPSTREAM="auto"
# auto        default?
# verbose     show number of commits ahead/behind (+/-) upstream
# name        if verbose, then also show the upstream abbrev name
# legacy      don't use the '--count' option available in recent
#             versions of git-rev-list
# git         always compare HEAD to @{upstream}
# svn         always compare HEAD to your SVN upstream

prompt_right() {
  local text=${1:-}
  local color=${2:-}
  local margin=${3:-0}

  if [[ ! -n "$COLUMNS" ]]; then
    COLUMNS=$(tput cols)
  fi

  if [[ -n "$color" ]]; then
    text="${color}${text}"
    margin=$((${margin} - ${#color}))
  fi

  printf "%*s" "$((${COLUMNS} - ${margin}))" "${text}"
}

prompt_command() {
  # Exit code
  local exit=$?

  # ~/.colors
  local c_text="\[${bblack}\]"
  local c_reset="\[${reset}\]"
  local c_bold="\[${bold}\]"
  local c_blue="\[${blue}\]"
  local c_bblue="\[${bblue}\]"
  local c_cyan="\[${cyan}\]"
  local c_red="\[${red}\]"
  local c_white="\[${white}\]"
  local c_yellow="\[${yellow}\]"

  # Start of the primary prompt
  local p='\n'
  # Right aligned text
  local p_right='$(date +%H:%M:%S)'
  # End of the first prompt line (before symbol and command line prompt)
  local p_end='\n'

  # Default symbols
  local p_symbol="${PROMPT_SYMBOL:-$ }"
  local p_symbol_error="${PROMPT_SYMBOL_ERROR:-! }"

  # Set the terminal title to the current working directory
  p+='\[\033]0;\w\007\]'

  # Move the cursor position and print right aligned text
  p+='\[$(tput sc; prompt_right "'${p_right}'" "'${c_text}'"; tput rc)\]'

  # Red if root
  if [[ "$USER" == "root" ]]; then
    p+="$c_red"
  else
    p+="$c_blue"
  fi
  # Username
  p+='\u'
  p+="$c_reset"

  # if [[ ! "$HOSTNAME" =~ "$USER" ]]; then
  if [[ "$USER" != "$HOSTNAME" ]]; then
    p+="$c_text"
    p+=' at '
    p+="$c_reset"
    # Highlight the hostname when connected via SSH
    if [[ -n "${SSH_TTY}" ]]; then
      p+="$c_bold"
      p+="$c_red"
    else
      p+="${c_bblue}"
    fi
    # Hostname
    p+='\h'
    p+="$c_reset"
  fi

  p+="$c_text"
  p+=' in '
  p+="$c_reset"
  p+="$c_white"
  # Working directory
  p+='\w'
  p+="$c_reset"

  # Exit code
  if [[ $exit -eq 0 ]]; then
    p_end+="${c_white}${p_symbol}${c_reset}"
  else
    p_end+="${c_red}${p_symbol_error}${c_reset}"
  fi

  # ~/.git-prompt.sh
  local git_format="${c_text} on ${c_reset}%s"
  __git_ps1 "${p}" "${p_end}" "${git_format}"

  # Change master branch color from green to yellow
  local git_branch='__git_ps1_branch_name'
  if [[ "${!git_branch}" == "master" ]]; then
    PS1=${PS1/"\[\e[32m\]\${${git_branch}}"/"${c_yellow}\${${git_branch}}"}
  fi
}
