#
# ~/.bashrc
#

# https://github.com/mathiasbynens/dotfiles/blob/master/.bash_profile

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# Append to the Bash history file, rather than overwriting it
shopt -s histappend

# Autocorrect typos in path names when using 'cd'
shopt -s cdspell

# Enable some Bash 4 features when possible:
#   'autocd', e.g. '**/qux' will enter './foo/bar/baz/qux'
#   Recursive globbing, e.g. 'echo **/*.txt'
for option in autocd globstar; do
  shopt -s "$option" 2> /dev/null
done

# Bash prompt
PROMPT_COMMAND='prompt_command'

# PS1
PROMPT_SYMBOL="› " # $ ✓ →
PROMPT_SYMBOL_ERROR="× " # ! ×

PS2="${PROMPT_SYMBOL:->} "

# Load bash configuration
source ~/.bash.d/init.bash
