#
# ~/.bashrc
#

PROMPT_SYMBOL="› " # $ ✓ →
PROMPT_SYMBOL_ERROR="× " # ! ×

# Load bash configuration
source ~/.bash.d/init.bash

load ~/.{exports,path,extra}
# ~/.exports can be used to export variables
# ~/.path can be used to extend '$PATH'.
# ~/.extra can be used for other settings you don’t want to commit.

# for file in ~/.{exports,path,extra}; do
#   [[ -r "$file" ]] && [[ -f "$file" ]] && source "$file"
# done
# unset file
