#!/usr/bin/env bash
#
# ~/.bash_prompt
#
# github.com/necolas/dotfiles
# github.com/mathiasbynens/dotfiles/blob/master/.bash_prompt
# github.com/demure/dotfiles/blob/master/subbash/prompt

# ~/.git-prompt.sh
# Show dirty state next to the branch name
#   '*' unstaged changes
#   '+' staged changes
GIT_PS1_SHOWDIRTYSTATE=1
#   '$': stashed items
GIT_PS1_SHOWSTASHSTATE=1
#   '%': untracked files
GIT_PS1_SHOWUNTRACKEDFILES=1
# Difference between HEAD and its upstream:
#   '<'           behind
#   '>'           ahead
#   '<>'          diverged
#   '='           no difference
# Other values:
#   verbose       show number of commits ahead/behind (+/-) upstream
#   name          if verbose, then also show the upstream abbrev name
#   legacy        don't use the '--count' option available in recent
#                 versions of git-rev-list
#   git           always compare HEAD to @{upstream}
#   svn           always compare HEAD to your SVN upstream
GIT_PS1_SHOWUPSTREAM="auto"
# Colored dirty state hints if non empty
GIT_PS1_SHOWCOLORHINTS=

# Exit status symbol
PROMPT_SYMBOL="›" #→
PROMPT_SYMBOL_ERROR="×"

PROMPT_COMMAND='prompt_command'
PS2="$PROMPT_SYMBOL "

prompt_command() {
  # Exit code
  local ec=$?
  local user=$(whoami)
  local host=$(hostname)
  # No color
  local nc='\[${bblack}\]'

  local ps='\n'
  local pe='\n'

  # Prompt START

  # Set the terminal title to the current working directory
  ps+='\[\033]0;\w\007\]'

  # Right align datetime
  ps+='\[$(tput sc; prompt_right; tput rc)\]'

  if [[ "$user" == "root" ]]; then
    ps+='\[${red}\]'
  else
    ps+='\[${cyan}\]'
  fi
  # User
  ps+='\u'
  ps+='\[${reset}\]'

  # Display the hostname when != username
  if [[ "$user" != "$host" ]]; then
    ps+=$nc
    ps+=' at '
    # Highlight the hostname when connected via SSH
    if [[ -n "${SSH_TTY}" ]]; then
      ps+='\[${bold}\]'
      ps+='\[${red}\]'
    else
      ps+='\[${blue}\]'
    fi
    # Host
    ps+='\h'
    ps+='\[${reset}\]'
  fi

  ps+=$nc
  ps+=' in '
  ps+='\[${white}\]'
  # Working directory
  ps+='\w'
  ps+='\[${reset}\]'

  # TODO: colorize git prompt, yellow if != master?
  ps+='\[${red}\]'

  # Prompt END

  pe+=$(prompt_status $ec "\[${white}\]${PROMPT_SYMBOL} " "\[${red}\]${PROMPT_SYMBOL_ERROR} " )
  pe+='\[${reset}\]'

  # Prompt command

  __git_ps1 "$ps" "$pe"
}

prompt_right() {
  local date="$(date +%H:%M:%S)"

  if [[ ! -n $COLUMNS ]]; then
    COLUMNS=$(tput cols)
  fi

  #$(prompt_jobs)
  printf ${bblack}"%*s" $COLUMNS "$date"
}

# ✓
# ×
prompt_status() {
  local exit=$1
  local default="> "
  local default_error="x "
  local success="${2-$default}"
  local error="${3-$default_error}"
  local str=

  if [[ $exit -eq 0 ]]; then
    str="$success"
  else
    str="$error"
  fi

  printf "%b" "$str"
}
