#
# ~/.bashrc
#

PROMPT_SYMBOL="› " # $ ✓ →
PROMPT_SYMBOL_ERROR="× " # ! ×

# Load bash configuration
source ~/.bash.d/init.bash

# ~/.exports can be used to export variables
# ~/.path can be used to extend '$PATH'.
# ~/.extra can be used for other settings you don’t want to commit.
for file in ~/.{exports,path,extra}; do
  [[ -r "$file" ]] && [[ -f "$file" ]] && source "$file"
done
unset file

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# Autocorrect typos in path names when using 'cd'
shopt -s cdspell

# Enable some Bash 4 features when possible:
#   'autocd', e.g. '**/qux' will enter './foo/bar/baz/qux'
#   Recursive globbing, e.g. 'echo **/*.txt'
for option in autocd globstar; do
  shopt -s "$option" 2> /dev/null
done
