---
enabled: "{{ .features.gemini }}"
packages:
  # https://aistudio.google.com/app/apikey
  gemini-cli:
    nameOverwrite:
      mise: npm:@google/gemini-cli
      npm: "@google/gemini-cli"
    type: '{{ .features.mise | ternary "mise" "npm" }}'
