---
dependencies:

  - role: package
    packages:
      - i3 # window manager
      - rofi # window switcher
      - scrot # screenshot utility
      # - gtk-theme-arc #-git
      - xorg-xinit
      - xorg-server
      - xorg-server-utils

  - role: pacman-yaourt
    pacman_yaourt_packages:
      # - i3blocks
      - ttf-font-awesome
      - system-san-francisco-font-git

  - role: dotfiles
    paths:
      - name: i3
        dest: .config/i3
        pattern: 
          - bin
          - config
          - "*.conf"
      - name: i3/files/Xresources.d
        # src: roles/i3/files/Xresources.d
        dest: .Xresources.d
