---
dependencies:

  - role: package
    packages: "{{ i3_packages }}"

  - role: pacman-yaourt
    pacman_yaourt_packages: "{{ i3_yaourt_packages }}"
    when: "{{ ansible_os_family == 'Archlinux' }}"

  - role: dotfiles
    paths:
      - name: i3
        dest: "{{ i3_config_path | default('.config/i3') }}"
        pattern:
          - bin
          - config
          - "*.conf"
      - name: i3/files/Xresources.d
        # src: roles/i3/files/Xresources.d
        dest: .Xresources.d

  # TODO: xset r rate 200 25
