---
dependencies:

  - role: dotfiles
    role_dir: roles/system
    paths:
      - name: xresources
        prefix: .
        pattern: "*.j2" # "Xresources"
        template: yes
      - name: xresources/files/Xresources.d
        dest: .Xresources.d
