---
dependencies:

  - role: dotfiles
    paths:
      - name: system/xresources
        prefix: .
        pattern: "Xresources"
      - name: system/xresources/files/Xresources.d
        dest: .Xresources.d
