---
- name: Gathering facts
  hosts: all
  gather_facts: yes

- name: Setup local development environment
  hosts: local
  pre_tasks:
    - name: Update repository
      git:
        repo: git://github.com/LEI/dotfiles.git
        dest: "{{ dot_root }}"
        version: ansible
        update: no
      # ignore_errors: yes
  roles:
    - {role: hammerspoon, when: ansible_os_family == "Darwin"}
