---
# - name: Gathering facts
#   hosts: local
#   gather_facts: yes

- name: Bootstrap
  hosts: all
  tasks:
    - name: "Distribution: {{ ansible_distribution }}"
      group_by: key=os_{{ ansible_distribution }}

- name: Setup local development environment
  hosts: local
  # pre_tasks:
  #   - name: Update repository
  #     git:
  #       repo: git://github.com/LEI/dotfiles.git
  #       dest: "{{ dot_root }}"
  #       version: ansible
  #       update: no
  #     ignore_errors: yes
  roles:
    - git
    - pkg
    - npm
    - tmux
    - {role: vim, tags: ['vim']}

- name: Max OS X
  hosts: os_MacOSX
  roles:
    - hammerspoon
