---
# - name: Gathering facts
#   hosts: local
#   gather_facts: yes

- name: Bootstrap dotfiles and install packages
  hosts: local
  tasks:
    - name: "Distribution: {{ ansible_distribution }}"
      group_by: key=os_{{ ansible_distribution }}
      tags:
        - always

- name: Debian
  hosts: os_Debian
  tags:
    - deb
  roles:
    - {role: apt, tags: ['pkg','apt'], become: yes}

- name: Mac OS X
  hosts: os_MacOSX
  tags:
    - osx
  roles:
    - {role: homebrew, tags: ['pkg','brew']}
    - {role: hammerspoon, tags: ['ws','hs']}
    # - {role: defaults, tags:['defaults']}

- name: Setup local development environment
  hosts: local
  # pre_tasks:
  #   - name: Update repository
  #     git:
  #       repo: git://github.com/LEI/dotfiles.git
  #       dest: "{{ dot_root }}"
  #       version: ansible
  #       update: no
  #     ignore_errors: yes
  tags: ['common', 'cmn']
  roles:
    - {role: git, tags: ['git']}
    - {role: npm, tags: ['node','npm']}
    - {role: tmux, tags: ['tmux']}
    - {role: vim, tags: ['vim']}
    - {role: bash, tags: ['bash']}
    - {role: bin, tags: ['bin']}

