---
# - name: Gathering facts
#   hosts: local
#   gather_facts: yes

- name: Bootstrap
  hosts: local
  tasks:
    - name: "Distribution: {{ ansible_distribution }}"
      group_by: key=os_{{ ansible_distribution }}

# - name: Debian
#   hosts: os_Debian
#   roles:
#     - {role: debops.nodejs, tag: ['node']}
#   sudo: yes

- name: Setup local development environment
  hosts: local
  # pre_tasks:
  #   - name: Update repository
  #     git:
  #       repo: git://github.com/LEI/dotfiles.git
  #       dest: "{{ dot_root }}"
  #       version: ansible
  #       update: no
  #     ignore_errors: yes
  roles:
    - git
    - {role: pkg, tags: ['bootstrap']}
    - {role: npm, tags: ['node']}
    - {role: tmux, tags: ['tmux']}
    - {role: vim, tags: ['vim']}
  handlers:
    - include: handlers/symlink.yml

- name: Max OS X
  hosts: os_MacOSX
  roles:
    - hammerspoon

