---
extraPackages:
  carapace:
    enabled: '{{ eq .osIDLike "alpine" "darwin" "arch" "windows" }}'
    nameOverwrite:
      arch: carapace-bin
      windows: rsteube.Carapace
    type: '{{ eq .osIDLike "arch" | ternary "aur" nil }}'
