---
enabled: "{{ .features.carapace }}"
packages:
  # Alternatives:
  # https://github.com/nushell/nu_scripts/tree/main/custom-completions
  # https://github.com/sigoden/argc-completions
  carapace:
    # enabled: '{{ not (eq .osIDLike "debian") }}'
    nameOverwrite:
      arch: carapace-bin
      mise: aqua:carapace-sh/carapace-bin
      windows: rsteube.Carapace
    type: '{{ eq .osIDLike "arch" | ternary "aur"
      (not (eq .osIDLike "android" "arch" "darwin" "windows") | ternary "mise" nil) }}'
