---
- name: "Make sure {{ vim_plug_path }} exists"
  file:
    path: "{{ dot_home }}/{{ vim_plug_path }}"
    state: directory
    follow: true # autoload is a symlink
  tags: vim-plug

- name: Install vim-plug
  get_url:
    url: "{{ vim_plug_url }}"
    dest: "{{ dot_home }}/{{ vim_plug_path }}/{{ vim_plug_file }}"
  tags: vim-plug

# github.com/junegunn/vim-plug#pluginstall-and-plugupdate
# stackoverflow.com/questions/33672491/how-to-use-ansible-to-provision-vim-vundle-plugin
- name: Install vim plugins
  vars:
    # FIXME: Vim Warning:
    # Output is not to a terminal / Input is not from a terminal
    # -E -s -V +'source {{ dot_home }}/.vim/plug.vimrc' < /dev/tty
    # "silent" is required or vim hangs on YCM installation
    # YCM: ./install.py --tern-completer
    plug_install:  "vim -E -s -u '{{ dot_home }}/.vim/plug.vimrc' -N +'silent PlugInstall{{ '!' if vim_plug_force else '' }}' +qall"
    # plug_install:  "vim -u NONE +'source {{ dot_home }}/.vim/plug.vimrc' +'silent PlugInstall{{ '!' if vim_plug_force else '' }}' +qall"
  shell: "{{ plug_install }}"
  args:
    creates: "{{ false if vim_plug_force else dot_home + '/' + vim_plugins_path + '/*' }}"
  register: vim_plug_output
  # failed_when: vim_plug_output.rc != 0
  when: vim_plug_install
  tags: vim-plug

# - debug: var=vim_plug_output
