---
- include: osx.yml
  when: ansible_os_family == 'Darwin'

- include: debian.yml
  when: ansible_os_family == 'Debian'

- include: ../../files/tasks/symlinks.yml
#
#- name: Check files
#  stat:
#    path: "{{ dot_home }}/.vim/{{ item }}"
#  register: "sym"
#  with_items: "{{ symlinks }}"
#  failed_when: false
#
## - debug: var=sym
#
#- name: Backup files
#  command: "mv {{ dot_home }}/.vim/{{ item.item }} {{ dot_home }}/.vim/{{ item.item }}.bak"
#  args:
#    creates: "{{ dot_home }}/.vim/{{ item.item }}.bak"
#  # with_items: "{{ sym.results|map(attribute='item')|map(attribute='stat')|list }}"
#  with_items: "{{ sym.results }}"
#  when: item.stat.exists # and item.stat.lnk_source != "{{ dot_root }}/vim/{{ item.item }}"
#
#- name: Symlink files
#  file:
#    src: "{{ dot_root }}/vim/{{ item.item }}"
#    dest: "{{ dot_home }}/.vim/{{ item.item }}"
#    state: link
#  # with_items: "{{ sym.results|map(attribute='item')|list }}"
#  with_items: "{{ sym.results }}"
#  # when: item.stat.lnk_source != "{{ dot_root }}/vim/{{ item.item }}"

- name: Make sure .vim/autoload directory exists
  file: path={{ dot_home }}/{{ paths.src + '/' if paths.src else '' }}autoload state=directory

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ dot_home }}/{{ paths.src + '/' if paths.src else '' }}autoload/plug.vim"

- name: Install plugins
  command: vim +PlugInstall +qall
  when: vim_install_plugins
