---
- name: Check vim files
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
  with_items: "{{ vim_files }}"
  when: "{{ item.when | default(true) }}"

- name: Source vimrc from ~/.vim/init.vim
  lineinfile:
    dest: "{{ vim_rc }}"
    line: "source {{ nvim_init }}"
    backup: yes
    create: yes
    state: present
  when: "{{ nvim_present }}"

- name: Download vim-plug
  get_url:
    url: "{{ vim_plug_url }}"
    dest: "{{ vim_plug_file }}"
  tags: vim-plug
 
# - name: Clone dein
#   git:
#     repo: "{{ vim_dein_repo }}"
#     # https://github.com/Shougo/dein.vim/blob/master/bin/installer.sh
#     dest: "{{ vim_dein_path }}"

# https://github.com/junegunn/vim-plug#pluginstall-and-plugupdate
# https://stackoverflow.com/questions/33672491/how-to-use-ansible-to-provision-vim-vundle-plugin
- name: "Install vim {{ vim_plugins | length }} plugins"
  shell: "{{ vim_plug_cmd }}"
  args:
    creates: "{{ false if vim_plug_force else vim_plugins_path + '/*' }}"
  ignore_errors: yes
  register: vim_plug_output
  # failed_when: vim_plug_output.rc != 0
  when: vim_plug_install # and vim_plug_template.changed
  tags: vim-plug

- debug: var=vim_plug_output
