---
# themes/spotlight-dark.rasi:
#   type: file
#   url: https://raw.githubusercontent.com/newmanls/rofi-themes-collection/refs/heads/master/themes/spotlight-dark.rasi
#   refreshPeriod: 168h

# themes/spotlight.rasi:
#   type: file
#   url: https://raw.githubusercontent.com/newmanls/rofi-themes-collection/refs/heads/master/themes/spotlight.rasi
#   refreshPeriod: 168h

# themes/tokyonight.rasi:
#   type: file
#   # url: https://raw.githubusercontent.com/newmanls/rofi-themes-collection/refs/heads/master/themes/simple-tokyonight.rasi
#   url: https://raw.githubusercontent.com/Murzchnvok/rofi-collection/refs/heads/master/tokyonight/tokyonight.rasi
#   refreshPeriod: 168h
