---
extraPackages:
  # adwaita-icon-theme:
  #   enabled: '{{ (get .features "i3") }}'
  # papirus-icon-theme:
  #   enabled: '{{ (get .features "i3") }}'
  rofi: # dmenu, sunbeam
    enabled: '{{ (get .features "i3") }}'
  rofi-calc: # rofi -show calc -modi calc -no-show-match -no-sort
    enabled: '{{ (get .features "i3") }}'
  # rofi-greenclip: # cliphist
  #   enabled: '{{ (get .features "i3") }}'
  #   type: '{{ eq .osIDLike "arch" | ternary "aur" nil }}'
  rofi-power-menu:
    enabled: '{{ (get .features "i3") }}'
    type: '{{ eq .osIDLike "arch" | ternary "aur" nil }}'
  # rofimoji: # rofi -modi emoji:rofimoji -show emoji
  #   enabled: "{{ (get .features "i3") }}"
