---
extraPackages:
  # adwaita-icon-theme:
  #   enabled: "{{ .features.i3 }}"
  # papirus-icon-theme:
  #   enabled: "{{ .features.i3 }}"
  rofi: # dmenu
    enabled: "{{ .features.i3 }}"
  rofi-calc: # rofi -show calc -modi calc -no-show-match -no-sort
    enabled: "{{ .features.i3 }}"
  # rofi-greenclip: # cliphist
  #   enabled: "{{ .features.i3 }}"
  #   type: aur
  rofi-power-menu:
    enabled: "{{ .features.i3 }}"
    type: aur
  # rofimoji: # rofi -modi emoji:rofimoji -show emoji
  #   enabled: "{{ .features.i3 }}"
