---
- include: register_paths.yml

- name: Generate templates
  template:
    src: "{{ item }}.j2"
    dest: "{{ source }}{{ item }}"
    backup: yes
    # force: yes
  # args:
  #   creates: "{{ source }}{{ item.item }}"
  with_items: "{{ templates }}"
  # ignore_errors: True
  # failed_when: not item.stat.exists
  # when: item.stat.exists == false

# - name: Looking for templates
#   template:
#     src: "{{ item.item }}.j2"
#     dest: "{{ source }}{{ item.item }}"
#     backup: yes
#     # force: yes
#   # args:
#   #   creates: "{{ source }}{{ item.item }}"
#   register: templates
#   with_items: "{{ stat.results }}"
#   ignore_errors: True
#   # failed_when: not item.stat.exists
#   # when: item.stat.exists == false

# - name: fail the play if the previous command did not succeed
#   fail: msg={{ item.msg }}
#   when: item.failed|default(False) and 'No such' in item.msg
#   with_items: "{{ templates.results }}"
#   # when: "'FAILED' in templates.results"

# - name: Backup files
#   command: "mv  {{ dot_home }}/{{ paths.dst + '/' if paths.dst }}{{ item.item }}.{{ backup_ext|default('bak') }}"
#   args:
#     creates: "{{ dot_home }}/{{ paths.dst + '/' if paths.dst }}{{ item.item }}.{{ backup_ext|default('bak') }}"
#   # with_items: "{{ stat.results|map(attribute='item')|map(attribute='stat')|list }}"
#   with_items: "{{ stat.results }}"
#   when: item.stat.exists #and item.stat.lnk_source != "{{ dot_root }}/{{ paths.src + '/' if paths.src }}{{ item.item }}"
#   no_log: yes
