---
# - set_fact:
#     app: "{{ item }}"

- name: "Write {{ app.key }} defaults"
  osx_defaults:
    key: "{{ item.key }}" # Required
    domain: "{{ item.value.domain | default(omit) }}" # Default: NSGlobalDomain
    state: "{{ item.value.state | default('present') }}" # Default: present
    type: "{{ item.value.type | default(omit) }}" # Default: string
    value: "{{ item.value.value | default(omit) }}" # Required when state = present
    array_add: "{{ item.value.array_add | default(omit) }}"
    host: "{{ item.value.host | default(omit) }}" # Default: currentHost
  with_dict: "{{ app.value }}" # TODO: when condition?
  notify: "killall {{ app.key }}"
