---
# Default file and URL scheme handlers for macOS (duti)
# Enforced by run_onchange_after_service.sh.tmpl
duti:
  utis:
    com.neovide.neovide:
      - public.bash-script
      - public.data
      - public.json
      - public.plain-text
      - public.shell-script
      - public.unix-executable
      - public.yaml
  extensions:
    com.neovide.neovide:
      - bash
      # - c # Xcode default
      - cfg
      - cmake
      - conf
      # - cpp # Xcode default
      - css
      - dart
      - diff
      - dockerfile
      - gemspec
      - go
      # - h # Xcode default
      # - hpp # Xcode default
      - ini
      - java
      - js
      - json
      - jsx
      - kt
      - lock
      # - log # Console.app default
      - lua
      - makefile
      - md
      - ml
      - patch
      - pl
      - pm
      # - proto # TextEdit default
      - py
      - rb
      - rs
      - sh
      - sql
      - svelte
      # - swift # Xcode default
      - tmpl # Default: unset
      - toml
      - ts
      - tsx
      - txt
      - vue
      - xml
      - yaml
      - yml
      - zsh # Default: com.apple.dt.Xcode
    com.google.Chrome:
      - html
    com.microsoft.Excel:
      - csv
  schemes:
    com.google.Chrome:
      - http
      - https
    com.apple.mail:
      - mailto
