---
enabled: "{{ .features.neovim }}"
packages:
  # NOTE: latest nvim requires GLIBC_2.42
  neovim:
    enabled: '{{ or (ne .osIDLike "debian") (gt .glibc 2.31) }}'
    nameOverwrite:
      windows: '{{ eq .packageType "winget" | ternary "Neovim.Neovim" nil }}'
    type: '{{ eq .packageType "npm" "gem" | ternary .packageType nil }}'
