---
packages:
  # NOTE: latest nvim requires GLIBC_2.42
  neovim:
    enabled: '{{ and .features.neovim (or (ne .osIDLike "debian") (not .glibc231)) }}'
    nameOverwrite:
      windows: '{{ eq .packageType "winget" | ternary "Neovim.Neovim" nil }}'
    type: '{{ eq .packageType "npm" "gem" | ternary .packageType nil }}'
  copilot:
    enabled: '{{ and .features.neovim .features.ai (eq .osIDLike "arch" "darwin" "windows") }}'
    nameOverwrite:
      npm: "@github/copilot"
      darwin: copilot-cli
    type: '{{ eq .osIDLike "arch" | ternary "aur" (eq .osIDLike "darwin" | ternary "cask" "npm") }}'
