---
enabled: "{{ .features.neovim }}"
packages:
  gs:
    description: Interpreter for PostScript and PDF
    type: brew
  mmdc:
    enabled: '{{ ne .os "android" }}' # FIXME(pupeteer): current platform not supported
    nameOverwrite:
      mise: npm:@mermaid-js/mermaid-cli
      npm: "@mermaid-js/mermaid-cli"
    type: '{{ .features.mise | ternary "mise" "npm" }}'
  neovim:
    # enabled: '{{ or (ne .osIDLike "debian") (eq .libc "gnu") }}'
    nameOverwrite:
      windows: '{{ eq .packageType "winget" | ternary "Neovim.Neovim" nil }}'
    type: '{{ if eq .packageType "npm" "gem" -}}
      {{ .packageType }}
      {{- else if or (and (eq .osIDLike "debian") (ne .libc "gnu")) (eq .osIDLike "fedora") -}}
      mise
      {{- else }}
      {{- end }}'
    # version: 0.12.1
  # darwin python3 host, linux uses run_onchange_after_install-python-host.sh
  pynvim:
    enabled: '{{ and .features.python (eq .osIDLike "darwin") }}'
    type: uv
  tree-sitter:
    type: brew
  tree-sitter-cli:
    type: brew
