---
packages:
  # NOTE: latest nvim requires GLIBC_2.42
  neovim:
    enabled: '{{ and .features.neovim (or (ne .osIDLike "debian") (not .glibc231)) }}'
    nameOverwrite:
      # android: neovim
      # arch: neovim
      # darwin: neovim
      windows: neovim.neovim
    type: '{{ eq .packageType "npm" "gem" | ternary .packageType nil }}'
