---
dependencies:

  - role: package
    packages:
      - irssi

  - role: dot.symlink
    dot_files:
      irssi:
        dest: .irssi

  - role: dot.template
    dot_files:
      irssi:
        dest: .irssi
