---
dependencies:

  - role: package
    packages:
      - irssi

  - role: symlink
    dot_files:
      irssi:
        dest: .irssi

  - role: template
    dot_files:
      irssi:
        dest: .irssi
