---
- name: Common environment
  hosts: all
  gather_facts: no
  tags: [common]

  roles:

    # Git via homebrew or apt
    - role: git
      tags: [git, vcs]

    # Composer & PHP
    - role: composer
      tags: [composer, php]

    # NodeJS & global npm packages
    - role: npm
      tags: [npm, node, js]

    # Python packages
    # - role: pyhton?
    - role: pip
      tags: [pip]

    # Ruby gems and .gemrc
    - role: ruby
      tags: [ruby, gem]
