---
- name: Common environment
  hosts: all
  gather_facts: no
  tags: [common]

  roles:

    # Update and configure Git
    - role: git
      tags: [git, vcs]

    # Install PHP and Composer packages
    - role: composer
      tags: [composer, php]

    # Install NodeJS and npm packages
    - role: npm
      tags: [npm, node, js]

    # - role: pyhton?
    # Install python packages
    - role: pip
      tags: [pip]

    # Install ruby gems
    - role: ruby
      tags: [ruby, gem]

    # Install go lang
    - role: go
      tags: [go]
