---
- name: Common environment
  hosts: all
  gather_facts: no
  tags: [common]

  roles:

    # Composer & PHP
    - role: composer
      tags: [composer, php]

    # NodeJS & global npm packages
    - role: npm
      tags: [npm, js]

    # Git via homebrew or apt
    - role: git
      tags: [git, vcs]

    - role: bash
      tags: [bash]

    - role: bin
      tags: [bin]

    - role: home
      tags: [home]

    - role: tmux
      tags: [tmux]

    - role: vim
      tags: [vim]
