---
- name: Common roles
  hosts: all
  gather_facts: no
  tags: [common]

  roles:

    - role: bash
      tags: [bash]
      files:
        prefix: .

    - role: bin
      tags: [bin]
      files:
        src: bin
        dest: bin

    - role: common
      tags: [cmn]
      files:
        prefix: .
      templates:
        prefix: .

    - role: git
      tags: [git]
      files:
        prefix: .
      templates:
        prefix: .

    - role: tmux
      tags: [tmux]
      templates:
        dest: .tmux

    - role: vim
      tags: [vim]
      files:
        dest: .vim
