---
- name: Local development environment
  hosts: local
  gather_facts: no
  tags: [common]

  roles:

    # Tools

    - role: git
      tags: [git, vcs]
      files:
        prefix: .
      templates:
        prefix: .

    - role: npm
      tags: [npm, js]
      packages: "{{ npm_packages }}"

    - role: composer
      tags: [composer, php]

    - role: irssi
      tags: [irssi, irc]
      files:
        dest: .irssi
      templates:
        dest: .irssi

    - role: tmux
      tags: [tmux]
      templates:
        dest: .tmux

    - role: vim
      tags: [vim]
      files:
        dest: .vim

    # Dotfiles

    - role: bash
      tags: [bash, files]
      files:
        prefix: .

    - role: bin
      tags: [bin, files]
      files:
        src: bin
        dest: bin

    - role: common
      tags: [cmn, files]
      files:
        prefix: .
      templates:
        prefix: .
