---
- name: Local development environment
  hosts: local
  gather_facts: no
  tags: [common]

  roles:

    # Dotfiles

    - role: bash
      tags: [bash]
      files:
        prefix: .

    - role: bin
      tags: [bin]
      files:
        src: bin
        dest: bin

    - role: common
      tags: [cmn]
      files:
        prefix: .
      templates:
        prefix: .

    # Tools

    - role: git
      tags: [git]
      files:
        prefix: .
      templates:
        prefix: .

    # Install node and global npm packages
    - role: npm
      tags: [npm, node, js]
      packages: "{{ npm_packages }}"

    - role: tmux
      tags: [tmux]
      templates:
        dest: .tmux

    - role: vim
      tags: [vim]
      files:
        dest: .vim

    - role: irssi
      tags: [irssi, irc]
      files:
        dest: .irssi
      templates:
        dest: .irssi
