---
- name: Local environment
  hosts: local
  gather_facts: no
  tags: [local]

  roles:

    - role: symlink
      dot_files:
        ruby:
          prefix: .

    # - role: ssh
    #   tags: [ssh]

    # - role: weechat
    #   tags: [weechat, irc]
