---
- name: Local environment
  hosts: local
  gather_facts: no
  tags: [local]

  roles:

    - role: home
      tags: [home]

    - role: ssh
      tags: [ssh]

    - role: irssi
      tags: [irssi, irc]
