---
- name: Local environment
  hosts: local
  gather_facts: no
  tags: [local]

  roles:

    # Shell dotfiles
    - role: shell
      tags: [bash, bin, shell]

    # Tmux
    - role: tmux
      tags: [tmux]

    # Vim
    - role: vim
      tags: [vim]

    # - role: ssh
    #   tags: [ssh]

    # - role: weechat
    #   tags: [weechat, irc]
