---
- name: MacOSX roles
  hosts: os_macosx
  gather_facts: no
  tags: [osx]

  roles:

    - role: homebrew
      tags: [brew, cask]

    # brew install
    - role: package
      tags: [pkg]
      packages: "{{ brew_packages }}"

    # brew cask install
    - role: cask
      tags: [cask]
      packages: "{{ brew_casks }}"

    # Install node and global npm packages
    - role: npm
      tags: [node, npm]
      packages: "{{ npm_packages }}"

    # Window manager
    - role: hammerspoon
      tags: [ws, hs]
      files:
        dest: .hammerspoon

    # - role: osx
    #   tags: [defaults]
