---
- name: MacOSX roles
  hosts: os_macosx
  gather_facts: no
  tags: [osx]

  roles:

    # brew update, upgrade, cleanup
    - role: homebrew
      tags: [brew, cask]

    # brew install
    - role: package
      tags: [pkg]
      packages: "{{ homebrew_packages }}"

    # brew cask install
    - role: cask
      tags: [cask]

    # Window manager
    - role: hammerspoon
      tags: [ws, hs]
      files:
        dest: .hammerspoon

    # - role: osx
    #   tags: [defaults]
