---
- name: Setup hosts
  hosts: all
  gather_facts: yes

  # pre_tasks:

  #   - name: Update dotfiles repository
  #     tags: ['repo']
  #     git:
  #       repo: "{{ dot_repo }}"
  #       dest: "{{ dot_root }}"
  #       version: "{{ dot_version | default('HEAD') }}"
  #       # Discard any modified files in the working repository
  #       force: no
  #       # Retrieve new revisions from the origin repository
  #       update: no
  #     # ignore_errors: yes

  tasks:

    # - debug: var=inventory_hostname

    - name: "Gyoup hosts by OS distribution"
      group_by: key=os_{{ ansible_distribution | lower }}
      tags: [always]
    - debug: var=group_names

    # - name: "Load OS specific vars"
    #   include_vars: "{{ item }}"
    #   with_first_found:
    #     - "vars/{{ ansible_distribution | lower }}.yml"
    #     - "vars/{{ ansible_os_family | lower }}.yml"
    #     - "vars/os_defaults.yml"

- include: "debian.yml"
  when: ansible_distribution == 'Debian'

- include: "macosx.yml"
  when: ansible_distribution == 'MacOSX'

- include: "all.yml"

- include: "local.yml"
  when: "'local' in group_names"
