---
- name: Archlinux roles
  hosts: os_archlinux
  gather_facts: no
  tags: [arch]

  roles:

    # Update and upgrade pacman
    - role: pacman
      tags: [pacman]

    # Install apt packages
    - role: package
      tags: [pkg]
      packages: "{{ pacman_packages }}"

    # Install yaourt packages
    - role: pacman-yaourt
      tags: [yaourt]
      yaourt_packages: "{{ pacman_yaourt_packages }}"
