---
- name: Windows roles
  hosts: os_cygwin
  gather_facts: no
  tags: [win]

  roles:

    # Install apt packages
    - role: package
      tags: [pkg]
      packages: "{{ apt_cyg_packages }}"

    - role: cygwin
      tags: [cyg]
