---
- name: Debian roles
  hosts: os_debian
  gather_facts: no
  tags: [deb]

  roles:

    # Update and upgrade apt
    - role: apt
      tags: [apt]

    # Install apt packages
    - role: package
      tags: [pkg]
      packages: "{{ apt_packages }}"

    - role: i3
      tags: [i3, wm]
      gtk_theme: arc

    - role: rxvt
      tags: [rxvt]
