---
- name: Debian roles
  hosts: os_debian
  gather_facts: no
  tags: [deb]

  # geerlingguy.nodejs
  vars:
    nodejs_forever: false
    nodejs_npm_global_packages: "{{ npm_packages }}"

  roles:

    - role: apt
      tags: [apt]

    - role: package
      tags: [pkg]
      packages: "{{ apt_packages }}"

    - role: geerlingguy.nodejs # Requires the EPEL repository on RedHat/CentOS
      become: yes
      tags: [node, npm]
      when: "ansible_os_family == 'Debian'"
