---
- name: MacOSX roles
  hosts: os_macosx
  gather_facts: no
  tags: [osx]

  roles:

    # Homebrew update, upgrade, tap...
    - role: homebrew
      tags: [brew, cask]

    # Homebrew packages
    - role: package
      tags: [pkg]
      packages: "{{ homebrew_packages }}"

    # Homebrew Cask applications
    - role: homebrew-cask
      tags: [cask]
      homebrew_cask_apps: "{{ cask_apps }}"
      homebrew_cask_options: "{{ cask_options }}"

    # Hammerspoon
    - role: hammerspoon
      tags: [ws, hs]

    # OSX defaults
    - role: osx-defaults
      tags: [defaults]
