---
- name: MacOSX roles
  hosts: os_macosx
  gather_facts: no
  tags: [osx]

  roles:

    # Homebrew update, upgrade, tap...
    - role: homebrew
      tags: [brew, cask]

    # Homebrew packages
    - role: package
      tags: [pkg]
      packages: "{{ homebrew_packages }}"

    # Homebrew Cask applications
    - role: homebrew-cask
      tags: [cask]

    # NodeJS
    - role: package
      tags: [node, npm, js]
      packages:
        - node

    # Hammerspoon
    - role: hammerspoon
      tags: [ws, hs]
      # files:
      #   dest: .hammerspoon

    # OSX defaults
    - role: osx-defaults
      tags: [defaults]

    # - role: osx-dock

    # - role: osx-terminal
