---
- name: Windows roles
  hosts: os_windows
  gather_facts: no
  tags: [win]
  tasks:
    - debug: var=ansible_os_family
  roles:

    # Install apt packages
    - role: package
      tags: [pkg]
      packages: "{{ apt_cyg_packages }}"

    - role: cygwin
      tags: [cyg]
