---
# getcomposer.org/download/

#   php -r "readfile('https://getcomposer.org/installer');" > composer-setup.php
#   php -r "if (hash('SHA384', file_get_contents('composer-setup.php')) === '41e71d86b40f28e771d4bb662b997f79625196afcca95a5abf44391188c695c6c1456e16154c75a211d238cc3bc5cb47') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
#   php composer-setup.php
#   php -r "unlink('composer-setup.php');

# https://composer.github.io/pubkeys.html
- name: Download Composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: "{{ tmp_dir }}composer-setup.php"
    mode: 0755
    checksum: "sha384:7228c001f88bee97506740ef0888240bd8a760b046ee16db8f4095c0d8d525f2367663f22a46b48d072c816e7fe19959"

- name: Run Composer installer
  shell: "{{ php_executable }} composer-setup.php --install-dir={{ composer_bin_path }} --filename=composer {% if composer_version != '' %} --version={{ composer_version }}{% endif %}"
  args:
    chdir: "{{ tmp_dir }}"
  become: "{{ 'yes' if ansible_os_family != 'Darwin' else 'no' }}"

# - name: Move Composer to be accessed globally
#   shell: "mv {{ tmp_dir }}composer.phar {{ composer_path }}"
#   args:
#     creates: "{{ composer_path }}"
