---
# github.com/geerlingguy/ansible-role-composer
# github.com/osxstrap/ansible-osx-php

- name: Check if Composer is installed
  stat:
    path: "{{ composer_bin_path }}/composer"
  register: composer_bin

- include: install-composer.yml
  when: composer_force_install or not composer_bin.stat.exists

# - name: Ensure Composer is executable
#   file:
#     path: "{{ composer_bin_path }}/composer"
#     mode: a+x
#     state: file

- name: Update Composer
  # composer:
  #   command: self-update
  #   working_dir: "{{ composer_home_path }}"
  shell: "{{ php_executable }} {{ composer_bin_path }}/composer self-update"
  register: composer_update_result
  when: composer_update
  changed_when: "'Updating to version' in composer_update_result.stdout"
  become: "{{ 'yes' if ansible_os_family != 'Darwin' else 'no' }}"

- include: global-require.yml
  when: composer_packages | length > 0
