---
# https://github.com/SummitRoute/osxlockdown/blob/master/commands.yaml

# TODO: idempotent (changed?)
# - name: Setup system
#   include: system.yml
#   with_dict: "{{ osx_system }}"
#   tags: systemsetup

# Set up OSX defaults
# docs.ansible.com/ansible/osx_defaults_module.html
- name: Setup defaults
  include: defaults.yml
  # vars: # using set_fact instead to notify handlers
  #   app: "{{ item }}"
  with_dict: "{{ osx_defaults }}"
  register: osx_defaults_write

- name: Restart defaults server
  command: killall cfprefsd
  when: osx_defaults_write.changed

# - name: Verify defaults
#   assert:
#     that:
#       - timezone | default('') != ''
#       - osx_defaults.natural_scroll in [true, false]
#       - osx_defaults.notification_center in [true, false]
#       - osx_defaults.ssd_tweaks in [true, false]

# - debug: var=osx_defaults
#   when: log_enable
