---
- name: "Check packages state : {{ packages_state }}"
  package:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default(packages_state) }}"
  with_items: "{{ packages }}"
  become: yes
  when: "packages_install and ansible_distribution != 'Darwin'"

- name: "Check packages state : {{ packages_state }}"
  homebrew:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default(packages_state) }}"
    install_options: "{{ item.state | default(packages_state) }}"
  with_items: "{{ packages }}"
  when: "packages_install and ansible_distribution == 'Darwin'"
