---
dependencies:

  - role: package
    packages:
      - tmux
  #   when: "ansible_os_family == 'Debian'"

  # - role: brew
  #   packages:
  #     - tmux
  #     # - reattach-to-user-namespace
  #   when: "ansible_os_family == 'Darwin'"

  - role: template
    dot_files:
      tmux:
        dest: .tmux
        pattern: "tmux-*.conf.j2"

  - role: symlink
    dot_files:
      tmux:
        dest: .tmux

  - role: template
    dot_files:
      tmux:
        dest: .tmux
        pattern: "tmux.conf.j2"
