---
dependencies:

  - role: package
    packages: "{{ tmux_packages }}"

  # - role: brew
  #   packages:
  #     - tmux
  #     # - reattach-to-user-namespace
  #   when: "ansible_os_family == 'Darwin'"

  - role: line-in-file
    lines: "{{ tmux_lines }}"

  - role: dotfiles
    paths:
      - name: tmux
        dest: .tmux
      - name: tmux
        dest: .tmux
        pattern: "*.conf.j2" # tmux|tmux-{{ os | lower }}
        template: yes
