---
- include: register_paths.yml

- name: Gather file info
  stat:
    path: "{{ destination }}{{ prefix|default('') }}{{ item }}"
    follow: false
  register: stat
  with_items: "{{ files }}"
  # failed_when: false

- include: backups.yml
  when: enable_backup

# # Source relative to dot_root, destination relative to dot_home
# - name: Symlink items
#   file:
#     src: "{{ dot_root }}/{{ paths.src + '/' if paths.src }}{{ item.src|default(item) }}"
#     dest: "{{ dot_home }}/{{ paths.dst + '/' if paths.dst }}{{ prefix|default('') }}{{ item.dst|default(item) }}"
#     state: link
#   with_items: "{{ symlinks }}"

# Source relative to dot_root, destination relative to dot_home
- name: Symlink files
  file:
    src: "{{ source }}{{ item.src|default(item) }}"
    dest: "{{ destination }}{{ prefix|default('') }}{{ item.dst|default(item)|basename }}"
    state: link
  with_items: "{{ files }}"
  # fail_when;: false

# # first ensure our target directory exists
# - file: dest=/etc/fooapp state=directory
#
# # copy each file over that matches the given pattern
# - copy: src={{ item }} dest=/etc/fooapp/ owner=root mode=600
#   with_fileglob:
#     - /playbooks/files/fooapp/*
# # relative to the roles/<rolename>/files directory.
