---
- include: targets.yml

- name: Check template destination
  stat:
    path: "{{ destination }}{{ prefix|default('') }}{{ item }}"
    follow: false
  register: backup_files
  with_items: "{{ templates }}"
  when: enable_backup
  # failed_when: false

# - name: Backup templates
#   vars:
#     dst: "{{ destination }}{{ prefix|default('') }}{{ item.item }}"
#   command: "mv {{ dst }} {{ dst }}.{{ backup_ext|default('bak') }}"
#   args:
#     creates: "{{ dst }}.{{ backup_ext|default('bak') }}"
#   # with_items: "{{ stat.results|map(attribute='item')|map(attribute='stat')|list }}"
#   with_items: "{{ backup_files.results }}"
#   when: enable_backup and item.stat.exists and backup_templates
#     # (backup_templates and item.stat.path != source + item.item)
#   no_log: yes

- name: Generate templates
  template:
    src: "{{ item.src|default(item) }}.j2"
    dest: "{{ destination }}{{ prefix|default('') }}{{ item.dst|default(item) }}"
    backup: "{{ 'yes' if backup_templates else 'no' }}"
    # force: yes
  # args:
  #   creates: "{{ source }}{{ item.item }}"
  with_items: "{{ templates }}"
  # ignore_errors: True
  # failed_when: not item.stat.exists
  # when: item.stat.exists == false

# - name: Looking for templates
#   template:
#     src: "{{ item.item }}.j2"
#     dest: "{{ source }}{{ item.item }}"
#     backup: yes
#     # force: yes
#   # args:
#   #   creates: "{{ source }}{{ item.item }}"
#   register: templates
#   with_items: "{{ stat.results }}"
#   ignore_errors: True
#   # failed_when: not item.stat.exists
#   # when: item.stat.exists == false

# - name: fail the play if the previous command did not succeed
#   fail: msg={{ item.msg }}
#   when: item.failed|default(False) and 'No such' in item.msg
#   with_items: "{{ templates.results }}"
#   # when: "'FAILED' in templates.results"

# - name: Backup files
#   command: "mv  {{ dot_home }}/{{ paths.dst + '/' if paths.dst }}{{ item.item }}.{{ backup_ext|default('bak') }}"
#   args:
#     creates: "{{ dot_home }}/{{ paths.dst + '/' if paths.dst }}{{ item.item }}.{{ backup_ext|default('bak') }}"
#   # with_items: "{{ stat.results|map(attribute='item')|map(attribute='stat')|list }}"
#   with_items: "{{ stat.results }}"
#   when: item.stat.exists #and item.stat.lnk_source != "{{ dot_root }}/{{ paths.src + '/' if paths.src }}{{ item.item }}"
#   no_log: yes
